# MR604 Thesis — Notebook 1: Gemma-2B Implementation


## Conditions Covered
- **REF**: Qwen2.5-14B-Instruct Zero-Shot (larger model reference for RQ1)
- **R5**: Gemma-2B LoRA Fine-Tuning and Evaluation
- **R6**: Gemma-2B QLoRA Fine-Tuning and Evaluation

## Hardware
- NVIDIA A100 40GB on Google Colab Pro

## Expected Total Time
- 1.5 to 2 hours on A100

---

## Instructions Before Running
1. Accept Gemma-2B terms at: https://huggingface.co/google/gemma-2b-it
2. Add `HF_TOKEN` to Colab Secrets (key icon in left sidebar)
3. Set Runtime to **GPU > A100** in Runtime > Change runtime type
4. Create folder `MR603_Thesis/results`, `MR603_Thesis/adapters`, `MR603_Thesis/checkpoints` in Google Drive

In [1]:
# ═══════════════════════════════════════════════════════════
# CELL 1: Install all required libraries with pinned versions
# Pinned versions ensure full reproducibility
# Run this cell then RESTART RUNTIME before Cell 2
# ═══════════════════════════════════════════════════════════




# Remove existing bitsandbytes completely
!pip uninstall bitsandbytes -y -q

# Install bitsandbytes built specifically for CUDA 12.x
!pip install bitsandbytes --upgrade -q

!pip install -q "accelerate>=1.1.0"

# Verify bitsandbytes CUDA is working
import subprocess
result = subprocess.run(
    ['python', '-m', 'bitsandbytes'],
    capture_output=True, text=True
)
print(result.stdout[:500] if result.stdout else 'No output')
print(result.stderr[:500] if result.stderr else '')

# Install remaining libraries
!pip install transformers==4.44.0 -q
!pip install peft==0.12.0 -q
!pip install trl==0.9.6 -q
!pip install datasets==2.21.0 -q
!pip install accelerate==0.33.0 -q
!pip install evaluate==0.4.3 -q
!pip install numpy==1.26.4 -q

print('=' * 55)
print('All libraries installed')
print('Restart runtime now then run Cell 2')
print('=' * 55)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 33.9 MB/s eta 0:00:00
=================== bitsandbytes v0.50.2 ===================
Platform: Linux-6.6.122+-x86_64-with-glibc2.39
  libc: glibc-2.39
Python: 3.13.15
PyTorch: 2.11.0+cu128
  CUDA: 12.8
  HIP: N/A
  XPU: N/A
Related packages:
  accelerate: 1.15.0
  diffusers: 0.40.0
  numpy: 1.26.4
  pip: 24.1.2
  peft: 0.12.0
  safetensors: 0.8.0
  transformers: 5.16.1
  triton: 3.6.0
  trl: 0.9.6
============================================================
PyTorch settings found: CUDA_VERSION=128, Highest Compute Capa

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  error: subprocess-exited-with-error

  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for tokenizers (pyproject.toml) ... error
  ERROR: Failed building wheel for tokenizers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (tokenizers)
=======================================================
All libraries installed
Restart runtime now then run Cell 2
=======================================================

In [2]:
# ═══════════════════════════════════════════════════════════
# CELL 2: Verify A100 GPU and all library versions
# Run immediately after restarting runtime
# ═══════════════════════════════════════════════════════════

import torch

print('=' * 55)
print('GPU VERIFICATION')
print('=' * 55)

if torch.cuda.is_available():
    gpu_name   = torch.cuda.get_device_name(0)
    total_vram = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f'GPU:              {gpu_name}')
    print(f'Total VRAM:       {total_vram:.1f} GB')
    print(f'CUDA version:     {torch.version.cuda}')
    print(f'PyTorch version:  {torch.__version__}')
    print(f'bfloat16 support: {torch.cuda.is_bf16_supported()}')
    if 'A100' in gpu_name:
        print()
        print('A100 confirmed.')
        print('Native 4-bit arithmetic supported.')
        print('40 GB VRAM available.')
        print('All conditions will fit comfortably.')
    else:
        print(f'Warning: Expected A100 but got {gpu_name}')
        print('Change runtime type to A100 and restart.')
else:
    print('No GPU detected.')
    print('Runtime > Change runtime type > GPU > A100')

print()
print('=' * 55)
print('LIBRARY VERSIONS')
print('=' * 55)

import transformers, peft, trl, bitsandbytes
import datasets, evaluate, numpy

print(f'transformers:   {transformers.__version__}')
print(f'peft:           {peft.__version__}')
print(f'trl:            {trl.__version__}')
print(f'bitsandbytes:   {bitsandbytes.__version__}')
print(f'datasets:       {datasets.__version__}')
print(f'evaluate:       {evaluate.__version__}')
print(f'numpy:          {numpy.__version__}')
print()
print('All versions verified.')

=======================================================
GPU VERIFICATION
=======================================================
GPU:              NVIDIA A100-SXM4-40GB
Total VRAM:       42.4 GB
CUDA version:     12.8
PyTorch version:  2.11.0+cu128
bfloat16 support: True

A100 confirmed.
Native 4-bit arithmetic supported.
40 GB VRAM available.
All conditions will fit comfortably.

=======================================================
LIBRARY VERSIONS
=======================================================
transformers:   5.16.1
peft:           0.12.0
trl:            0.9.6
bitsandbytes:   0.50.2
datasets:       2.21.0
evaluate:       0.4.3
numpy:          1.26.4

All versions verified.

In [3]:
# ═══════════════════════════════════════════════════════════
# CELL 3: Set all random seeds for full reproducibility
# Seed 42 applied across Python, NumPy, PyTorch, and CUDA
# Same seed used across all conditions and all notebooks
# ═══════════════════════════════════════════════════════════

import torch
import numpy as np
import random
import os

SEED = 42

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark     = False

set_seed(SEED)

print(f'Random seed {SEED} applied to:')
print(f'  Python random module')
print(f'  NumPy random module')
print(f'  PyTorch CPU and GPU')
print(f'  CUDA all devices')
print(f'  PYTHONHASHSEED environment variable')
print()
print(f'Reproducibility confirmed.')

Random seed 42 applied to:
  Python random module
  NumPy random module
  PyTorch CPU and GPU
  CUDA all devices
  PYTHONHASHSEED environment variable

Reproducibility confirmed.

In [3]:
# ═══════════════════════════════════════════════════════════
# CELL 4: Mount Google Drive
# All results, adapters, and checkpoints saved here
# Sign in with your Google account when prompted
# ═══════════════════════════════════════════════════════════

from google.colab import drive
drive.mount('/content/drive')

import os

BASE_DIR       = '/content/drive/MyDrive/MR603_Thesis'
RESULTS_DIR    = f'{BASE_DIR}/results'
ADAPTER_DIR    = f'{BASE_DIR}/adapters'
CHECKPOINT_DIR = f'{BASE_DIR}/checkpoints'

os.makedirs(RESULTS_DIR,    exist_ok=True)
os.makedirs(ADAPTER_DIR,    exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

print('Google Drive mounted successfully')
print()
print(f'Directory structure:')
print(f'  Base:         {BASE_DIR}')
print(f'  Results:      {RESULTS_DIR}')
print(f'  Adapters:     {ADAPTER_DIR}')
print(f'  Checkpoints:  {CHECKPOINT_DIR}')

test_file = f'{RESULTS_DIR}/.write_test'
with open(test_file, 'w') as f:
    f.write('write test')
os.remove(test_file)
print()
print('Drive is writable. All results will be saved automatically.')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Google Drive mounted successfully

Directory structure:
  Base:         /content/drive/MyDrive/MR603_Thesis
  Results:      /content/drive/MyDrive/MR603_Thesis/results
  Adapters:     /content/drive/MyDrive/MR603_Thesis/adapters
  Checkpoints:  /content/drive/MyDrive/MR603_Thesis/checkpoints

Drive is writable. All results will be saved automatically.

In [4]:
# ═══════════════════════════════════════════════════════════
# CELL 5: HuggingFace login
# Required for Gemma-2B access
# Make sure HF_TOKEN is added to Colab Secrets first
# ═══════════════════════════════════════════════════════════

from huggingface_hub import login
from google.colab import userdata

try:
    hf_token = userdata.get('HF_TOKEN')
    login(token=hf_token)
    print('Logged in to HuggingFace using Colab secrets')
    print('Gemma-2B access will be granted')
    print('Qwen2.5-14B access confirmed (no special terms needed)')
except Exception as e:
    print(f'Could not read Colab secret: {e}')
    print('Falling back to manual entry...')
    hf_token = input('Paste your HuggingFace token here: ')
    login(token=hf_token)
    print('Logged in manually')

Could not read Colab secret: Secret HF_TOKEN does not exist.
Falling back to manual entry...
Paste your HuggingFace token here: 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
Logged in manually

In [6]:
# ============================================================
# SEED / REPRODUCIBILITY
# Run this before Cell 6
# ============================================================

import random
import numpy as np
import torch
import os

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

os.environ["PYTHONHASHSEED"] = str(SEED)

print("Seed:", SEED)

Seed: 42

In [7]:
# ═══════════════════════════════════════════════════════════
# CELL 6: Define all configuration
# All hyperparameters in one place
# Fixed across all conditions
# ═══════════════════════════════════════════════════════════

MODEL_ID       = 'google/gemma-2b-it'
MODEL_NAME     = 'Gemma-2B'
QWEN_MODEL_ID  = 'Qwen/Qwen2.5-14B-Instruct'
QWEN_NAME      = 'Qwen2.5-14B-Instruct'

LORA_R               = 16
LORA_ALPHA           = 32
LORA_DROPOUT         = 0.05
LORA_TARGET_MODULES  = ['q_proj', 'k_proj', 'v_proj', 'o_proj']

LEARNING_RATE    = 2e-4
NUM_EPOCHS       = 3
BATCH_SIZE       = 4
GRAD_ACCUM       = 4
EFFECTIVE_BATCH  = BATCH_SIZE * GRAD_ACCUM
MAX_SEQ_LENGTH   = 512
WARMUP_RATIO     = 0.03
MAX_NEW_TOKENS   = 64

print('=' * 55)
print('EXPERIMENTAL CONFIGURATION')
print('=' * 55)
print(f'SLM model:          {MODEL_ID}')
print(f'Reference model:    {QWEN_MODEL_ID}')
print()
print(f'LoRA configuration:')
print(f'  Rank (r):         {LORA_R}')
print(f'  Alpha:            {LORA_ALPHA}')
print(f'  Scaling ratio:    {LORA_ALPHA/LORA_R}')
print(f'  Dropout:          {LORA_DROPOUT}')
print(f'  Target modules:   {LORA_TARGET_MODULES}')
print()
print(f'Training:')
print(f'  Learning rate:    {LEARNING_RATE}')
print(f'  Epochs:           {NUM_EPOCHS}')
print(f'  Per device batch: {BATCH_SIZE}')
print(f'  Grad accum steps: {GRAD_ACCUM}')
print(f'  Effective batch:  {EFFECTIVE_BATCH}')
print(f'  Max seq length:   {MAX_SEQ_LENGTH}')
print(f'  Max new tokens:   {MAX_NEW_TOKENS}')
print(f'  Random seed:      {SEED}')

=======================================================
EXPERIMENTAL CONFIGURATION
=======================================================
SLM model:          google/gemma-2b-it
Reference model:    Qwen/Qwen2.5-14B-Instruct

LoRA configuration:
  Rank (r):         16
  Alpha:            32
  Scaling ratio:    2.0
  Dropout:          0.05
  Target modules:   ['q_proj', 'k_proj', 'v_proj', 'o_proj']

Training:
  Learning rate:    0.0002
  Epochs:           3
  Per device batch: 4
  Grad accum steps: 4
  Effective batch:  16
  Max seq length:   512
  Max new tokens:   64
  Random seed:      42

In [ ]:
import os

for root, dirs, files in os.walk("/content/syllabusqa"):
    for f in files:
        print(os.path.join(root, f))

/content/syllabusqa/.gitignore
/content/syllabusqa/README.md
/content/syllabusqa/requirements.txt
/content/syllabusqa/syllabi/syllabi_meta_info.csv
/content/syllabusqa/syllabi/syllabi_redacted/pdf/vsyllabus 2022.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus_IntroGIS_Fall2022.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/syllabus_fall2022-revised2.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/num_analysis_redacted.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/syllabus-2.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/syllabus_606.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/101-f22-syll.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus_Grounding_S_2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus. Multivariable Calculus.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Biol582_2022_Syllabus.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus SPP 697 PM 2023 (clean).pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/MIE 302 Spring 2022 Syllabus-v1.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/advanced_system_software_design_redacted.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/BDES-Syllabus-2021-v1rsb.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/270 Syllabus Fall 2022 (1).pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Sch Mgmt 652 Syllabus - Fully OnLine.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus_209H_230301.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/PSYCH 397D syllabus Spring 2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/MIE 380 syllabus F22.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Most Recent P132 Syllabus - Spring 2022.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/web_syllabus_4670.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/ResEcon-213-Fall-2022.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/cs466_sp21_info_redacted.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus_ISE4100_Au22_v3_redacted.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Nutr_130H_Syllabus_2021Fall.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/1. Syllabus 2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus Chem111-Fa22.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/JOURNAL 310 (International Journalism) Syllabus - 2022 Spring.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/BIOCHEM 320 Syllabus SP23 2 Feb 2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/UMASS-Math3312023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus_Marine_Microbiome_2022_redacted.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/2023_Chem122_syllabus.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/CS4501-001_ Privacy in the Internet Age, Fall 2021_1.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/796 Syllabus.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/PH224_Syllabus_Spring23.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/stat-111-syl-spring 2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/syllabus-RESEC213-2023spring-yp.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/CS Syllabus for 568.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Spring 2022 SCH-MGMT 697DS Data Science for Business Syllabus.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus.Astron101.summer2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus_BIOLOGY497G_BIOLOGY697G_FA22.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Teaching Math in Elementary School 2 Proposed Syllabus.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/BCH8016 Solid State Analysis (SYL) 012219 - revised.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/151 syllabus fall 2022 Rounds.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus Bio 544 lecture S23.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/FS542_food chem2.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/ENG 204 syllabus_FA 2021.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/130 syllabus_2 S 2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/315 Lab Syllabus 22-01-11.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus_Spmgt461_DataAnalytics.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/GEOG468668syllabusGIS_2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/MKTG 497G Customer Insight Syllabus S2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/soc795E.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Acct 371 Syllabus - Spring.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/MGMNT 462_ Syllabus - Spring 2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/MUSIC-ED 500KU Syllabus S23.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Animlsci581 Syllabus-v4.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Legal 297BL Syllabus.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/FIN 408 Syllabus updated v2.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus-549.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/L0.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Honors 391AH - AA Media Pop Culture - Fall 2022 Syllabus.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/EME6651-SP2023_Syllabus.pdf
/content/syllabusqa/syllabi/syllabi_redacted/text/advanced_system_software_design_redacted.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/MIE 380 syllabus F22.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus Bio 544 lecture S23.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Teaching Math in Elementary School 2 Proposed Syllabus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/MIE 302 Spring 2022 Syllabus-v1.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/PSYCH 397D syllabus Spring 2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Biol582_2022_Syllabus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Most Recent P132 Syllabus - Spring 2022.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/FIN 408 Syllabus updated v2.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/JOURNAL 310 (International Journalism) Syllabus - 2022 Spring.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/151 syllabus fall 2022 Rounds.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/BIOCHEM 320 Syllabus SP23 2 Feb 2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Acct 371 Syllabus - Spring.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus_ISE4100_Au22_v3_redacted.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/MGMNT 462_ Syllabus - Spring 2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/stat-111-syl-spring 2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/BDES-Syllabus-2021-v1rsb.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/PH224_Syllabus_Spring23.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus Chem111-Fa22.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Honors 391AH - AA Media Pop Culture - Fall 2022 Syllabus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus_IntroGIS_Fall2022.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus_Marine_Microbiome_2022_redacted.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/syllabus-2.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/EME6651-SP2023_Syllabus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Sch Mgmt 652 Syllabus - Fully OnLine.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Spring 2022 SCH-MGMT 697DS Data Science for Business Syllabus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus_Grounding_S_2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus_209H_230301.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/L0.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus.Astron101.summer2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/315 Lab Syllabus 22-01-11.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/BCH8016 Solid State Analysis (SYL) 012219 - revised.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/UMASS-Math3312023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/130 syllabus_2 S 2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/MUSIC-ED 500KU Syllabus S23.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/270 Syllabus Fall 2022 (1).txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus-549.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/cs466_sp21_info_redacted.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/2023_Chem122_syllabus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus SPP 697 PM 2023 (clean).txt
/content/syllabusqa/syllabi/syllabi_redacted/text/CS4501-001_ Privacy in the Internet Age, Fall 2021_1.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/vsyllabus 2022.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/soc795E.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/syllabus_606.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Legal 297BL Syllabus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/1. Syllabus 2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/syllabus_fall2022-revised2.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/FS542_food chem2.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus_Spmgt461_DataAnalytics.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus_BIOLOGY497G_BIOLOGY697G_FA22.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus. Multivariable Calculus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/num_analysis_redacted.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/CS Syllabus for 568.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/GEOG468668syllabusGIS_2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/syllabus-RESEC213-2023spring-yp.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/web_syllabus_4670.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Nutr_130H_Syllabus_2021Fall.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/101-f22-syll.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/MKTG 497G Customer Insight Syllabus S2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/ENG 204 syllabus_FA 2021.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/796 Syllabus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/ResEcon-213-Fall-2022.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Animlsci581 Syllabus-v4.txt
/content/syllabusqa/syllabi/syllabi_redacted/word/PSYCH 397D syllabus Spring 2023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/151 syllabus fall 2022 Rounds.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/ENG 204 syllabus_FA 2021.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus Bio 544 lecture S23.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/soc795E.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/syllabus_fall2022-revised2.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/EME6651-SP2023_Syllabus.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/MKTG 497G Customer Insight Syllabus S2023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/101-f22-syll.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus_209H_230301.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/num_analysis_redacted.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/130 syllabus_2 S 2023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/BCH8016 Solid State Analysis (SYL) 012219 - revised.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/web_syllabus_4670.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/L0.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/PH224_Syllabus_Spring23.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Sch Mgmt 652 Syllabus - Fully OnLine.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus. Multivariable Calculus.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus_BIOLOGY497G_BIOLOGY697G_FA22.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/advanced_system_software_design_redacted.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/1. Syllabus 2023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Animlsci581 Syllabus-v4.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/CS Syllabus for 568.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus SPP 697 PM 2023 (clean).docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Legal 297BL Syllabus.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Nutr_130H_Syllabus_2021Fall.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/BDES-Syllabus-2021-v1rsb.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/vsyllabus 2022.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Biol582_2022_Syllabus.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Spring 2022 SCH-MGMT 697DS Data Science for Business Syllabus.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus_IntroGIS_Fall2022.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Most Recent P132 Syllabus - Spring 2022.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/MIE 302 Spring 2022 Syllabus-v1.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/MUSIC-ED 500KU Syllabus S23.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus.Astron101.summer2023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/CS4501-001_ Privacy in the Internet Age, Fall 2021_1.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/syllabus_606.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/270 Syllabus Fall 2022 (1).docx
/content/syllabusqa/syllabi/syllabi_redacted/word/ResEcon-213-Fall-2022.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Teaching Math in Elementary School 2 Proposed Syllabus.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus-549.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus Chem111-Fa22.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/FIN 408 Syllabus updated v2.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Honors 391AH - AA Media Pop Culture - Fall 2022 Syllabus.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/JOURNAL 310 (International Journalism) Syllabus - 2022 Spring.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/MGMNT 462_ Syllabus - Spring 2023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/315 Lab Syllabus 22-01-11.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/syllabus-RESEC213-2023spring-yp.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus_Spmgt461_DataAnalytics.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Acct 371 Syllabus - Spring.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/stat-111-syl-spring 2023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus_ISE4100_Au22_v3_redacted.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/796 Syllabus.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/GEOG468668syllabusGIS_2023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/2023_Chem122_syllabus.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/cs466_sp21_info_redacted.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/UMASS-Math3312023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/MIE 380 syllabus F22.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/BIOCHEM 320 Syllabus SP23 2 Feb 2023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus_Grounding_S_2023.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/FS542_food chem2.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/Syllabus_Marine_Microbiome_2022_redacted.docx
/content/syllabusqa/syllabi/syllabi_redacted/word/syllabus-2.docx
/content/syllabusqa/code/__init__.py
/content/syllabusqa/code/gpt4/configs.yaml
/content/syllabusqa/code/gpt4/run_gpt4.py
/content/syllabusqa/code/gpt4/clean_completion.py
/content/syllabusqa/code/gpt4/evaluate.py
/content/syllabusqa/code/zeroshot/search_baseline.py
/content/syllabusqa/code/zeroshot/evaluate.py
/content/syllabusqa/code/data_wrangling/create_split.py
/content/syllabusqa/code/data_wrangling/quality_control_v2.py
/content/syllabusqa/code/data_wrangling/create_dataset.py
/content/syllabusqa/code/finetune/batch_collator.py
/content/syllabusqa/code/finetune/configs.yaml
/content/syllabusqa/code/finetune/train.py
/content/syllabusqa/code/finetune/model.py
/content/syllabusqa/code/finetune/test.py
/content/syllabusqa/code/data_analysis/stats.py
/content/syllabusqa/code/data_analysis/compute_question_overlap.py
/content/syllabusqa/code/utils/utils.py
/content/syllabusqa/code/utils/data_utils.py
/content/syllabusqa/code/utils/load_data.py
/content/syllabusqa/code/metric/openai_api.py
/content/syllabusqa/code/metric/eval_results.py
/content/syllabusqa/code/retrievalauggen/get_retrieved_text.py
/content/syllabusqa/code/retrievalauggen/chunk_syllabi.py
/content/syllabusqa/.git/description
/content/syllabusqa/.git/config
/content/syllabusqa/.git/packed-refs
/content/syllabusqa/.git/HEAD
/content/syllabusqa/.git/index
/content/syllabusqa/.git/refs/remotes/origin/HEAD
/content/syllabusqa/.git/refs/heads/main
/content/syllabusqa/.git/objects/pack/pack-3617c5d30ba9e642575464139db40156cd490244.pack
/content/syllabusqa/.git/objects/pack/pack-3617c5d30ba9e642575464139db40156cd490244.rev
/content/syllabusqa/.git/objects/pack/pack-3617c5d30ba9e642575464139db40156cd490244.idx
/content/syllabusqa/.git/info/exclude
/content/syllabusqa/.git/logs/HEAD
/content/syllabusqa/.git/logs/refs/remotes/origin/HEAD
/content/syllabusqa/.git/logs/refs/heads/main
/content/syllabusqa/.git/hooks/pre-merge-commit.sample
/content/syllabusqa/.git/hooks/sendemail-validate.sample
/content/syllabusqa/.git/hooks/pre-commit.sample
/content/syllabusqa/.git/hooks/pre-applypatch.sample
/content/syllabusqa/.git/hooks/applypatch-msg.sample
/content/syllabusqa/.git/hooks/prepare-commit-msg.sample
/content/syllabusqa/.git/hooks/pre-receive.sample
/content/syllabusqa/.git/hooks/push-to-checkout.sample
/content/syllabusqa/.git/hooks/pre-push.sample
/content/syllabusqa/.git/hooks/pre-rebase.sample
/content/syllabusqa/.git/hooks/commit-msg.sample
/content/syllabusqa/.git/hooks/fsmonitor-watchman.sample
/content/syllabusqa/.git/hooks/post-update.sample
/content/syllabusqa/.git/hooks/update.sample
/content/syllabusqa/data/.gitkeep
/content/syllabusqa/data/dataset_split/train.csv
/content/syllabusqa/data/dataset_split/test.json
/content/syllabusqa/data/dataset_split/val.csv
/content/syllabusqa/data/dataset_split/val.json
/content/syllabusqa/data/dataset_split/test.csv
/content/syllabusqa/data/dataset_split/train.json

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 7: Load SyllabusQA from GitHub
# Clones official repository directly
# Required because Wheeza/syllabusQA HuggingFace path
# no longer works
# ═══════════════════════════════════════════════════════════

from pathlib import Path
import json

REPO_DIR = Path("/content/syllabusqa")

if not REPO_DIR.exists():
    print("Cloning SyllabusQA from GitHub...")
    !git clone -q https://github.com/umass-ml4ed/syllabusqa.git /content/syllabusqa
    print("Clone complete.")
else:
    print("SyllabusQA already cloned.")

print(f"\nRepository exists: {REPO_DIR.exists()}")

# Show what files are available
data_dir = REPO_DIR / "data"
if data_dir.exists():
    print("\nFiles in data directory:")
    for f in sorted(data_dir.iterdir()):
        size_kb = f.stat().st_size / 1024
        print(f"  {f.name}: {size_kb:.1f} KB")
else:
    print("\nNo data directory. Searching for JSON files...")
    for f in sorted(REPO_DIR.rglob("*.json")):
        print(f"  {f}")

SyllabusQA already cloned.

Repository exists: True

Files in data directory:
  .gitkeep: 0.0 KB
  dataset_split: 4.0 KB

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 7B: Load SyllabusQA from dataset_split files
# Files confirmed: train.csv, val.csv, test.csv
# Also has JSON versions: train.json, val.json, test.json
# Using JSON for richer data structure
# ═══════════════════════════════════════════════════════════

from datasets import DatasetDict, Dataset
from collections import Counter
from pathlib import Path
import json

split_dir = Path("/content/syllabusqa/data/dataset_split")

print("Loading splits from JSON files...")

splits = {}

# Correct file names confirmed from your output
file_map = {
    "train":      "train.json",
    "validation": "val.json",
    "test":       "test.json"
}

for split_name, filename in file_map.items():
    filepath = split_dir / filename
    if filepath.exists():
        with open(filepath) as f:
            data = json.load(f)

        # Handle list or dict format
        if isinstance(data, list):
            splits[split_name] = Dataset.from_list(data)
        elif isinstance(data, dict):
            # Some JSON datasets wrap examples in a key
            first_val = list(data.values())[0]
            if isinstance(first_val, list):
                splits[split_name] = Dataset.from_list(first_val)
            else:
                splits[split_name] = Dataset.from_list([data])

        print(f"  {split_name}: {len(splits[split_name]):,} examples")
    else:
        print(f"  Not found: {filename}")

dataset = DatasetDict(splits)

print()
print("=" * 55)
print("SYLLABUSQA LOADED SUCCESSFULLY")
print("=" * 55)
print(f"Train:       {len(dataset['train']):,} examples")
print(f"Validation:  {len(dataset['validation']):,} examples")
print(f"Test:        {len(dataset['test']):,} examples")
print(f"Total:       {sum(len(dataset[s]) for s in dataset):,} examples")

print("\nColumn names in train split:")
print(dataset['train'].column_names)

print("\nSample training example:")
sample = dict(dataset['train'][0])
for key, val in sample.items():
    print(f"\n  {key}:")
    print(f"  {str(val)[:200]}")

if 'question_type' in dataset['test'].column_names:
    print("\nQuestion type distribution in test set:")
    counts = Counter(dataset['test']['question_type'])
    for qtype, count in sorted(counts.items()):
        pct = 100 * count / len(dataset['test'])
        print(f"  {qtype:25s}: {count:4d} ({pct:.1f}%)")

Loading splits from JSON files...
  train: 3,018 examples
  validation: 957 examples
  test: 1,103 examples

=======================================================
SYLLABUSQA LOADED SUCCESSFULLY
=======================================================
Train:       3,018 examples
Validation:  957 examples
Test:        1,103 examples
Total:       5,078 examples

Column names in train split:
['id', 'syllabus_name', 'question_type', 'question', 'answer', 'answer_span_1', 'answer_span_2', 'answer_span_3', 'answer_span_4', 'answer_span_5', 'reasoning_step_1', 'reasoning_step_2', 'reasoning_step_3', 'reasoning_step_4', 'reasoning_step_5']

Sample training example:

  id:
  6PwCf8udvbESgSZR

  syllabus_name:
  130 syllabus_2 S 2023

  question_type:
  single reasoning

  question:
  Is it permissible to provide incorrect information when completing a homework assignment?


  answer:
  No, it is essential that you complete this Homework assignment as accurately as possible because a lot of discussion activities will rely on your completed Food Intake Analysis.


  answer_span_1:
  None

  answer_span_2:
  None

  answer_span_3:
  None

  answer_span_4:
  None

  answer_span_5:
  None

  reasoning_step_1:
  It is essential that you complete this Homework assignment as accurately as possible because a number of discussion activities will make use of your completed Food Intake Analysis.


  reasoning_step_2:
  None

  reasoning_step_3:
  None

  reasoning_step_4:
  None

  reasoning_step_5:
  None

Question type distribution in test set:
  multi factual            :  158 (14.3%)
  multi reasoning          :  158 (14.3%)
  no answer                :  155 (14.1%)
  single factual           :  158 (14.3%)
  single reasoning         :  158 (14.3%)
  summarization            :  158 (14.3%)
  yes/no                   :  158 (14.3%)

In [ ]:
#7C-Verify missing context

print("=== DATASET FIELD CHECK ===")

sample = dataset["train"][0]

print("Available fields:")
print(dataset["train"].column_names)

print("\nSyllabus name:")
print(sample["syllabus_name"])

print("\nQuestion:")
print(sample["question"])

print("\nDoes 'context' exist?")
print("context" in sample)

print("\nDoes 'syllabus' exist?")
print("syllabus" in sample)

=== DATASET FIELD CHECK ===
Available fields:
['id', 'syllabus_name', 'question_type', 'question', 'answer', 'answer_span_1', 'answer_span_2', 'answer_span_3', 'answer_span_4', 'answer_span_5', 'reasoning_step_1', 'reasoning_step_2', 'reasoning_step_3', 'reasoning_step_4', 'reasoning_step_5']

Syllabus name:
130 syllabus_2 S 2023

Question:
Is it permissible to provide incorrect information when completing a homework assignment?


Does 'context' exist?
False

Does 'syllabus' exist?
False

In [ ]:
#NEW Cell 7D — Search for source syllabi

from pathlib import Path

REPO_DIR = Path("/content/syllabusqa")

print("=== SEARCHING REPOSITORY FOR SYLLABUS FILES ===")

pdf_files = list(REPO_DIR.rglob("*.pdf"))
txt_files = list(REPO_DIR.rglob("*.txt"))

print(f"PDF files found: {len(pdf_files)}")
print(f"TXT files found: {len(txt_files)}")

print("\nFirst PDF files:")
for f in pdf_files[:10]:
    print(f)

print("\nFirst TXT files:")
for f in txt_files[:10]:
    print(f)

=== SEARCHING REPOSITORY FOR SYLLABUS FILES ===
PDF files found: 63
TXT files found: 64

First PDF files:
/content/syllabusqa/syllabi/syllabi_redacted/pdf/vsyllabus 2022.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus_IntroGIS_Fall2022.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/syllabus_fall2022-revised2.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/num_analysis_redacted.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/syllabus-2.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/syllabus_606.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/101-f22-syll.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus_Grounding_S_2023.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Syllabus. Multivariable Calculus.pdf
/content/syllabusqa/syllabi/syllabi_redacted/pdf/Biol582_2022_Syllabus.pdf

First TXT files:
/content/syllabusqa/requirements.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/advanced_system_software_design_redacted.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/MIE 380 syllabus F22.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Syllabus Bio 544 lecture S23.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Teaching Math in Elementary School 2 Proposed Syllabus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/MIE 302 Spring 2022 Syllabus-v1.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/PSYCH 397D syllabus Spring 2023.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Biol582_2022_Syllabus.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/Most Recent P132 Syllabus - Spring 2022.txt
/content/syllabusqa/syllabi/syllabi_redacted/text/FIN 408 Syllabus updated v2.txt

In [ ]:
# ============================================================
# CELL 7E: Inspect dataset syllabus names vs syllabus text files
# Goal: determine how syllabus_name maps to .txt filenames
# ============================================================

from pathlib import Path

TEXT_DIR = Path(
    "/content/syllabusqa/syllabi/syllabi_redacted/text"
)

# 1. Unique syllabus names used by the dataset
dataset_syllabus_names = sorted(
    set(
        ex["syllabus_name"]
        for split in ["train", "validation", "test"]
        for ex in dataset[split]
    )
)

# 2. Actual syllabus text files
syllabus_txt_files = sorted(
    [
        f for f in TEXT_DIR.glob("*.txt")
        if f.name.lower() != "requirements.txt"
    ]
)

print("=== DATASET SYLLABUS NAMES ===")
print("Unique syllabus names:", len(dataset_syllabus_names))

for i, name in enumerate(dataset_syllabus_names[:15]):
    print(i, repr(name))

print("\n=== SYLLABUS TEXT FILES ===")
print("Text syllabus files:", len(syllabus_txt_files))

for i, f in enumerate(syllabus_txt_files[:15]):
    print(i, repr(f.stem))

=== DATASET SYLLABUS NAMES ===
Unique syllabus names: 63
0 '1. Syllabus 2023'
1 '101-f22-syll'
2 '130 syllabus_2 S 2023'
3 '151 syllabus fall 2022 Rounds'
4 '2023_Chem122_syllabus'
5 '270 Syllabus Fall 2022 (1)'
6 '315 Lab Syllabus 22-01-11'
7 '796 Syllabus'
8 'Acct 371 Syllabus - Spring'
9 'Animlsci581 Syllabus-v4'
10 'BCH8016 Solid State Analysis (SYL) 012219 - revised'
11 'BDES-Syllabus-2021-v1rsb'
12 'BIOCHEM 320 Syllabus SP23 2 Feb 2023'
13 'Biol582_2022_Syllabus'
14 'CS Syllabus for 568'

=== SYLLABUS TEXT FILES ===
Text syllabus files: 63
0 '1. Syllabus 2023'
1 '101-f22-syll'
2 '130 syllabus_2 S 2023'
3 '151 syllabus fall 2022 Rounds'
4 '2023_Chem122_syllabus'
5 '270 Syllabus Fall 2022 (1)'
6 '315 Lab Syllabus 22-01-11'
7 '796 Syllabus'
8 'Acct 371 Syllabus - Spring'
9 'Animlsci581 Syllabus-v4'
10 'BCH8016 Solid State Analysis (SYL) 012219 - revised'
11 'BDES-Syllabus-2021-v1rsb'
12 'BIOCHEM 320 Syllabus SP23 2 Feb 2023'
13 'Biol582_2022_Syllabus'
14 'CS Syllabus for 568'

In [ ]:
# ============================================================
# CELL 7F: Check direct filename matches
# ============================================================

file_stems = {f.stem for f in syllabus_txt_files}

exact_matches = [
    name for name in dataset_syllabus_names
    if name in file_stems
]

missing_matches = [
    name for name in dataset_syllabus_names
    if name not in file_stems
]

print("=== EXACT MATCH CHECK ===")
print("Dataset syllabus names:", len(dataset_syllabus_names))
print("Exact filename matches:", len(exact_matches))
print("Not directly matched:", len(missing_matches))

print("\nFirst exact matches:")
for name in exact_matches[:10]:
    print("MATCH:", repr(name))

print("\nFirst unmatched names:")
for name in missing_matches[:10]:
    print("NO MATCH:", repr(name))

=== EXACT MATCH CHECK ===
Dataset syllabus names: 63
Exact filename matches: 63
Not directly matched: 0

First exact matches:
MATCH: '1. Syllabus 2023'
MATCH: '101-f22-syll'
MATCH: '130 syllabus_2 S 2023'
MATCH: '151 syllabus fall 2022 Rounds'
MATCH: '2023_Chem122_syllabus'
MATCH: '270 Syllabus Fall 2022 (1)'
MATCH: '315 Lab Syllabus 22-01-11'
MATCH: '796 Syllabus'
MATCH: 'Acct 371 Syllabus - Spring'
MATCH: 'Animlsci581 Syllabus-v4'

First unmatched names:

In [ ]:
# ============================================================
# CELL 7G: Build syllabus_name -> syllabus text mapping
# ============================================================

from pathlib import Path

TEXT_DIR = Path("/content/syllabusqa/syllabi/syllabi_redacted/text")

syllabus_map = {}

for fpath in TEXT_DIR.glob("*.txt"):
    # Ignore requirements.txt
    if fpath.name.lower() == "requirements.txt":
        continue

    syllabus_name = fpath.stem

    with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
        syllabus_text = f.read().strip()

    syllabus_map[syllabus_name] = syllabus_text

print("=== SYLLABUS MAP CREATED ===")
print("Total syllabi loaded:", len(syllabus_map))

print("\nFirst 5 syllabus names:")
for name in list(syllabus_map.keys())[:5]:
    print(repr(name))

=== SYLLABUS MAP CREATED ===
Total syllabi loaded: 63

First 5 syllabus names:
'advanced_system_software_design_redacted'
'MIE 380 syllabus F22'
'Syllabus Bio 544 lecture S23'
'Teaching Math in Elementary School 2 Proposed Syllabus'
'MIE 302 Spring 2022 Syllabus-v1'

In [ ]:
# ============================================================
# CELL 7H: Verify QA example -> correct syllabus text
# ============================================================

sample = dataset["train"][0]

sample_name = sample["syllabus_name"]
sample_question = sample["question"]
sample_answer = sample["answer"]

print("=== QA TO SYLLABUS VERIFICATION ===")

print("\nSyllabus name:")
print(sample_name)

print("\nQuestion:")
print(sample_question)

print("\nReference answer:")
print(sample_answer)

print("\nSyllabus found in map:")
print(sample_name in syllabus_map)

if sample_name in syllabus_map:
    context = syllabus_map[sample_name]

    print("\nSyllabus length in characters:")
    print(len(context))

    print("\nFirst 1000 characters of syllabus:")
    print(context[:1000])

else:
    print("\nERROR: matching syllabus not found.")

=== QA TO SYLLABUS VERIFICATION ===

Syllabus name:
130 syllabus_2 S 2023

Question:
Is it permissible to provide incorrect information when completing a homework assignment?


Reference answer:
No, it is essential that you complete this Homework assignment as accurately as possible because a lot of discussion activities will rely on your completed Food Intake Analysis.


Syllabus found in map:
True

Syllabus length in characters:
27114

First 1000 characters of syllabus:
NUTRITION 130 (GEN ED BS 4 credits) NUTRITION FOR A HEALTHY LIFESTYLE SYLLABUS Spring 2023MWF 10:10-11
Small changes may be made to this syllabus and before and during the semester. If that happens students will
be notified by email.
Instructor <PROF_FULL_NAME> MS, RD, LDN
206A Chenoweth Student drop-in hours Thursday 11-12
Book: Please note that information on the book for this course is available on the Moodle page. The book is recommended but not required and is available as an etext.
iClicker: Because we will be using iClicker for 10% of the grade, I would recommend that you order this soon. I only useiClicker classic because I have found that there are glitches with the iClicker app that may result in a student not gettingcredit for all the sessions they responded to.
Why I teach this Course
I teach this course because I love food and eating.  I was hooked by the subject of Nutrition the first time I realized that all the cells in my body were completely dependent on what

In [ ]:
# ============================================================
# CELL 7I: Check syllabus mapping coverage
# ============================================================

print("=== SYLLABUS MAPPING COVERAGE ===")

for split in ["train", "validation", "test"]:

    total = len(dataset[split])

    matched = sum(
        1
        for ex in dataset[split]
        if ex["syllabus_name"] in syllabus_map
    )

    missing = total - matched

    print(
        f"{split}: {matched}/{total} matched "
        f"({missing} missing)"
    )

=== SYLLABUS MAPPING COVERAGE ===
train: 3018/3018 matched (0 missing)
validation: 957/957 matched (0 missing)
test: 1103/1103 matched (0 missing)

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "google/gemma-2b-it"
)

print("Tokenizer loaded successfully.")

Tokenizer loaded successfully.

In [ ]:
# ============================================================
# CELL 7J: Check syllabus token lengths
# ============================================================

sample_lengths = []

for name, text in list(syllabus_map.items())[:10]:
    tokens = tokenizer(
        text,
        add_special_tokens=False
    )["input_ids"]

    sample_lengths.append(len(tokens))

    print(
        f"{name[:50]} -> "
        f"{len(tokens)} tokens"
    )

print("\nAverage token length of these samples:")
print(sum(sample_lengths) / len(sample_lengths))

advanced_system_software_design_redacted -> 1384 tokens
MIE 380 syllabus F22 -> 2551 tokens
Syllabus Bio 544 lecture S23 -> 1690 tokens
Teaching Math in Elementary School 2 Proposed Syll -> 6039 tokens
MIE 302 Spring 2022 Syllabus-v1 -> 3087 tokens
PSYCH 397D syllabus Spring 2023 -> 6258 tokens
Biol582_2022_Syllabus -> 4241 tokens
Most Recent P132 Syllabus - Spring 2022 -> 10692 tokens
FIN 408 Syllabus updated v2 -> 1866 tokens
JOURNAL 310 (International Journalism) Syllabus -  -> 6076 tokens

Average token length of these samples:
4388.4

In [ ]:
!pip -q install rank_bm25

In [ ]:
# ============================================================
# CELL 7K: Build simple BM25 context retrieval
# ============================================================

from rank_bm25 import BM25Okapi
import re

CHUNK_WORDS = 90
CHUNK_OVERLAP = 30
TOP_K = 2

def split_syllabus_into_chunks(text, chunk_words=CHUNK_WORDS, overlap=CHUNK_OVERLAP):
    words = text.split()
    chunks = []
    step = chunk_words - overlap

    for start in range(0, len(words), step):
        chunk = " ".join(words[start:start + chunk_words]).strip()
        if chunk:
            chunks.append(chunk)

    return chunks

def retrieve_relevant_context(syllabus_name, question, top_k=TOP_K):
    syllabus_text = syllabus_map.get(syllabus_name, "")

    if not syllabus_text:
        return ""

    chunks = split_syllabus_into_chunks(syllabus_text)

    tokenized_chunks = [
        re.findall(r"\w+", chunk.lower())
        for chunk in chunks
    ]

    bm25 = BM25Okapi(tokenized_chunks)

    query_tokens = re.findall(r"\w+", question.lower())
    scores = bm25.get_scores(query_tokens)

    ranked_indices = sorted(
        range(len(scores)),
        key=lambda i: scores[i],
        reverse=True
    )[:top_k]

    selected_chunks = [chunks[i] for i in ranked_indices]

    return "\n".join(selected_chunks)

print("BM25 context retrieval ready.")

BM25 context retrieval ready.

In [ ]:
# ============================================================
# CELL 7L: Test retrieved syllabus context
# ============================================================

sample = dataset["train"][0]

sample_name = sample["syllabus_name"]
sample_question = sample["question"]
sample_answer = sample["answer"]

retrieved_context = retrieve_relevant_context(
    sample_name,
    sample_question
)

print("=== RETRIEVAL TEST ===")

print("\nSyllabus name:")
print(sample_name)

print("\nQuestion:")
print(sample_question)

print("\nReference answer:")
print(sample_answer)

print("\nRetrieved syllabus context:")
print(retrieved_context)

print("\nRetrieved context word count:")
print(len(retrieved_context.split()))

=== RETRIEVAL TEST ===

Syllabus name:
130 syllabus_2 S 2023

Question:
Is it permissible to provide incorrect information when completing a homework assignment?


Reference answer:
No, it is essential that you complete this Homework assignment as accurately as possible because a lot of discussion activities will rely on your completed Food Intake Analysis.


Retrieved syllabus context:
You will do an analysis of your food intake (as recorded in your Food/Eating Log) using Chronometer (a free website)When you bring your completed Food Intake Analysis to discussion, your TA will guide you so that you can correct any errors. It is important that you are as accurate as possible when completing this Homework assignment, because there are a number of discussion activities that use your completed Food Intake Analysis. Diet Modification Project (6%) You will use Chronometer to adjust the food intake of a very imperfect intake to
CRAPP test to websites with a nutrition focus. Newspaper Article (5%) In this assignment you will compare a news article with an original research article and answer questions. Please note LATE POLICY: We allow for late submissions, however, there is a 10% deduction for every day it is late. We will accept homework up to 5 days past the due date. Discussion participation (10%) Many students fail this class because they do not go to discussion. The total points for discussion attendance, and homework (which is a part of the

Retrieved context word count:
180

In [ ]:
# ============================================================
# CELL 7M: Check corrected prompt token length
# ============================================================

sample_prompt = (
    f"Syllabus context:\n{retrieved_context}\n\n"
    f"Question:\n{sample_question}\n\n"
    f"Answer: {sample_answer}"
)

prompt_tokens = tokenizer(
    sample_prompt,
    add_special_tokens=True
)["input_ids"]

print("Corrected prompt token count:", len(prompt_tokens))
print("\nPrompt preview:\n")
print(sample_prompt[:2000])

Corrected prompt token count: 272

Prompt preview:

Syllabus context:
You will do an analysis of your food intake (as recorded in your Food/Eating Log) using Chronometer (a free website)When you bring your completed Food Intake Analysis to discussion, your TA will guide you so that you can correct any errors. It is important that you are as accurate as possible when completing this Homework assignment, because there are a number of discussion activities that use your completed Food Intake Analysis. Diet Modification Project (6%) You will use Chronometer to adjust the food intake of a very imperfect intake to
CRAPP test to websites with a nutrition focus. Newspaper Article (5%) In this assignment you will compare a news article with an original research article and answer questions. Please note LATE POLICY: We allow for late submissions, however, there is a 10% deduction for every day it is late. We will accept homework up to 5 days past the due date. Discussion participation (10%) Many students fail this class because they do not go to discussion. The total points for discussion attendance, and homework (which is a part of the

Question:
Is it permissible to provide incorrect information when completing a homework assignment?


Answer: No, it is essential that you complete this Homework assignment as accurately as possible because a lot of discussion activities will rely on your completed Food Intake Analysis.

In [ ]:
# ============================================================
# CELL 7N: Inspect 10 context-aware examples
# ============================================================

for i in range(10):
    ex = dataset["train"][i]

    context = retrieve_relevant_context(
        ex["syllabus_name"],
        ex["question"]
    )

    prompt = (
        f"Syllabus context:\n{context}\n\n"
        f"Question:\n{ex['question']}\n\n"
        f"Answer: {ex['answer']}"
    )

    token_count = len(
        tokenizer(
            prompt,
            add_special_tokens=True
        )["input_ids"]
    )

    print("=" * 80)
    print("Example:", i + 1)
    print("Syllabus:", ex["syllabus_name"])
    print("Question:", ex["question"])
    print("Token count:", token_count)
    print("\nContext:")
    print(context[:700])
    print()

================================================================================
Example: 1
Syllabus: 130 syllabus_2 S 2023
Question: Is it permissible to provide incorrect information when completing a homework assignment?

Token count: 272

Context:
You will do an analysis of your food intake (as recorded in your Food/Eating Log) using Chronometer (a free website)When you bring your completed Food Intake Analysis to discussion, your TA will guide you so that you can correct any errors. It is important that you are as accurate as possible when completing this Homework assignment, because there are a number of discussion activities that use your completed Food Intake Analysis. Diet Modification Project (6%) You will use Chronometer to adjust the food intake of a very imperfect intake to
CRAPP test to websites with a nutrition focus. Newspaper Article (5%) In this assignment you will compare a news article with an original research article

================================================================================
Example: 2
Syllabus: FIN 408 Syllabus updated v2
Question: How much does class participation count for my final grade?
Token count: 332

Context:
will evaluate other members contributions. There will be one individual exam during the semester. I expect you to show up in all classes. Any need for absences should be pre-requested by e.mail to the instructor. For the class to be a success, I need your active participation. You are strongly encouraged to ask questions as we proceed through the material. Your class participation score will be based on my evaluation of your level of participation in-class activities and discussions. When final grades are determined, those students who made substantial contributions
Your class participation score will be based on my evaluation of your level of participation in-class activities and discussion

================================================================================
Example: 3
Syllabus: 1. Syllabus 2023
Question: What is the Congressional Budget Office website?
Token count: 319

Context:
that prepare students for work involving the federal government. Course Materials All readings will be available online or provided via e-mail and Moodle. Useful Government Websites There are many worthwhile government and non-profit organization websites that contain useful information on federal budgeting. These include: Office of Management and Budget (OMB) http://www.whitehouse.gov/omb/ Congressional Budget Office http://www.cbo.gov/ Congressional Legislation Information https://www.congress.gov/ Past President Budget Proposals http://www.gpo.gov/fdsys/browse/collectionGPO.action?collectionCode=BUDGET Online centralized performance reporting portal required by the Government Performance

================================================================================
Example: 4
Syllabus: 2023_Chem122_syllabus
Question: What are the types of homework in this class?
Token count: 265

Context:
unreported, grades be changed after the fact. Section 15: OWL electronic Homework system Types of homework: There are two types of homework in this class. (A)Problem sets are assigned for each chapter. Those include questions that will help you apply the concepts to problem, and are great practice for examinations. Youll do much of these during scheduled class time. Working with others is highly encouraged! (B) On-Line Web-based Learning (OWL) are assigned for each chapter. These are challenging and require connecting the dots and critical thinking, but they tend to
using any means, including social medial like GroupMe, constitutes academic dishonesty. Knowing about such sharing and not repo

================================================================================
Example: 5
Syllabus: Acct 371 Syllabus - Spring
Question: What percentage of the grade do the exams, pre-class quizzes, and quizzes make up?
Token count: 366

Context:
following chart: Weighting % Grade Cutoffs Exam 1 15% A 94-100% Exam 2 15% A-90-93% Exam 3 15% B+ 86-89% Tax Return Problem 15% B 82-85% Pre-Class Quiz 10% B-79-81% Homework 10% C+ 75-78% Quizzes 10% C 72-74% In-Class Assignments 10% C-69-71% D+ 66-68% Total 100% D 60-65% F Below 60% Exams: The exams will be outside of class time to reduce time stress. I will describe the layout of the exams beforehand. The exams will be open book. If you miss an exam I will give a make-up exam
homework will consist of completing tax forms associated with the material covered in class. I will allow you to miss one homework assignment without deducting points. While homework is graded in CNOW, your final grad

================================================================================
Example: 6
Syllabus: syllabus_fall2022-revised2
Question: What kind of milestones will the students acquire after completing this course in Statistical modeling for health data science?
Token count: 670

Context:
alternatives to commonly used statistical methodswhenassumptionsare violated. Integrate analysis strategies in biostatistics with principles and issues in epidemiology. literature Developwrittenandoralpresentationsbasedonstatisticalanalysesfor both public healthprofessionals and educated lay audiences. Applystatisticalmethodstosolveproblemsinthehealthsciencesandcarryouttheoreticalresearchinstatistical methodology. Academic Integrity: TheUMass-AmherstAcademic HonestystatementfromtheAcademicRegulations2006-2007, pp. 7-8states: Intellectual honesty requires that students demonstrate their own learning duringexaminations and other academic exercises,and thatother sources ofinformation or knowled

================================================================================
Example: 7
Syllabus: Syllabus.Astron101.summer2023
Question: Am I able to get tutoring online?
Token count: 324

Context:
use. The book is also available as a low-priced ebook that you can read on your phones (ISBN 9781264150243). The textbook is also on reserve at the library. https://www.amazon.com/s?k=pathways+to+astronomy&ref=nb_sb_noss_1 https://www.mheducation.com/highered/product/pathways-astronomy-schneider/M9781260258066.html All units (chapters) should be read before listening to the lecture. Reading the units will help you understand better the concepts in the lecture that I am emphasizing. Online Tutoring There is free online tutoring. See link on left side of Blackboard. Accommodations Any accessibility or accommodation issues should be brought up with the instructor at the beginning of the
There i

================================================================================
Example: 8
Syllabus: 315 Lab Syllabus 22-01-11
Question: What will happen if I don't complete the Pre-Lab preparation before class?
Token count: 313

Context:
The Group-Lab notebook is based on what you do during the lab and is due before you leave the lab each day. Choose one of the group members Pre-lab notebooks and use it during lab. At the end of lab submit the revised document in Gradescope for the group. 1. (25%) Update the document a. Correct answers to pre-lab questions, the chemicals, the materials, and safety reflect the in class activities. b. Indicate changes to the procedure by using the strike-through text tool and then writing what you did in
when an assignment is due, don't wait until the day before to start working on it. 4. Plan ahead! To be successful, keep up with all the materials and assignments, monitor and participate in d

================================================================================
Example: 9
Syllabus: 796 Syllabus
Question: How many credits does this course award?
Token count: 284

Context:
EdPsych 796 Spring 2023 Educational Psychology Introduction to Learning Sciences II Course Info Course Overview Expectations Instructor: <PROF_FIRST_NAME> <PROF_LAST_NAME>, Ed Sciences 1086,: <PROF_EMAIL> (office hours by appointment) Credits: 3 Canvas: <LINK_CANVAS> Instructional mode: Face-to-face Classroom: Ed Sci 304 This is the second of a two-semester course sequence that establishes the intellectual foundations for research in the learning sciences. In 795, we got to know major theoretical perspectives that are foundational for the learning sciences. In 796, we will look at how these theoretical perspectives have shaped interventions designed to help
the interventions we will discuss

================================================================================
Example: 10
Syllabus: Syllabus Bio 544 lecture S23
Question: What are the administrative details for exams and quizzes?
Token count: 415

Context:
interpret their findings) Exams: We will have three exams: Exam 1 -Monday, March 27 Exam 2 -Monday, April 24 Exam 3 (not cumulative) -During the final exam period, date TBA. (Youll also have lab quizzes and exams; <TA_FIRST_NAME> will give the details on these in your lab section). Exams will be timed, but will be available during an extended time window on exam day. Most exam questions will be open format "thought questions" that require you to integrate the concepts and information that you have acquired and to explain your
point. For peer-reviewed research articles, write short answers to the following questions: 1) What question were the researchers trying to answer? 2) What, exactly, di

In [ ]:
# ============================================================
# CELL 8: Corrected prompt formatting with syllabus context
# ============================================================

def get_answer(example):
    answer = example.get("answer", "")

    if isinstance(answer, dict):
        texts = answer.get("text", [])
        return texts[0] if texts else ""

    if isinstance(answer, list):
        return answer[0] if answer else ""

    return str(answer) if answer is not None else ""

def format_for_training(example):
    context = retrieve_relevant_context(
        example["syllabus_name"],
        example["question"]
    )

    question = example["question"]
    answer = get_answer(example)

    text = (
        f"Syllabus context:\n{context}\n\n"
        f"Question:\n{question}\n\n"
        f"Answer: {answer}"
    )

    return {"text": text}

def format_for_inference(example):
    context = retrieve_relevant_context(
        example["syllabus_name"],
        example["question"]
    )

    question = example["question"]

    prompt = (
        f"Syllabus context:\n{context}\n\n"
        f"Question:\n{question}\n\n"
        f"Answer:"
    )

    return {"prompt": prompt}

train_data = dataset["train"].map(format_for_training)
val_data = dataset["validation"].map(format_for_training)
test_data = dataset["test"].map(format_for_inference)

print("Corrected datasets created.")
print("Train:", len(train_data))
print("Validation:", len(val_data))
print("Test:", len(test_data))

Map:   0%|          | 0/3018 [00:00<?, ? examples/s]

Map:   0%|          | 0/957 [00:00<?, ? examples/s]

Map:   0%|          | 0/1103 [00:00<?, ? examples/s]

Corrected datasets created.
Train: 3018
Validation: 957
Test: 1103

In [ ]:
print(train_data[0]["text"][:1000])
print(test_data[0]["prompt"][:1000])

Syllabus context:
You will do an analysis of your food intake (as recorded in your Food/Eating Log) using Chronometer (a free website)When you bring your completed Food Intake Analysis to discussion, your TA will guide you so that you can correct any errors. It is important that you are as accurate as possible when completing this Homework assignment, because there are a number of discussion activities that use your completed Food Intake Analysis. Diet Modification Project (6%) You will use Chronometer to adjust the food intake of a very imperfect intake to
CRAPP test to websites with a nutrition focus. Newspaper Article (5%) In this assignment you will compare a news article with an original research article and answer questions. Please note LATE POLICY: We allow for late submissions, however, there is a 10% deduction for every day it is late. We will accept homework up to 5 days past the due date. Discussion participation (10%) Many students fail this class because they do not go to
Syllabus context:
Extra Credit: Four extra credit opportunities will be available during the semester. Three of these are exam reflections and the fourth is the end-of-course survey. Each one has a maximum value of 0.3 percentage points towards your final grade. Additional details will be provided as each assignment becomes available. Final Grading Scale: Final grades are rounded to the tenth and then assigned according to this scale. A 93.00 100.00% B-80.00 82.99% D+ 67.00 69.99% A-90.00 92.99% C+ 77.00 79.99% D 60.00 66.99% B+ 87.00 89.99% C 73.00 76.99% F <59.99
miss some assignments and classes are built into the course and should cover most circumstances, but if you have an unexpected situation or assignment extensions are part of your accommodations, contact me as soon as possible to discuss an extension. Note: Because of the course flexibility, extension requests should be infrequent. Student Learning Accommodations: As a member of the university, I am committed to providing an

In [ ]:
!pip install -q --upgrade evaluate datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 48.7 MB/s eta 0:00:00

In [ ]:
# ============================================================
# HELPER: get_answer()
# ============================================================

def get_answer(example):
    answer = example.get("answer", "")

    if isinstance(answer, str):
        return answer.strip()

    return str(answer).strip()

print("get_answer() ready.")

get_answer() ready.

In [10]:
# ============================================================
# CELL 9: Prepare references and local SQuAD EM/F1 metric
# No dependency on evaluate.load("squad")
# ============================================================

import re
import string
from collections import Counter

print("Loading local SQuAD-style evaluation metric...")


# ------------------------------------------------------------
# Standard SQuAD answer normalization
# ------------------------------------------------------------
def normalize_answer(s):
    """Lower text and remove punctuation, articles and extra whitespace."""

    def remove_articles(text):
        return re.sub(r"\b(a|an|the)\b", " ", text)

    def white_space_fix(text):
        return " ".join(text.split())

    def remove_punc(text):
        exclude = set(string.punctuation)
        return "".join(ch for ch in text if ch not in exclude)

    def lower(text):
        return text.lower()

    return white_space_fix(
        remove_articles(
            remove_punc(
                lower(str(s))
            )
        )
    )


# ------------------------------------------------------------
# Exact Match
# ------------------------------------------------------------
def exact_match_score(prediction, ground_truth):
    return float(
        normalize_answer(prediction) ==
        normalize_answer(ground_truth)
    )


# ------------------------------------------------------------
# Token-level F1
# ------------------------------------------------------------
def f1_score(prediction, ground_truth):

    prediction_tokens = normalize_answer(prediction).split()
    ground_truth_tokens = normalize_answer(ground_truth).split()

    # Handle empty answers
    if len(prediction_tokens) == 0 or len(ground_truth_tokens) == 0:
        return float(prediction_tokens == ground_truth_tokens)

    common = Counter(prediction_tokens) & Counter(ground_truth_tokens)
    num_same = sum(common.values())

    if num_same == 0:
        return 0.0

    precision = num_same / len(prediction_tokens)
    recall = num_same / len(ground_truth_tokens)

    return 2 * precision * recall / (precision + recall)


# ------------------------------------------------------------
# Compatible replacement for squad_metric.compute(...)
# ------------------------------------------------------------
class LocalSquadMetric:

    def compute(self, predictions, references):

        exact_scores = []
        f1_scores = []

        reference_dict = {
            str(ref["id"]): ref["answers"]["text"]
            for ref in references
        }

        for pred in predictions:

            pred_id = str(pred["id"])
            prediction_text = pred["prediction_text"]

            ground_truths = reference_dict.get(pred_id, [""])

            if not ground_truths:
                ground_truths = [""]

            # Standard SQuAD evaluation:
            # use best score if multiple reference answers exist
            exact = max(
                exact_match_score(prediction_text, gt)
                for gt in ground_truths
            )

            f1 = max(
                f1_score(prediction_text, gt)
                for gt in ground_truths
            )

            exact_scores.append(exact)
            f1_scores.append(f1)

        return {
            "exact_match": 100.0 * sum(exact_scores) / len(exact_scores),
            "f1": 100.0 * sum(f1_scores) / len(f1_scores)
        }


squad_metric = LocalSquadMetric()

print("Local SQuAD-style metric loaded.")
print("Measures: Exact Match and token-level F1")
print()


# ------------------------------------------------------------
# Build reference answers from original test split
# ------------------------------------------------------------
print("Building reference answers from test split...")

references = []

for i, example in enumerate(dataset["test"]):

    answer_text = get_answer(example)

    references.append({
        "id": str(i),
        "answers": {
            "text": [answer_text],
            "answer_start": [0]
        }
    })


print(f"Reference answers prepared: {len(references):,}")

print()
print("Sample references:")

for i in range(3):
    print(
        f'  [{i}] answer="{references[i]["answers"]["text"][0][:60]}"'
    )

Loading local SQuAD-style evaluation metric...
Local SQuAD-style metric loaded.
Measures: Exact Match and token-level F1

Building reference answers from test split...
Reference answers prepared: 1,103

Sample references:
  [0] answer="Missing one exam will not necessarily mean that you will get"
  [1] answer="In order to succeed in this class, you have to be actively e"
  [2] answer="The grading breakdown is as follows: Class participation is "

In [11]:
test_predictions = [
    {
        "id": "0",
        "prediction_text": references[0]["answers"]["text"][0]
    }
]

test_references = [
    references[0]
]

test_result = squad_metric.compute(
    predictions=test_predictions,
    references=test_references
)

print(test_result)

{'exact_match': 100.0, 'f1': 100.0}

In [12]:
# ═══════════════════════════════════════════════════════════
# CELL 10: Define evaluation function
# Measures all five metrics for every condition
# Called after each experimental condition
# ═══════════════════════════════════════════════════════════

import time
import torch

def run_evaluation(model, tokenizer, test_data,
                   references, condition_name):
    print(f'\n{"="*55}')
    print(f'EVALUATING: {condition_name}')
    print(f'{"="*55}')
    print(f'Test examples: {len(test_data):,}')
    print(f'Progress logged every 100 examples')

    model.eval()
    torch.cuda.reset_peak_memory_stats()
    torch.cuda.empty_cache()

    all_predictions = []
    all_latencies   = []

    for i, example in enumerate(test_data):
        if i % 100 == 0:
            elapsed_min = (sum(all_latencies)/1000/60
                           if all_latencies else 0)
            avg_lat = (sum(all_latencies)/len(all_latencies)
                       if all_latencies else 0)
            print(f'  {i:4d}/{len(test_data)} | '
                  f'{elapsed_min:.1f} min | '
                  f'{avg_lat:.0f} ms/sample')

        prompt = example['prompt']
        inputs = tokenizer(
            prompt,
            return_tensors  = 'pt',
            max_length      = MAX_SEQ_LENGTH,
            truncation      = True,
            padding         = False
        ).to(model.device)

        torch.cuda.synchronize()
        t_start = time.perf_counter()

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens  = MAX_NEW_TOKENS,
                do_sample       = False,
                temperature     = 1.0,
                pad_token_id    = tokenizer.eos_token_id
            )

        torch.cuda.synchronize()
        t_end = time.perf_counter()

        latency_ms = (t_end - t_start) * 1000
        all_latencies.append(latency_ms)

        new_tokens  = outputs[0][inputs['input_ids'].shape[1]:]
        prediction  = tokenizer.decode(
            new_tokens, skip_special_tokens=True
        ).strip()
        all_predictions.append(prediction)

    peak_vram_gb = torch.cuda.max_memory_allocated() / 1e9

    predictions_fmt = [
        {'id': str(i), 'prediction_text': pred}
        for i, pred in enumerate(all_predictions)
    ]

    metric_out = squad_metric.compute(
        predictions = predictions_fmt,
        references  = references
    )

    em          = metric_out['exact_match']
    f1          = metric_out['f1']
    accuracy    = em
    avg_latency = sum(all_latencies) / len(all_latencies)

    print(f'\n{"─"*45}')
    print(f'RESULTS: {condition_name}')
    print(f'{"─"*45}')
    print(f'Exact Match:    {em:.3f}%')
    print(f'F1 Score:       {f1:.3f}%')
    print(f'Accuracy:       {accuracy:.3f}%')
    print(f'Avg Latency:    {avg_latency:.3f} ms/sample')
    print(f'Peak GPU VRAM:  {peak_vram_gb:.3f} GB')

    return {
        'condition':        condition_name,
        'em':               em,
        'f1':               f1,
        'accuracy':         accuracy,
        'avg_latency_ms':   avg_latency,
        'peak_vram_gb':     peak_vram_gb,
        'predictions':      all_predictions,
        'latencies':        all_latencies
    }

print('Evaluation function defined and ready.')

Evaluation function defined and ready.

In [13]:
# ═══════════════════════════════════════════════════════════
# CELL 11: Define stratified analysis function
# Addresses RQ2 directly
# Uses native question_type labels from SyllabusQA
# ═══════════════════════════════════════════════════════════

from collections import defaultdict

def stratified_analysis(predictions, test_raw, condition_name):
    print(f'\nRunning stratified analysis: {condition_name}')

    type_preds  = defaultdict(list)
    type_refs   = defaultdict(list)
    type_counts = defaultdict(int)

    for i, example in enumerate(test_raw):
        q_type   = example.get('question_type', 'unknown')
        ans_text = get_answer(example)
        pred     = predictions[i] if i < len(predictions) else ''

        type_preds[q_type].append({
            'id':               str(i),
            'prediction_text':  pred
        })
        type_refs[q_type].append({
            'id':       str(i),
            'answers':  {
                'text':         [ans_text],
                'answer_start': [0]
            }
        })
        type_counts[q_type] += 1

    results = {}

    print(f'\n{"Question Type":25s} {"EM %":8s} {"F1 %":8s} {"n":5s}')
    print('─' * 50)

    for q_type in sorted(type_preds.keys()):
        if type_preds[q_type]:
            r = squad_metric.compute(
                predictions = type_preds[q_type],
                references  = type_refs[q_type]
            )
            results[q_type] = {
                'exact_match':  r['exact_match'],
                'f1':           r['f1'],
                'count':        type_counts[q_type]
            }
            print(f'{q_type:25s} '
                  f'{r["exact_match"]:8.3f} '
                  f'{r["f1"]:8.3f} '
                  f'{type_counts[q_type]:5d}')

    return results

print('Stratified analysis function defined and ready.')

Stratified analysis function defined and ready.

In [ ]:
# ============================================================
# RECOVER SAVED QWEN RESULTS
# ============================================================

import json
import os

print("=" * 65)
print("RECOVERING SAVED QWEN RESULTS")
print("=" * 65)

zero_path = f"{RESULTS_DIR}/REF_qwen14b_zeroshot_CONTEXT.json"

with open(zero_path, "r") as f:
    results_qwen_zero = json.load(f)

QWEN_ZERO_EM = results_qwen_zero["em"]
QWEN_ZERO_F1 = results_qwen_zero["f1"]

print("\nQwen zero-shot recovered:")
print(f"EM: {QWEN_ZERO_EM:.3f}%")
print(f"F1: {QWEN_ZERO_F1:.3f}%")

few_path = f"{RESULTS_DIR}/REF_qwen14b_2shot_CONTEXT.json"

if os.path.exists(few_path):
    with open(few_path, "r") as f:
        results_qwen_few = json.load(f)

    QWEN_FEW_EM = results_qwen_few["em"]
    QWEN_FEW_F1 = results_qwen_few["f1"]

    print("\nQwen 2-shot recovered:")
    print(f"EM: {QWEN_FEW_EM:.3f}%")
    print(f"F1: {QWEN_FEW_F1:.3f}%")
else:
    print("\nQwen 2-shot result not found.")

=================================================================
RECOVERING SAVED QWEN RESULTS
=================================================================

Qwen zero-shot recovered:
EM: 0.000%
F1: 18.488%

Qwen 2-shot recovered:
EM: 0.091%
F1: 18.934%

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 12: FINAL CONTEXT-AWARE DATASET CHECK
# ═══════════════════════════════════════════════════════════

print("=" * 65)
print("FINAL CONTEXT-AWARE DATASET CHECK")
print("=" * 65)

print(f"Train examples:      {len(train_data):,}")
print(f"Validation examples: {len(val_data):,}")
print(f"Test examples:       {len(test_data):,}")

print("\n--- SAMPLE TRAIN PROMPT ---")
print(train_data[0]["text"][:1800])

print("\n--- SAMPLE TEST PROMPT ---")
print(test_data[0]["prompt"][:1800])

train_empty = sum(
    1 for ex in train_data
    if "Syllabus context:\n\n" in ex["text"]
)

test_empty = sum(
    1 for ex in test_data
    if "Syllabus context:\n\n" in ex["prompt"]
)

print("\nContext coverage:")
print(f"Train empty context: {train_empty}/{len(train_data)}")
print(f"Test empty context:  {test_empty}/{len(test_data)}")

assert train_empty == 0, "ERROR: blank training contexts remain."
assert test_empty == 0, "ERROR: blank test contexts remain."

print("\n✓ Context validation passed.")

=================================================================
FINAL CONTEXT-AWARE DATASET CHECK
=================================================================
Train examples:      3,018
Validation examples: 957
Test examples:       1,103

--- SAMPLE TRAIN PROMPT ---
Syllabus context:
You will do an analysis of your food intake (as recorded in your Food/Eating Log) using Chronometer (a free website)When you bring your completed Food Intake Analysis to discussion, your TA will guide you so that you can correct any errors. It is important that you are as accurate as possible when completing this Homework assignment, because there are a number of discussion activities that use your completed Food Intake Analysis. Diet Modification Project (6%) You will use Chronometer to adjust the food intake of a very imperfect intake to
CRAPP test to websites with a nutrition focus. Newspaper Article (5%) In this assignment you will compare a news article with an original research article and answer questions. Please note LATE POLICY: We allow for late submissions, however, there is a 10% deduction for every day it is late. We will accept homework up to 5 days past the due date. Discussion participation (10%) Many students fail this class because they do not go to discussion. The total points for discussion attendance, and homework (which is a part of the

Question:
Is it permissible to provide incorrect information when completing a homework assignment?


Answer: No, it is essential that you complete this Homework assignment as accurately as possible because a lot of discussion activities will rely on your completed Food Intake Analysis.


--- SAMPLE TEST PROMPT ---
Syllabus context:
Extra Credit: Four extra credit opportunities will be available during the semester. Three of these are exam reflections and the fourth is the end-of-course survey. Each one has a maximum value of 0.3 percentage points towards your final grade. Additional details will be provided as each assignment becomes available. Final Grading Scale: Final grades are rounded to the tenth and then assigned according to this scale. A 93.00 100.00% B-80.00 82.99% D+ 67.00 69.99% A-90.00 92.99% C+ 77.00 79.99% D 60.00 66.99% B+ 87.00 89.99% C 73.00 76.99% F <59.99
miss some assignments and classes are built into the course and should cover most circumstances, but if you have an unexpected situation or assignment extensions are part of your accommodations, contact me as soon as possible to discuss an extension. Note: Because of the course flexibility, extension requests should be infrequent. Student Learning Accommodations: As a member of the university, I am committed to providing an equal educational opportunity for all students. If you have a documented disability, you may be eligible for reasonable academic accommodations to help you succeed

Question:
Will I get an F as my overall grade if I miss one exam?

Answer:

Context coverage:
Train empty context: 0/3018
Test empty context:  0/1103

✓ Context validation passed.

In [ ]:
!pip install -q accelerate

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 13: LOAD QWEN2.5-14B ONCE
# Used for:
#   A. Zero-shot + corrected syllabus context
#   B. 2-shot + corrected syllabus context
# No device_map="auto" → no accelerate dependency
# ═══════════════════════════════════════════════════════════

import gc
import json
import torch

from transformers import AutoTokenizer, AutoModelForCausalLM

print("=" * 65)
print("LOADING QWEN2.5-14B-INSTRUCT")
print("=" * 65)

# ------------------------------------------------------------
# Clean GPU memory
# ------------------------------------------------------------

gc.collect()
torch.cuda.empty_cache()

set_seed(SEED)

print("GPU:", torch.cuda.get_device_name(0))

total_vram = (
    torch.cuda.get_device_properties(0).total_memory
    / 1024**3
)

free_vram_before = (
    torch.cuda.get_device_properties(0).total_memory
    - torch.cuda.memory_allocated()
) / 1024**3

print(f"Total GPU VRAM: {total_vram:.2f} GB")
print(f"Free GPU VRAM:  {free_vram_before:.2f} GB")

# ------------------------------------------------------------
# Load tokenizer
# ------------------------------------------------------------

print("\nLoading Qwen tokenizer...")

tok_qwen = AutoTokenizer.from_pretrained(
    QWEN_MODEL_ID
)

if tok_qwen.pad_token is None:
    tok_qwen.pad_token = tok_qwen.eos_token

tok_qwen.padding_side = "left"

print("Tokenizer loaded.")

# ------------------------------------------------------------
# Load model
# IMPORTANT:
# No device_map="auto"
# No torch_dtype deprecation
# ------------------------------------------------------------

print("\nLoading Qwen2.5-14B in bfloat16...")
print("This may take several minutes.")

model_qwen = AutoModelForCausalLM.from_pretrained(
    QWEN_MODEL_ID,
    dtype=torch.bfloat16,
    low_cpu_mem_usage=True
)

print("Model loaded into system memory.")

# ------------------------------------------------------------
# Move full model to A100 GPU
# ------------------------------------------------------------

print("\nMoving Qwen model to GPU...")

model_qwen = model_qwen.to("cuda")

model_qwen.config.pad_token_id = (
    tok_qwen.eos_token_id
)

model_qwen.eval()

# ------------------------------------------------------------
# Verify model
# ------------------------------------------------------------

param_count = sum(
    p.numel()
    for p in model_qwen.parameters()
)

gpu_allocated = (
    torch.cuda.memory_allocated()
    / 1024**3
)

gpu_reserved = (
    torch.cuda.memory_reserved()
    / 1024**3
)

model_device = next(
    model_qwen.parameters()
).device

model_dtype = next(
    model_qwen.parameters()
).dtype

print("\n" + "=" * 55)
print("QWEN LOAD CHECK")
print("=" * 55)

print(f"Parameters:    {param_count:,}")
print(f"GPU allocated: {gpu_allocated:.2f} GB")
print(f"GPU reserved:  {gpu_reserved:.2f} GB")
print(f"Model device:  {model_device}")
print(f"Model dtype:   {model_dtype}")

print("\n✓ Qwen2.5-14B successfully loaded.")
print("✓ No device_map used.")
print("✓ Ready for zero-shot and 2-shot evaluation.")

=================================================================
LOADING QWEN2.5-14B-INSTRUCT
=================================================================
GPU: NVIDIA A100-SXM4-40GB
Total GPU VRAM: 39.49 GB
Free GPU VRAM:  39.49 GB

Loading Qwen tokenizer...

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Tokenizer loaded.

Loading Qwen2.5-14B in bfloat16...
This may take several minutes.

model.safetensors.index.json:   0%|          | 0.00/47.5k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/579 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Model loaded into system memory.

Moving Qwen model to GPU...

=======================================================
QWEN LOAD CHECK
=======================================================
Parameters:    14,770,033,664
GPU allocated: 27.65 GB
GPU reserved:  27.65 GB
Model device:  cuda:0
Model dtype:   torch.bfloat16

✓ Qwen2.5-14B successfully loaded.
✓ No device_map used.
✓ Ready for zero-shot and 2-shot evaluation.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 14: QWEN ZERO-SHOT + CORRECTED SYLLABUS CONTEXT
# Complete corrected version
# Uses:
#   - corrected context-aware test_data
#   - local SQuAD EM/F1 metric
#   - actual Cell 11 function: stratified_analysis()
# Saves:
#   - summary JSON
# Keeps Qwen loaded for later 2-shot evaluation
# ═══════════════════════════════════════════════════════════

import json

print("=" * 65)
print("QWEN ZERO-SHOT + CORRECTED SYLLABUS CONTEXT")
print("=" * 65)

# ------------------------------------------------------------
# 1. Run full zero-shot evaluation
# ------------------------------------------------------------

results_qwen_zero = run_evaluation(
    model=model_qwen,
    tokenizer=tok_qwen,
    test_data=test_data,
    references=references,
    condition_name="Qwen2.5-14B_ZeroShot_CONTEXT"
)

# ------------------------------------------------------------
# 2. Add experiment metadata
# ------------------------------------------------------------

results_qwen_zero["model"] = "Qwen2.5-14B-Instruct"
results_qwen_zero["method"] = "Zero-Shot"
results_qwen_zero["parameters"] = "14B"
results_qwen_zero["precision"] = "bfloat16"

results_qwen_zero["context_mode"] = (
    "BM25-retrieved syllabus context"
)

results_qwen_zero["role"] = (
    "Larger zero-shot reference; "
    "not an adaptation-matched baseline"
)

# Original Accuracy field duplicated Exact Match
results_qwen_zero.pop(
    "accuracy",
    None
)

# ------------------------------------------------------------
# 3. Question-type stratified analysis
# IMPORTANT:
# Uses the actual function defined in your Cell 11
# ------------------------------------------------------------

print(
    "\nRunning question-type "
    "stratified analysis..."
)

strat_qwen_zero = stratified_analysis(
    predictions=results_qwen_zero["predictions"],
    test_raw=dataset["test"],
    condition_name="Qwen2.5-14B_ZeroShot_CONTEXT"
)

results_qwen_zero["stratified"] = (
    strat_qwen_zero
)

# ------------------------------------------------------------
# 4. Prepare summary JSON
# Do not put large prediction/latency lists in summary file
# ------------------------------------------------------------

save_qwen_zero = {
    k: v
    for k, v in results_qwen_zero.items()
    if k not in [
        "predictions",
        "latencies"
    ]
}

QWEN_ZERO_PATH = (
    f"{RESULTS_DIR}/"
    f"REF_qwen14b_zeroshot_CONTEXT.json"
)

with open(
    QWEN_ZERO_PATH,
    "w"
) as f:

    json.dump(
        save_qwen_zero,
        f,
        indent=2
    )

# ------------------------------------------------------------
# 5. Save individual predictions separately
# This protects the expensive evaluation output
# ------------------------------------------------------------

QWEN_ZERO_PRED_PATH = (
    f"{RESULTS_DIR}/"
    f"REF_qwen14b_zeroshot_CONTEXT_predictions.jsonl"
)

with open(
    QWEN_ZERO_PRED_PATH,
    "w",
    encoding="utf-8"
) as f:

    for i, prediction in enumerate(
        results_qwen_zero["predictions"]
    ):

        raw = dataset["test"][i]

        row = {
            "id": str(i),
            "syllabus_name":
                raw["syllabus_name"],
            "question_type":
                raw["question_type"],
            "question":
                raw["question"],
            "reference_answer":
                get_answer(raw),
            "prediction":
                prediction
        }

        f.write(
            json.dumps(
                row,
                ensure_ascii=False
            )
            + "\n"
        )

# ------------------------------------------------------------
# 6. Store metrics for later few-shot comparison
# ------------------------------------------------------------

QWEN_ZERO_EM = (
    results_qwen_zero["em"]
)

QWEN_ZERO_F1 = (
    results_qwen_zero["f1"]
)

# ------------------------------------------------------------
# 7. Display final result
# ------------------------------------------------------------

print("\n" + "=" * 55)
print("QWEN ZERO-SHOT + CONTEXT FINAL RESULTS")
print("=" * 55)

print(
    f"Exact Match: "
    f"{QWEN_ZERO_EM:.3f}%"
)

print(
    f"F1 Score:    "
    f"{QWEN_ZERO_F1:.3f}%"
)

print(
    f"Avg Latency: "
    f"{results_qwen_zero['avg_latency_ms']:.3f} "
    f"ms/sample"
)

print(
    f"Peak VRAM:   "
    f"{results_qwen_zero['peak_vram_gb']:.3f} GB"
)

print("\nSummary saved to:")
print(QWEN_ZERO_PATH)

print("\nPredictions saved to:")
print(QWEN_ZERO_PRED_PATH)

print("\n✓ Qwen zero-shot + context complete.")
print("✓ Keep Qwen loaded for the 2-shot experiment.")
print("✓ Continue to Cell 15.")

=================================================================
QWEN ZERO-SHOT + CORRECTED SYLLABUS CONTEXT
=================================================================

=======================================================
EVALUATING: Qwen2.5-14B_ZeroShot_CONTEXT
=======================================================
Test examples: 1,103
Progress logged every 100 examples
     0/1103 | 0.0 min | 0 ms/sample
   100/1103 | 6.0 min | 3593 ms/sample
   200/1103 | 12.0 min | 3587 ms/sample
   300/1103 | 17.9 min | 3586 ms/sample
   400/1103 | 23.9 min | 3581 ms/sample
   500/1103 | 29.9 min | 3584 ms/sample
   600/1103 | 35.9 min | 3588 ms/sample
   700/1103 | 41.9 min | 3591 ms/sample
   800/1103 | 47.9 min | 3592 ms/sample
   900/1103 | 53.9 min | 3595 ms/sample
  1000/1103 | 59.9 min | 3596 ms/sample
  1100/1103 | 66.0 min | 3598 ms/sample

─────────────────────────────────────────────
RESULTS: Qwen2.5-14B_ZeroShot_CONTEXT
─────────────────────────────────────────────
Exact Match:    0.000%
F1 Score:       18.488%
Accuracy:       0.000%
Avg Latency:    3597.464 ms/sample
Peak GPU VRAM:  29.868 GB

Running question-type stratified analysis...

Running stratified analysis: Qwen2.5-14B_ZeroShot_CONTEXT

Question Type             EM %     F1 %     n
──────────────────────────────────────────────────
multi factual                0.000   29.660   158
multi reasoning              0.000   25.602   158
no answer                    0.000    1.980   155
single factual               0.000   16.393   158
single reasoning             0.000   24.683   158
summarization                0.000   27.788   158
yes/no                       0.000    3.000   158

=======================================================
QWEN ZERO-SHOT + CONTEXT FINAL RESULTS
=======================================================
Exact Match: 0.000%
F1 Score:    18.488%
Avg Latency: 3597.464 ms/sample
Peak VRAM:   29.868 GB

Summary saved to:
/content/drive/MyDrive/MR603_Thesis/results/REF_qwen14b_zeroshot_CONTEXT.json

Predictions saved to:
/content/drive/MyDrive/MR603_Thesis/results/REF_qwen14b_zeroshot_CONTEXT_predictions.jsonl

✓ Qwen zero-shot + context complete.
✓ Keep Qwen loaded for the 2-shot experiment.
✓ Continue to Cell 15.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 15: SAVE ZERO-SHOT PREDICTIONS + SELECT 2-SHOT DEMOS
# Demonstrations come ONLY from the training split
# ═══════════════════════════════════════════════════════════

import json

print("=" * 65)
print("PREPARING QWEN 2-SHOT EXPERIMENT")
print("=" * 65)

# ------------------------------------------------------------
# A. Save completed zero-shot predictions
# ------------------------------------------------------------

ZERO_PRED_PATH = (
    f"{RESULTS_DIR}/"
    f"REF_qwen14b_zeroshot_CONTEXT_predictions.jsonl"
)

with open(
    ZERO_PRED_PATH,
    "w",
    encoding="utf-8"
) as f:

    for i, prediction in enumerate(
        results_qwen_zero["predictions"]
    ):

        raw = dataset["test"][i]

        row = {
            "id": str(i),
            "syllabus_name": raw["syllabus_name"],
            "question_type": raw["question_type"],
            "question": raw["question"],
            "reference_answer": get_answer(raw),
            "prediction": prediction
        }

        f.write(
            json.dumps(
                row,
                ensure_ascii=False
            ) + "\n"
        )

print("\nZero-shot predictions safely saved:")
print(ZERO_PRED_PATH)

# ------------------------------------------------------------
# B. Build candidate training demonstrations
# ------------------------------------------------------------

candidate_examples = []

for idx, ex in enumerate(dataset["train"]):

    question = str(ex["question"]).strip()
    answer = str(get_answer(ex)).strip()
    qtype = str(ex["question_type"]).strip()

    # Prefer compact demonstrations
    total_words = (
        len(question.split())
        + len(answer.split())
    )

    candidate_examples.append(
        {
            "index": idx,
            "question_type": qtype,
            "question": question,
            "answer": answer,
            "length": total_words,
            "example": ex
        }
    )

# Shortest first, then original train index for deterministic order
candidate_examples = sorted(
    candidate_examples,
    key=lambda x: (
        x["length"],
        x["index"]
    )
)

# ------------------------------------------------------------
# C. Select exactly two DIFFERENT question types
# ------------------------------------------------------------

fewshot_examples = []
fewshot_metadata = []
seen_types = set()

for item in candidate_examples:

    qtype = item["question_type"]

    if qtype not in seen_types:

        fewshot_examples.append(
            item["example"]
        )

        fewshot_metadata.append(
            {
                "train_index": item["index"],
                "question_type": qtype,
                "question": item["question"],
                "answer": item["answer"]
            }
        )

        seen_types.add(qtype)

    if len(fewshot_examples) == 2:
        break

assert len(fewshot_examples) == 2, (
    "Could not select two distinct training question types."
)

# ------------------------------------------------------------
# D. Display selected demonstrations
# ------------------------------------------------------------

print("\n" + "=" * 55)
print("SELECTED 2-SHOT DEMONSTRATIONS")
print("=" * 55)

for i, demo in enumerate(
    fewshot_metadata,
    start=1
):

    print(f"\nDEMONSTRATION {i}")
    print(
        "Training index:",
        demo["train_index"]
    )
    print(
        "Question type:",
        demo["question_type"]
    )
    print(
        "Question:",
        demo["question"]
    )
    print(
        "Answer:",
        demo["answer"]
    )

print("\n✓ Demonstrations selected from TRAIN split only.")
print("✓ No validation/test answers were used.")

=================================================================
PREPARING QWEN 2-SHOT EXPERIMENT
=================================================================

Zero-shot predictions safely saved:
/content/drive/MyDrive/MR603_Thesis/results/REF_qwen14b_zeroshot_CONTEXT_predictions.jsonl

=======================================================
SELECTED 2-SHOT DEMONSTRATIONS
=======================================================

DEMONSTRATION 1
Training index: 506
Question type: yes/no
Question: Are there prerequisites?
Answer: Yes

DEMONSTRATION 2
Training index: 100
Question type: no answer
Question: can i monitors?
Answer: No/insufficient information

✓ Demonstrations selected from TRAIN split only.
✓ No validation/test answers were used.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 16: BUILD QWEN 2-SHOT + SYLLABUS CONTEXT PROMPTS
# Keeps every prompt within MAX_SEQ_LENGTH = 512
# ═══════════════════════════════════════════════════════════

print("=" * 65)
print("BUILDING QWEN 2-SHOT CONTEXT PROMPTS")
print("=" * 65)

# ------------------------------------------------------------
# A. Create fixed demonstration text
# ------------------------------------------------------------

def build_demo_text(demos):

    blocks = []

    for i, demo in enumerate(
        demos,
        start=1
    ):

        blocks.append(
            f"Example {i}\n"
            f"Question: {demo['question']}\n"
            f"Answer: {get_answer(demo)}"
        )

    return "\n\n".join(blocks)


DEMO_TEXT = build_demo_text(
    fewshot_examples
)

print("\nDemonstration block:")
print(DEMO_TEXT)

# ------------------------------------------------------------
# B. Context trimming function
# Only syllabus context is shortened when necessary
# ------------------------------------------------------------

def trim_context_for_qwen_fewshot(
    context,
    prefix,
    suffix,
    tokenizer,
    max_length=MAX_SEQ_LENGTH,
    safety_margin=16
):

    prefix_ids = tokenizer(
        prefix,
        add_special_tokens=False
    )["input_ids"]

    suffix_ids = tokenizer(
        suffix,
        add_special_tokens=False
    )["input_ids"]

    context_ids = tokenizer(
        context,
        add_special_tokens=False
    )["input_ids"]

    available_context_tokens = (
        max_length
        - len(prefix_ids)
        - len(suffix_ids)
        - safety_margin
    )

    if available_context_tokens <= 0:
        return ""

    trimmed_ids = context_ids[
        :available_context_tokens
    ]

    trimmed_context = tokenizer.decode(
        trimmed_ids,
        skip_special_tokens=True
    )

    return trimmed_context

# ------------------------------------------------------------
# C. Few-shot formatter
# ------------------------------------------------------------

def format_qwen_fewshot(example):

    question = str(
        example["question"]
    ).strip()

    context = retrieve_relevant_context(
        example["syllabus_name"],
        question
    )

    prefix = (
        "You are a teaching assistant answering "
        "course-logistics questions.\n"
        "Use the syllabus context to answer the final question.\n\n"
        f"{DEMO_TEXT}\n\n"
        "Syllabus context:\n"
    )

    suffix = (
        f"\n\nQuestion: {question}\n"
        f"Answer:"
    )

    trimmed_context = (
        trim_context_for_qwen_fewshot(
            context=context,
            prefix=prefix,
            suffix=suffix,
            tokenizer=tok_qwen,
            max_length=MAX_SEQ_LENGTH
        )
    )

    prompt = (
        prefix
        + trimmed_context
        + suffix
    )

    return {
        "prompt": prompt
    }

# ------------------------------------------------------------
# D. Build test set
# ------------------------------------------------------------

qwen_fewshot_test_data = (
    dataset["test"].map(
        format_qwen_fewshot
    )
)

print(
    "\nFew-shot test examples:",
    len(qwen_fewshot_test_data)
)

# ------------------------------------------------------------
# E. Check every prompt length
# ------------------------------------------------------------

fewshot_lengths = []

for ex in qwen_fewshot_test_data:

    n_tokens = len(
        tok_qwen(
            ex["prompt"],
            add_special_tokens=True
        )["input_ids"]
    )

    fewshot_lengths.append(
        n_tokens
    )

min_len = min(
    fewshot_lengths
)

max_len = max(
    fewshot_lengths
)

avg_len = (
    sum(fewshot_lengths)
    / len(fewshot_lengths)
)

over_limit = sum(
    n > MAX_SEQ_LENGTH
    for n in fewshot_lengths
)

print("\n" + "=" * 55)
print("2-SHOT TOKEN LENGTH CHECK")
print("=" * 55)

print(
    f"Minimum tokens: {min_len}"
)
print(
    f"Maximum tokens: {max_len}"
)
print(
    f"Average tokens: {avg_len:.2f}"
)
print(
    f"Over {MAX_SEQ_LENGTH}: {over_limit}"
)

assert over_limit == 0, (
    "ERROR: Some 2-shot prompts exceed 512 tokens."
)

# ------------------------------------------------------------
# F. Display one complete prompt
# ------------------------------------------------------------

print("\n--- SAMPLE 2-SHOT PROMPT ---\n")

print(
    qwen_fewshot_test_data[0]["prompt"]
)

print("\n✓ All 2-shot prompts fit within 512 tokens.")

=================================================================
BUILDING QWEN 2-SHOT CONTEXT PROMPTS
=================================================================

Demonstration block:
Example 1
Question: Are there prerequisites?
Answer: Yes

Example 2
Question: can i monitors?
Answer: No/insufficient information

Map:   0%|          | 0/1103 [00:00<?, ? examples/s]

Few-shot test examples: 1103

=======================================================
2-SHOT TOKEN LENGTH CHECK
=======================================================
Minimum tokens: 179
Maximum tokens: 496
Average tokens: 327.93
Over 512: 0

--- SAMPLE 2-SHOT PROMPT ---

You are a teaching assistant answering course-logistics questions.
Use the syllabus context to answer the final question.

Example 1
Question: Are there prerequisites?
Answer: Yes

Example 2
Question: can i monitors?
Answer: No/insufficient information

Syllabus context:
Extra Credit: Four extra credit opportunities will be available during the semester. Three of these are exam reflections and the fourth is the end-of-course survey. Each one has a maximum value of 0.3 percentage points towards your final grade. Additional details will be provided as each assignment becomes available. Final Grading Scale: Final grades are rounded to the tenth and then assigned according to this scale. A 93.00 100.00% B-80.00 82.99% D+ 67.00 69.99% A-90.00 92.99% C+ 77.00 79.99% D 60.00 66.99% B+ 87.00 89.99% C 73.00 76.99% F <59.99
miss some assignments and classes are built into the course and should cover most circumstances, but if you have an unexpected situation or assignment extensions are part of your accommodations, contact me as soon as possible to discuss an extension. Note: Because of the course flexibility, extension requests should be infrequent. Student Learning Accommodations: As a member of the university, I am committed to providing an equal educational opportunity for all students. If you have a documented disability, you may be eligible for reasonable academic accommodations to help you succeed

Question: Will I get an F as my overall grade if I miss one exam?
Answer:

✓ All 2-shot prompts fit within 512 tokens.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 17: QWEN 2-SHOT + CORRECTED SYLLABUS CONTEXT
# ═══════════════════════════════════════════════════════════

import json

print("=" * 65)
print("QWEN 2-SHOT + CORRECTED SYLLABUS CONTEXT")
print("=" * 65)

# ------------------------------------------------------------
# A. Full evaluation
# ------------------------------------------------------------

results_qwen_few = run_evaluation(
    model=model_qwen,
    tokenizer=tok_qwen,
    test_data=qwen_fewshot_test_data,
    references=references,
    condition_name="Qwen2.5-14B_2Shot_CONTEXT"
)

# ------------------------------------------------------------
# B. Metadata
# ------------------------------------------------------------

results_qwen_few["model"] = (
    "Qwen2.5-14B-Instruct"
)

results_qwen_few["method"] = (
    "2-Shot Prompting"
)

results_qwen_few["shots"] = 2

results_qwen_few["parameters"] = (
    "14B"
)

results_qwen_few["precision"] = (
    "bfloat16"
)

results_qwen_few["context_mode"] = (
    "BM25-retrieved syllabus context"
)

results_qwen_few["role"] = (
    "Larger few-shot reference; "
    "not adaptation-matched"
)

results_qwen_few["demonstrations"] = (
    fewshot_metadata
)

# Accuracy duplicated EM in original pipeline
results_qwen_few.pop(
    "accuracy",
    None
)

# ------------------------------------------------------------
# C. Stratified evaluation
# Uses your ACTUAL Cell 11 function
# ------------------------------------------------------------

print(
    "\nRunning question-type "
    "stratified analysis..."
)

strat_qwen_few = stratified_analysis(
    predictions=results_qwen_few[
        "predictions"
    ],
    test_raw=dataset["test"],
    condition_name=(
        "Qwen2.5-14B_2Shot_CONTEXT"
    )
)

results_qwen_few["stratified"] = (
    strat_qwen_few
)

# ------------------------------------------------------------
# D. Save summary
# ------------------------------------------------------------

save_qwen_few = {
    k: v
    for k, v in results_qwen_few.items()
    if k not in [
        "predictions",
        "latencies"
    ]
}

QWEN_FEW_PATH = (
    f"{RESULTS_DIR}/"
    f"REF_qwen14b_2shot_CONTEXT.json"
)

with open(
    QWEN_FEW_PATH,
    "w"
) as f:

    json.dump(
        save_qwen_few,
        f,
        indent=2
    )

# ------------------------------------------------------------
# E. Save individual predictions
# ------------------------------------------------------------

QWEN_FEW_PRED_PATH = (
    f"{RESULTS_DIR}/"
    f"REF_qwen14b_2shot_CONTEXT_predictions.jsonl"
)

with open(
    QWEN_FEW_PRED_PATH,
    "w",
    encoding="utf-8"
) as f:

    for i, prediction in enumerate(
        results_qwen_few["predictions"]
    ):

        raw = dataset["test"][i]

        row = {
            "id": str(i),
            "syllabus_name":
                raw["syllabus_name"],
            "question_type":
                raw["question_type"],
            "question":
                raw["question"],
            "reference_answer":
                get_answer(raw),
            "prediction":
                prediction
        }

        f.write(
            json.dumps(
                row,
                ensure_ascii=False
            ) + "\n"
        )

# ------------------------------------------------------------
# F. Store metrics
# ------------------------------------------------------------

QWEN_FEW_EM = (
    results_qwen_few["em"]
)

QWEN_FEW_F1 = (
    results_qwen_few["f1"]
)

# ------------------------------------------------------------
# G. Display result
# ------------------------------------------------------------

print("\n" + "=" * 55)
print("QWEN 2-SHOT + CONTEXT RESULTS")
print("=" * 55)

print(
    f"Exact Match: "
    f"{QWEN_FEW_EM:.3f}%"
)

print(
    f"F1 Score:    "
    f"{QWEN_FEW_F1:.3f}%"
)

print(
    f"Avg Latency: "
    f"{results_qwen_few['avg_latency_ms']:.3f} "
    f"ms/sample"
)

print(
    f"Peak VRAM:   "
    f"{results_qwen_few['peak_vram_gb']:.3f} GB"
)

print("\nSummary saved:")
print(QWEN_FEW_PATH)

print("\nPredictions saved:")
print(QWEN_FEW_PRED_PATH)

=================================================================
QWEN 2-SHOT + CORRECTED SYLLABUS CONTEXT
=================================================================

=======================================================
EVALUATING: Qwen2.5-14B_2Shot_CONTEXT
=======================================================
Test examples: 1,103
Progress logged every 100 examples
     0/1103 | 0.0 min | 0 ms/sample
   100/1103 | 5.9 min | 3545 ms/sample
   200/1103 | 11.8 min | 3536 ms/sample
   300/1103 | 17.7 min | 3544 ms/sample
   400/1103 | 23.6 min | 3542 ms/sample
   500/1103 | 29.4 min | 3529 ms/sample
   600/1103 | 35.3 min | 3528 ms/sample
   700/1103 | 41.2 min | 3531 ms/sample
   800/1103 | 47.1 min | 3533 ms/sample
   900/1103 | 53.0 min | 3533 ms/sample
  1000/1103 | 58.8 min | 3531 ms/sample
  1100/1103 | 64.7 min | 3528 ms/sample

─────────────────────────────────────────────
RESULTS: Qwen2.5-14B_2Shot_CONTEXT
─────────────────────────────────────────────
Exact Match:    0.091%
F1 Score:       18.934%
Accuracy:       0.091%
Avg Latency:    3528.325 ms/sample
Peak GPU VRAM:  29.864 GB

Running question-type stratified analysis...

Running stratified analysis: Qwen2.5-14B_2Shot_CONTEXT

Question Type             EM %     F1 %     n
──────────────────────────────────────────────────
multi factual                0.000   29.819   158
multi reasoning              0.000   25.518   158
no answer                    0.000    3.627   155
single factual               0.633   18.211   158
single reasoning             0.000   23.472   158
summarization                0.000   28.525   158
yes/no                       0.000    3.075   158

=======================================================
QWEN 2-SHOT + CONTEXT RESULTS
=======================================================
Exact Match: 0.091%
F1 Score:    18.934%
Avg Latency: 3528.325 ms/sample
Peak VRAM:   29.864 GB

Summary saved:
/content/drive/MyDrive/MR603_Thesis/results/REF_qwen14b_2shot_CONTEXT.json

Predictions saved:
/content/drive/MyDrive/MR603_Thesis/results/REF_qwen14b_2shot_CONTEXT_predictions.jsonl

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 18: QWEN ZERO-SHOT VS 2-SHOT COMPARISON
# Save comparison and clear Qwen before Gemma training
# ═══════════════════════════════════════════════════════════

import json
import gc
import torch

print("=" * 65)
print("QWEN PROMPTING COMPARISON")
print("=" * 65)

# ------------------------------------------------------------
# Retrieve results
# ------------------------------------------------------------

QWEN_ZERO_EM = results_qwen_zero["em"]
QWEN_ZERO_F1 = results_qwen_zero["f1"]

QWEN_FEW_EM = results_qwen_few["em"]
QWEN_FEW_F1 = results_qwen_few["f1"]

delta_em = QWEN_FEW_EM - QWEN_ZERO_EM
delta_f1 = QWEN_FEW_F1 - QWEN_ZERO_F1

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print(f"\nQwen2.5-14B Zero-Shot + Context:")
print(f"  Exact Match:   {QWEN_ZERO_EM:.3f}%")
print(f"  F1 Score:      {QWEN_ZERO_F1:.3f}%")
print(
    f"  Avg Latency:   "
    f"{results_qwen_zero['avg_latency_ms']:.3f} ms/sample"
)
print(
    f"  Peak VRAM:     "
    f"{results_qwen_zero['peak_vram_gb']:.3f} GB"
)

print(f"\nQwen2.5-14B 2-Shot + Context:")
print(f"  Exact Match:   {QWEN_FEW_EM:.3f}%")
print(f"  F1 Score:      {QWEN_FEW_F1:.3f}%")
print(
    f"  Avg Latency:   "
    f"{results_qwen_few['avg_latency_ms']:.3f} ms/sample"
)
print(
    f"  Peak VRAM:     "
    f"{results_qwen_few['peak_vram_gb']:.3f} GB"
)

print("\n" + "─" * 50)

print(
    f"2-shot minus zero-shot EM: "
    f"{delta_em:+.3f} percentage points"
)

print(
    f"2-shot minus zero-shot F1: "
    f"{delta_f1:+.3f} percentage points"
)

# ------------------------------------------------------------
# Save comparison
# ------------------------------------------------------------

qwen_comparison = {
    "zero_shot_context": {
        "em": QWEN_ZERO_EM,
        "f1": QWEN_ZERO_F1,
        "avg_latency_ms":
            results_qwen_zero["avg_latency_ms"],
        "peak_vram_gb":
            results_qwen_zero["peak_vram_gb"]
    },

    "two_shot_context": {
        "em": QWEN_FEW_EM,
        "f1": QWEN_FEW_F1,
        "avg_latency_ms":
            results_qwen_few["avg_latency_ms"],
        "peak_vram_gb":
            results_qwen_few["peak_vram_gb"]
    },

    "two_shot_minus_zero_shot": {
        "delta_em_pp": delta_em,
        "delta_f1_pp": delta_f1
    }
}

QWEN_COMPARE_PATH = (
    f"{RESULTS_DIR}/"
    f"Qwen_Context_Prompting_Comparison.json"
)

with open(QWEN_COMPARE_PATH, "w") as f:
    json.dump(
        qwen_comparison,
        f,
        indent=2
    )

print("\nResults saved to:")
print(QWEN_COMPARE_PATH)

# ------------------------------------------------------------
# Clear Qwen
# ------------------------------------------------------------

del model_qwen
del tok_qwen

gc.collect()
torch.cuda.empty_cache()

vram_free = (
    torch.cuda.get_device_properties(0).total_memory
    - torch.cuda.memory_allocated()
) / 1e9

print(
    f"\nMemory cleared. "
    f"{vram_free:.1f} GB VRAM free."
)

print(
    "Ready for Gemma-2B LoRA training."
)

=================================================================
QWEN PROMPTING COMPARISON
=================================================================

Qwen2.5-14B Zero-Shot + Context:
  Exact Match:   0.000%
  F1 Score:      18.488%
  Avg Latency:   3597.464 ms/sample
  Peak VRAM:     29.868 GB

Qwen2.5-14B 2-Shot + Context:
  Exact Match:   0.091%
  F1 Score:      18.934%
  Avg Latency:   3528.325 ms/sample
  Peak VRAM:     29.864 GB

──────────────────────────────────────────────────
2-shot minus zero-shot EM: +0.091 percentage points
2-shot minus zero-shot F1: +0.445 percentage points

Results saved to:
/content/drive/MyDrive/MR603_Thesis/results/Qwen_Context_Prompting_Comparison.json

Memory cleared. 42.4 GB VRAM free.
Ready for Gemma-2B LoRA training.

In [ ]:
!pip install -q --upgrade "accelerate>=1.1.0"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 9.7 MB/s eta 0:00:00

In [ ]:
import accelerate
print("Accelerate version:", accelerate.__version__)

Accelerate version: 0.33.0

In [ ]:
import accelerate
print(accelerate.__version__)

1.15.0

In [ ]:
!pip show accelerate

Name: accelerate
Version: 1.15.0
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The Hugging Face team
Author-email: transformers@huggingface.co
License: Apache
Location: /usr/local/lib/python3.13/dist-packages
Requires: huggingface_hub, numpy, packaging, psutil, pyyaml, safetensors, torch
Required-by: peft, trl

In [ ]:
# ═══════════════════════════════════════════════════════════
# RECOVER SAVED QWEN RESULTS AFTER RUNTIME RESTART
# ═══════════════════════════════════════════════════════════

import json
import os

print("=" * 65)
print("RECOVERING SAVED QWEN RESULTS")
print("=" * 65)

# ------------------------------------------------------------
# Zero-shot
# ------------------------------------------------------------

zero_path = (
    f"{RESULTS_DIR}/"
    f"REF_qwen14b_zeroshot_CONTEXT.json"
)

with open(zero_path, "r") as f:
    results_qwen_zero = json.load(f)

QWEN_ZERO_EM = (
    results_qwen_zero["em"]
)

QWEN_ZERO_F1 = (
    results_qwen_zero["f1"]
)

print("\nQwen zero-shot recovered:")
print(f"EM: {QWEN_ZERO_EM:.3f}%")
print(f"F1: {QWEN_ZERO_F1:.3f}%")

# ------------------------------------------------------------
# Few-shot
# ------------------------------------------------------------

few_path = (
    f"{RESULTS_DIR}/"
    f"REF_qwen14b_2shot_CONTEXT.json"
)

if os.path.exists(few_path):

    with open(few_path, "r") as f:
        results_qwen_few = json.load(f)

    QWEN_FEW_EM = (
        results_qwen_few["em"]
    )

    QWEN_FEW_F1 = (
        results_qwen_few["f1"]
    )

    print("\nQwen 2-shot recovered:")
    print(f"EM: {QWEN_FEW_EM:.3f}%")
    print(f"F1: {QWEN_FEW_F1:.3f}%")

else:

    print(
        "\nQwen 2-shot result not found."
    )

print("\n✓ Saved Qwen results restored.")
print("✓ No Qwen evaluation needs to be rerun.")

=================================================================
RECOVERING SAVED QWEN RESULTS
=================================================================

Qwen zero-shot recovered:
EM: 0.000%
F1: 18.488%

Qwen 2-shot recovered:
EM: 0.091%
F1: 18.934%

✓ Saved Qwen results restored.
✓ No Qwen evaluation needs to be rerun.

In [15]:
# ═══════════════════════════════════════════════════════════
# DIAGNOSTIC: CHECK ACCELERATE SEEN BY PYTHON/TRANSFORMERS
# ═══════════════════════════════════════════════════════════

import sys
import accelerate
import transformers
import importlib.metadata

from transformers.utils import is_accelerate_available

print("Python executable:")
print(sys.executable)

print("\nAccelerate imported version:")
print(accelerate.__version__)

print("\nAccelerate package version:")
print(importlib.metadata.version("accelerate"))

print("\nAccelerate loaded from:")
print(accelerate.__file__)

print("\nTransformers version:")
print(transformers.__version__)

print("\nDoes Transformers detect Accelerate?")
print(is_accelerate_available())

Python executable:
/usr/bin/python3

Accelerate imported version:
0.33.0

Accelerate package version:
0.33.0

Accelerate loaded from:
/usr/local/lib/python3.13/dist-packages/accelerate/__init__.py

Transformers version:
5.16.1

Does Transformers detect Accelerate?
False

In [16]:
# ============================================================
# FIX DUPLICATE / STALE ACCELERATE INSTALLATION
# ============================================================

!pip uninstall -y accelerate
!pip install -q --no-cache-dir --no-deps "accelerate==1.15.0"

print("Accelerate reinstalled.")

Found existing installation: accelerate 0.33.0
Uninstalling accelerate-0.33.0:
  Successfully uninstalled accelerate-0.33.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 114.9 MB/s eta 0:00:00
Accelerate reinstalled.

In [17]:
import accelerate
import importlib.metadata

print("Imported accelerate:", accelerate.__version__)
print("Package metadata:", importlib.metadata.version("accelerate"))
print("Loaded from:", accelerate.__file__)

Imported accelerate: 0.33.0
Package metadata: 1.15.0
Loaded from: /usr/local/lib/python3.13/dist-packages/accelerate/__init__.py

In [18]:
import importlib
import transformers.utils.import_utils as import_utils

importlib.reload(import_utils)

print(
    "Transformers detects Accelerate:",
    import_utils.is_accelerate_available()
)

Transformers detects Accelerate: True

In [ ]:
# ═══════════════════════════════════════════════════════════
# BACKUP CORRECTED DATA BEFORE RUNTIME RESTART
# ═══════════════════════════════════════════════════════════

import os
from datasets import DatasetDict

RECOVERY_DIR = f"{BASE_DIR}/recovery_gemma_context"

os.makedirs(RECOVERY_DIR, exist_ok=True)

corrected_data = DatasetDict({
    "train": train_data,
    "validation": val_data,
    "test": test_data
})

corrected_data.save_to_disk(
    f"{RECOVERY_DIR}/corrected_data"
)

dataset.save_to_disk(
    f"{RECOVERY_DIR}/raw_dataset"
)

print("✓ Corrected train/validation/test saved.")
print("✓ Raw SyllabusQA dataset saved.")
print("Location:")
print(RECOVERY_DIR)

Saving the dataset (0/1 shards):   0%|          | 0/3018 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/957 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/1103 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/3018 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/957 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/1103 [00:00<?, ? examples/s]

✓ Corrected train/validation/test saved.
✓ Raw SyllabusQA dataset saved.
Location:
/content/drive/MyDrive/MR603_Thesis/recovery_gemma_context

In [19]:
import accelerate
import importlib.metadata

print("Imported Accelerate:", accelerate.__version__)
print("Metadata Accelerate:", importlib.metadata.version("accelerate"))

Imported Accelerate: 0.33.0
Metadata Accelerate: 1.15.0

In [ ]:
from transformers.utils import is_accelerate_available
print("Transformers detects Accelerate:", is_accelerate_available())

Transformers detects Accelerate: True

In [ ]:
from transformers import TrainingArguments

test_args = TrainingArguments(
    output_dir="/tmp/test_training_args",
    per_device_train_batch_size=1,
    report_to="none"
)

print("✓ TrainingArguments works.")

✓ TrainingArguments works.

In [20]:
import sys
import importlib

# Remove stale accelerate modules from memory
for name in list(sys.modules.keys()):
    if name == "accelerate" or name.startswith("accelerate."):
        del sys.modules[name]

# Re-import fresh installation
import accelerate
import importlib.metadata

print("Imported Accelerate:", accelerate.__version__)
print("Metadata Accelerate:", importlib.metadata.version("accelerate"))
print("Loaded from:", accelerate.__file__)

Imported Accelerate: 1.15.0
Metadata Accelerate: 1.15.0
Loaded from: /usr/local/lib/python3.13/dist-packages/accelerate/__init__.py

In [21]:
import importlib
import transformers.utils.import_utils as import_utils

importlib.reload(import_utils)

print(
    "Transformers detects Accelerate:",
    import_utils.is_accelerate_available()
)

Transformers detects Accelerate: True

In [23]:
!pip uninstall -y accelerate
!pip install -q --no-cache-dir "accelerate==1.15.0"

import importlib.metadata

print("Installed accelerate metadata:",
      importlib.metadata.version("accelerate"))

Found existing installation: accelerate 1.15.0
Uninstalling accelerate-1.15.0:
  Successfully uninstalled accelerate-1.15.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 95.4 MB/s eta 0:00:00
Installed accelerate metadata: 1.15.0

In [1]:
import accelerate
import transformers
import importlib.metadata
from transformers.utils import is_accelerate_available

print("Imported Accelerate:", accelerate.__version__)
print("Metadata Accelerate:",
      importlib.metadata.version("accelerate"))
print("Transformers:", transformers.__version__)
print("Transformers detects Accelerate:",
      is_accelerate_available())

Imported Accelerate: 1.15.0
Metadata Accelerate: 1.15.0
Transformers: 5.16.1
Transformers detects Accelerate: True

In [2]:
from transformers import TrainingArguments

test_args = TrainingArguments(
    output_dir="/tmp/qlora_test",
    per_device_train_batch_size=1,
    report_to="none"
)

print("✓ TrainingArguments works.")

✓ TrainingArguments works.

In [ ]:
# ═══════════════════════════════════════════════════════════
# RECOVER CORRECTED DATASETS
# ═══════════════════════════════════════════════════════════

from datasets import load_from_disk

RECOVERY_DIR = f"{BASE_DIR}/recovery_gemma_context"

corrected_data = load_from_disk(
    f"{RECOVERY_DIR}/corrected_data"
)

train_data = corrected_data["train"]
val_data = corrected_data["validation"]
test_data = corrected_data["test"]

dataset = load_from_disk(
    f"{RECOVERY_DIR}/raw_dataset"
)

print("Corrected datasets restored:")
print("Train:", len(train_data))
print("Validation:", len(val_data))
print("Test:", len(test_data))
print("Raw test:", len(dataset["test"]))

print("\nSample corrected test prompt:")
print(test_data[0]["prompt"][:1000])

Corrected datasets restored:
Train: 3018
Validation: 957
Test: 1103
Raw test: 1103

Sample corrected test prompt:
Syllabus context:
Extra Credit: Four extra credit opportunities will be available during the semester. Three of these are exam reflections and the fourth is the end-of-course survey. Each one has a maximum value of 0.3 percentage points towards your final grade. Additional details will be provided as each assignment becomes available. Final Grading Scale: Final grades are rounded to the tenth and then assigned according to this scale. A 93.00 100.00% B-80.00 82.99% D+ 67.00 69.99% A-90.00 92.99% C+ 77.00 79.99% D 60.00 66.99% B+ 87.00 89.99% C 73.00 76.99% F <59.99
miss some assignments and classes are built into the course and should cover most circumstances, but if you have an unexpected situation or assignment extensions are part of your accommodations, contact me as soon as possible to discuss an extension. Note: Because of the course flexibility, extension requests should be infrequent. Student Learning Accommodations: As a member of the university, I am committed to providing an

In [ ]:
print("Train:", len(train_data))
print("Validation:", len(val_data))
print("Test:", len(test_data))

print("\nSample test prompt:")
print(test_data[0]["prompt"][:800])

print("\nQwen zero-shot F1:", QWEN_ZERO_F1)

if "QWEN_FEW_F1" in globals():
    print("Qwen 2-shot F1:", QWEN_FEW_F1)

Train: 3018
Validation: 957
Test: 1103

Sample test prompt:
Syllabus context:
Extra Credit: Four extra credit opportunities will be available during the semester. Three of these are exam reflections and the fourth is the end-of-course survey. Each one has a maximum value of 0.3 percentage points towards your final grade. Additional details will be provided as each assignment becomes available. Final Grading Scale: Final grades are rounded to the tenth and then assigned according to this scale. A 93.00 100.00% B-80.00 82.99% D+ 67.00 69.99% A-90.00 92.99% C+ 77.00 79.99% D 60.00 66.99% B+ 87.00 89.99% C 73.00 76.99% F <59.99
miss some assignments and classes are built into the course and should cover most circumstances, but if you have an unexpected situation or assignment extensions are part of your accommodations, contact me as soon as possible to

Qwen zero-shot F1: 18.48837820034529
Qwen 2-shot F1: 18.93380317716979

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 19: CONDITION R5 — GEMMA-2B LoRA
# CORRECTED CONTEXT PIPELINE
# ═══════════════════════════════════════════════════════════

import gc
import math
import time
import inspect
import torch
import transformers
import trl

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments
)

from peft import (
    LoraConfig,
    get_peft_model,
    TaskType
)

from trl import SFTTrainer

print("=" * 60)
print("CONDITION R5: Gemma-2B LoRA Fine-Tuning")
print("Corrected syllabus-context pipeline")
print("Base model: bfloat16 full precision")
print("=" * 60)

# ------------------------------------------------------------
# 1. Clean GPU
# ------------------------------------------------------------

gc.collect()
torch.cuda.empty_cache()

set_seed(SEED)

print("\nEnvironment:")
print("GPU:", torch.cuda.get_device_name(0))
print("Transformers:", transformers.__version__)
print("TRL:", trl.__version__)

BF16_OK = torch.cuda.is_bf16_supported()

TRAIN_DTYPE = (
    torch.bfloat16
    if BF16_OK
    else torch.float16
)

print("BF16 supported:", BF16_OK)
print("Training dtype:", TRAIN_DTYPE)

# ------------------------------------------------------------
# 2. Tokenizer
# ------------------------------------------------------------

print("\nLoading Gemma-2B tokenizer...")

tok_r5 = AutoTokenizer.from_pretrained(
    MODEL_ID
)

if tok_r5.pad_token is None:
    tok_r5.pad_token = tok_r5.eos_token

tok_r5.padding_side = "right"

# ------------------------------------------------------------
# 3. Base model
# ------------------------------------------------------------

print("Loading Gemma-2B...")

model_r5 = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=TRAIN_DTYPE
)

print("Moving Gemma to GPU...")

model_r5 = model_r5.to("cuda")

model_r5.config.pad_token_id = (
    tok_r5.pad_token_id
)

model_r5.config.use_cache = False

print(
    "Gemma device:",
    next(model_r5.parameters()).device
)

# ------------------------------------------------------------
# 4. LoRA
# ------------------------------------------------------------

print("\nConfiguring LoRA adapters...")

lora_config_r5 = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=LORA_TARGET_MODULES,
    task_type=TaskType.CAUSAL_LM,
    bias="none"
)

model_r5 = get_peft_model(
    model_r5,
    lora_config_r5
)

# Fix retained from previous working Gemma implementation
model_r5.enable_input_require_grads()

model_r5.gradient_checkpointing_enable(
    gradient_checkpointing_kwargs={
        "use_reentrant": False
    }
)

model_r5.print_trainable_parameters()

trainable_params = sum(
    p.numel()
    for p in model_r5.parameters()
    if p.requires_grad
)

total_params = sum(
    p.numel()
    for p in model_r5.parameters()
)

trainable_pct = (
    100
    * trainable_params
    / total_params
)

print(
    f"\nTrainable parameters:   "
    f"{trainable_params:,}"
)

print(
    f"Total parameters:       "
    f"{total_params:,}"
)

print(
    f"Trainable percentage:   "
    f"{trainable_pct:.4f}%"
)

assert trainable_params > 0, (
    "No LoRA parameters are trainable."
)

# ------------------------------------------------------------
# 5. Convert original 3% warmup ratio to warmup steps
# ------------------------------------------------------------

steps_per_epoch = math.ceil(
    len(train_data)
    / BATCH_SIZE
    / GRAD_ACCUM
)

total_training_steps = (
    steps_per_epoch
    * NUM_EPOCHS
)

warmup_steps = math.ceil(
    total_training_steps
    * WARMUP_RATIO
)

print("\nTraining schedule:")
print(
    f"Steps per epoch:       "
    f"{steps_per_epoch}"
)
print(
    f"Total optimizer steps: "
    f"{total_training_steps}"
)
print(
    f"Original warmup ratio: "
    f"{WARMUP_RATIO}"
)
print(
    f"Equivalent warmup steps: "
    f"{warmup_steps}"
)

# ------------------------------------------------------------
# 6. TrainingArguments compatibility
# ------------------------------------------------------------

training_parameters = (
    inspect.signature(
        TrainingArguments.__init__
    ).parameters
)

if "eval_strategy" in training_parameters:
    eval_argument_name = "eval_strategy"

elif "evaluation_strategy" in training_parameters:
    eval_argument_name = "evaluation_strategy"

else:
    eval_argument_name = None

R5_CHECKPOINT_DIR = (
    f"{CHECKPOINT_DIR}/"
    f"R5_gemma2b_lora_CONTEXT"
)

training_kwargs = {
    "output_dir":
        R5_CHECKPOINT_DIR,

    "num_train_epochs":
        NUM_EPOCHS,

    "per_device_train_batch_size":
        BATCH_SIZE,

    "per_device_eval_batch_size":
        1,

    "gradient_accumulation_steps":
        GRAD_ACCUM,

    "learning_rate":
        LEARNING_RATE,

    "lr_scheduler_type":
        "cosine",

    "warmup_steps":
        warmup_steps,

    "bf16":
        BF16_OK,

    "fp16":
        not BF16_OK,

    "logging_steps":
        50,

    "save_strategy":
        "epoch",

    "save_total_limit":
        2,

    "load_best_model_at_end":
        True,

    "metric_for_best_model":
        "eval_loss",

    "greater_is_better":
        False,

    "gradient_checkpointing":
        True,

    "gradient_checkpointing_kwargs": {
        "use_reentrant": False
    },

    "optim":
        "paged_adamw_8bit",

    "seed":
        SEED,

    "data_seed":
        SEED,

    "report_to":
        "none"
}

if eval_argument_name is not None:
    training_kwargs[
        eval_argument_name
    ] = "epoch"

train_args_r5 = TrainingArguments(
    **training_kwargs
)

print(
    "\nTrainingArguments created successfully."
)

# ------------------------------------------------------------
# 7. SFTTrainer compatibility
# ------------------------------------------------------------

sft_parameters = (
    inspect.signature(
        SFTTrainer.__init__
    ).parameters
)

trainer_kwargs = {
    "model":
        model_r5,

    "args":
        train_args_r5,

    "train_dataset":
        train_data,

    "eval_dataset":
        val_data
}

if "processing_class" in sft_parameters:
    trainer_kwargs[
        "processing_class"
    ] = tok_r5

elif "tokenizer" in sft_parameters:
    trainer_kwargs[
        "tokenizer"
    ] = tok_r5

if "dataset_text_field" in sft_parameters:
    trainer_kwargs[
        "dataset_text_field"
    ] = "text"

if "max_seq_length" in sft_parameters:
    trainer_kwargs[
        "max_seq_length"
    ] = MAX_SEQ_LENGTH

if "packing" in sft_parameters:
    trainer_kwargs[
        "packing"
    ] = False

trainer_r5 = SFTTrainer(
    **trainer_kwargs
)

print(
    "Trainer created successfully."
)

# ------------------------------------------------------------
# 8. Same descriptive output as previous implementation
# ------------------------------------------------------------

print("\nStarting LoRA training...")

print(
    f"Training examples:  "
    f"{len(train_data):,}"
)

print(
    f"Validation examples:"
    f" {len(val_data):,}"
)

print(
    f"Epochs:             "
    f"{NUM_EPOCHS}"
)

print(
    f"Effective batch:    "
    f"{EFFECTIVE_BATCH}"
)

# ------------------------------------------------------------
# 9. Training
# ------------------------------------------------------------

torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

lora_train_start = (
    time.perf_counter()
)

trainer_r5.train()

torch.cuda.synchronize()

lora_train_seconds = (
    time.perf_counter()
    - lora_train_start
)

lora_train_mins = (
    lora_train_seconds / 60
)

lora_peak_train_vram = (
    torch.cuda.max_memory_allocated()
    / 1024**3
)

print(
    f"\nTraining complete: "
    f"{lora_train_mins:.2f} minutes"
)

print(
    f"Peak training VRAM: "
    f"{lora_peak_train_vram:.2f} GB"
)

# ------------------------------------------------------------
# 10. Save adapter
# ------------------------------------------------------------

lora_path = (
    f"{ADAPTER_DIR}/"
    f"R5_gemma2b_lora_CONTEXT"
)

model_r5.save_pretrained(
    lora_path
)

tok_r5.save_pretrained(
    lora_path
)

print(
    f"LoRA adapter saved to: "
    f"{lora_path}"
)

============================================================
CONDITION R5: Gemma-2B LoRA Fine-Tuning
Corrected syllabus-context pipeline
Base model: bfloat16 full precision
============================================================

Environment:
GPU: NVIDIA A100-SXM4-40GB
Transformers: 5.16.1
TRL: 0.9.6
BF16 supported: True
Training dtype: torch.bfloat16

Loading Gemma-2B tokenizer...
Loading Gemma-2B...

Loading weights:   0%|          | 0/164 [00:00<?, ?it/s]

Moving Gemma to GPU...
Gemma device: cuda:0

Configuring LoRA adapters...
trainable params: 3,686,400 || all params: 2,509,858,816 || trainable%: 0.1469

Trainable parameters:   3,686,400
Total parameters:       2,509,858,816
Trainable percentage:   0.1469%

Training schedule:
Steps per epoch:       189
Total optimizer steps: 567
Original warmup ratio: 0.03
Equivalent warmup steps: 18

TrainingArguments created successfully.

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_deprecation.py:100: FutureWarning: Deprecated argument(s) used in '__init__': dataset_text_field, max_seq_length. Will not be supported from version '1.0.0'.

Deprecated positional argument(s) used in SFTTrainer, please use the SFTConfig to set these arguments instead.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.13/dist-packages/trl/trainer/sft_trainer.py:280: UserWarning: You passed a `max_seq_length` argument to the SFTTrainer, the value you passed will override the one in the `SFTConfig`.
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/trl/trainer/sft_trainer.py:318: UserWarning: You passed a `dataset_text_field` argument to the SFTTrainer, the value you passed will override the one in the `SFTConfig`.
  warnings.warn(

Map:   0%|          | 0/3018 [00:00<?, ? examples/s]

Map:   0%|          | 0/957 [00:00<?, ? examples/s]

TypeError: Trainer.__init__() got an unexpected keyword argument 'tokenizer'

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 19B: CONTINUE GEMMA LoRA TRAINING
# Fixes TRL/Transformers SFTTrainer incompatibility
# DOES NOT reload Gemma or reattach LoRA
# ═══════════════════════════════════════════════════════════

import time
import torch

from transformers import (
    Trainer,
    DataCollatorForLanguageModeling
)

print("=" * 65)
print("CELL 19B — CONTINUING GEMMA-2B LoRA TRAINING")
print("Using standard Hugging Face Trainer")
print("=" * 65)

# ------------------------------------------------------------
# 1. Tokenize corrected context-aware training data
# ------------------------------------------------------------

def tokenize_training_batch(batch):

    return tok_r5(
        batch["text"],
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
        padding=False
    )


print("\nTokenizing corrected training dataset...")

train_tokenized = train_data.map(
    tokenize_training_batch,
    batched=True,
    remove_columns=train_data.column_names
)

print("Tokenizing corrected validation dataset...")

val_tokenized = val_data.map(
    tokenize_training_batch,
    batched=True,
    remove_columns=val_data.column_names
)

print("\nTokenized datasets:")
print(f"Train:      {len(train_tokenized):,}")
print(f"Validation: {len(val_tokenized):,}")

# ------------------------------------------------------------
# 2. Causal language-model data collator
# Creates labels from input_ids automatically
# ------------------------------------------------------------

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tok_r5,
    mlm=False
)

# ------------------------------------------------------------
# 3. Create standard Trainer
# No tokenizer= argument is passed
# ------------------------------------------------------------

trainer_r5 = Trainer(
    model=model_r5,
    args=train_args_r5,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=data_collator
)

print("\n✓ Trainer created successfully.")

print("\nTraining configuration:")
print(f"Training examples:   {len(train_tokenized):,}")
print(f"Validation examples: {len(val_tokenized):,}")
print(f"Epochs:              {NUM_EPOCHS}")
print(f"Batch size:          {BATCH_SIZE}")
print(f"Gradient accumulation: {GRAD_ACCUM}")
print(f"Effective batch:     {EFFECTIVE_BATCH}")
print(f"Learning rate:       {LEARNING_RATE}")
print(f"Max sequence length: {MAX_SEQ_LENGTH}")

# ------------------------------------------------------------
# 4. Measure training resources
# ------------------------------------------------------------

torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

lora_train_start = time.perf_counter()

print("\nStarting corrected Gemma-2B LoRA training...\n")

trainer_r5.train()

torch.cuda.synchronize()

# ------------------------------------------------------------
# 5. Training time
# ------------------------------------------------------------

lora_train_seconds = (
    time.perf_counter()
    - lora_train_start
)

lora_train_mins = (
    lora_train_seconds / 60
)

# ------------------------------------------------------------
# 6. Peak training VRAM
# ------------------------------------------------------------

lora_peak_train_vram = (
    torch.cuda.max_memory_allocated()
    / 1024**3
)

print("\n" + "=" * 55)
print("GEMMA-2B LoRA TRAINING COMPLETE")
print("=" * 55)

print(
    f"Training time: "
    f"{lora_train_mins:.2f} minutes"
)

print(
    f"Peak training VRAM: "
    f"{lora_peak_train_vram:.2f} GB"
)

# ------------------------------------------------------------
# 7. Save corrected adapter
# ------------------------------------------------------------

R5_ADAPTER_PATH = (
    f"{ADAPTER_DIR}/"
    f"R5_gemma2b_lora_CONTEXT"
)

model_r5.save_pretrained(
    R5_ADAPTER_PATH
)

tok_r5.save_pretrained(
    R5_ADAPTER_PATH
)

print("\nLoRA adapter saved to:")
print(R5_ADAPTER_PATH)

print("\n✓ Ready for Cell 20 evaluation.")

=================================================================
CELL 19B — CONTINUING GEMMA-2B LoRA TRAINING
Using standard Hugging Face Trainer
=================================================================

Tokenizing corrected training dataset...

Map:   0%|          | 0/3018 [00:00<?, ? examples/s]

Tokenizing corrected validation dataset...

Map:   0%|          | 0/957 [00:00<?, ? examples/s]

Tokenized datasets:
Train:      3,018
Validation: 957

✓ Trainer created successfully.

Training configuration:
Training examples:   3,018
Validation examples: 957
Epochs:              3
Batch size:          4
Gradient accumulation: 4
Effective batch:     16
Learning rate:       0.0002
Max sequence length: 512

Starting corrected Gemma-2B LoRA training...

=======================================================
GEMMA-2B LoRA TRAINING COMPLETE
=======================================================
Training time: 11.34 minutes
Peak training VRAM: 10.74 GB

LoRA adapter saved to:
/content/drive/MyDrive/MR603_Thesis/adapters/R5_gemma2b_lora_CONTEXT

✓ Ready for Cell 20 evaluation.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 20: EVALUATE GEMMA-2B LoRA + CORRECTED CONTEXT
# Compatible with standard Hugging Face Trainer from Cell 19B
# ═══════════════════════════════════════════════════════════

import json

print("=" * 65)
print("EVALUATING R5: GEMMA-2B LoRA + CONTEXT")
print("=" * 65)

# Enable cache again for inference
model_r5.config.use_cache = True
model_r5.eval()

# ------------------------------------------------------------
# Full test evaluation
# ------------------------------------------------------------

results_r5 = run_evaluation(
    model=model_r5,
    tokenizer=tok_r5,
    test_data=test_data,
    references=references,
    condition_name="R5_Gemma2B_LoRA_CONTEXT"
)

# ------------------------------------------------------------
# Metadata
# ------------------------------------------------------------

results_r5["model"] = "Gemma-2B"
results_r5["method"] = "LoRA"
results_r5["parameters"] = "2B"

results_r5["precision"] = (
    "bfloat16"
    if torch.cuda.is_bf16_supported()
    else "float16"
)

results_r5["context_mode"] = (
    "BM25-retrieved syllabus context"
)

results_r5["training_time_minutes"] = (
    lora_train_mins
)

results_r5["peak_training_vram_gb"] = (
    lora_peak_train_vram
)

results_r5["trainable_parameters"] = (
    trainable_params
)

results_r5["trainable_percentage"] = (
    trainable_pct
)

# Accuracy was only an alias of EM
results_r5.pop("accuracy", None)

# ------------------------------------------------------------
# Stratified analysis
# Uses your actual Cell 11 function
# ------------------------------------------------------------

print("\nRunning question-type stratified analysis...")

strat_r5 = stratified_analysis(
    predictions=results_r5["predictions"],
    test_raw=dataset["test"],
    condition_name="R5_Gemma2B_LoRA_CONTEXT"
)

results_r5["stratified"] = strat_r5

# Keep compatibility with your previous notebook naming
results_r5["stratified_em"] = strat_r5

# ------------------------------------------------------------
# Save summary JSON
# ------------------------------------------------------------

save_r5 = {
    k: v
    for k, v in results_r5.items()
    if k not in [
        "predictions",
        "latencies"
    ]
}

R5_RESULT_PATH = (
    f"{RESULTS_DIR}/"
    f"R5_gemma2b_lora_CONTEXT.json"
)

with open(R5_RESULT_PATH, "w") as f:
    json.dump(
        save_r5,
        f,
        indent=2
    )

# ------------------------------------------------------------
# Save predictions
# ------------------------------------------------------------

R5_PRED_PATH = (
    f"{RESULTS_DIR}/"
    f"R5_gemma2b_lora_CONTEXT_predictions.jsonl"
)

with open(
    R5_PRED_PATH,
    "w",
    encoding="utf-8"
) as f:

    for i, prediction in enumerate(
        results_r5["predictions"]
    ):

        raw = dataset["test"][i]

        row = {
            "id": str(i),
            "syllabus_name": raw["syllabus_name"],
            "question_type": raw["question_type"],
            "question": raw["question"],
            "reference_answer": get_answer(raw),
            "prediction": prediction
        }

        f.write(
            json.dumps(
                row,
                ensure_ascii=False
            ) + "\n"
        )

# ------------------------------------------------------------
# Display results
# ------------------------------------------------------------

print("\n" + "=" * 55)
print("GEMMA-2B LoRA CORRECTED RESULTS")
print("=" * 55)

print(
    f"Exact Match:        "
    f"{results_r5['em']:.3f}%"
)

print(
    f"F1 Score:           "
    f"{results_r5['f1']:.3f}%"
)

print(
    f"Avg Latency:        "
    f"{results_r5['avg_latency_ms']:.3f} ms/sample"
)

print(
    f"Peak Eval VRAM:     "
    f"{results_r5['peak_vram_gb']:.3f} GB"
)

print(
    f"Training Time:      "
    f"{lora_train_mins:.2f} min"
)

print(
    f"Peak Training VRAM: "
    f"{lora_peak_train_vram:.3f} GB"
)

print("\nResults saved to:")
print(R5_RESULT_PATH)

print("\nPredictions saved to:")
print(R5_PRED_PATH)

=================================================================
EVALUATING R5: GEMMA-2B LoRA + CONTEXT
=================================================================

=======================================================
EVALUATING: R5_Gemma2B_LoRA_CONTEXT
=======================================================
Test examples: 1,103
Progress logged every 100 examples
     0/1103 | 0.0 min | 0 ms/sample
   100/1103 | 4.0 min | 2415 ms/sample
   200/1103 | 8.0 min | 2405 ms/sample
   300/1103 | 12.1 min | 2420 ms/sample
   400/1103 | 16.1 min | 2421 ms/sample
   500/1103 | 20.1 min | 2416 ms/sample
   600/1103 | 24.1 min | 2412 ms/sample
   700/1103 | 28.1 min | 2406 ms/sample
   800/1103 | 32.0 min | 2403 ms/sample
   900/1103 | 36.1 min | 2405 ms/sample
  1000/1103 | 40.1 min | 2408 ms/sample
  1100/1103 | 44.2 min | 2410 ms/sample

─────────────────────────────────────────────
RESULTS: R5_Gemma2B_LoRA_CONTEXT
─────────────────────────────────────────────
Exact Match:    0.000%
F1 Score:       17.309%
Accuracy:       0.000%
Avg Latency:    2410.089 ms/sample
Peak GPU VRAM:  5.121 GB

Running question-type stratified analysis...

Running stratified analysis: R5_Gemma2B_LoRA_CONTEXT

Question Type             EM %     F1 %     n
──────────────────────────────────────────────────
multi factual                0.000   27.368   158
multi reasoning              0.000   24.892   158
no answer                    0.000    2.811   155
single factual               0.000   15.743   158
single reasoning             0.000   21.509   158
summarization                0.000   25.771   158
yes/no                       0.000    2.796   158

=======================================================
GEMMA-2B LoRA CORRECTED RESULTS
=======================================================
Exact Match:        0.000%
F1 Score:           17.309%
Avg Latency:        2410.089 ms/sample
Peak Eval VRAM:     5.121 GB
Training Time:      11.34 min
Peak Training VRAM: 10.737 GB

Results saved to:
/content/drive/MyDrive/MR603_Thesis/results/R5_gemma2b_lora_CONTEXT.json

Predictions saved to:
/content/drive/MyDrive/MR603_Thesis/results/R5_gemma2b_lora_CONTEXT_predictions.jsonl

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 21: RQ1 COMPARISON
# Gemma-2B LoRA vs corrected Qwen references
# ═══════════════════════════════════════════════════════════

print("=" * 60)
print("RQ1 CHECK: GEMMA-2B LoRA VS QWEN2.5-14B")
print("=" * 60)

print(
    f"Qwen2.5-14B Zero-Shot + Context F1: "
    f"{QWEN_ZERO_F1:.3f}%"
)

if "QWEN_FEW_F1" in globals():

    print(
        f"Qwen2.5-14B 2-Shot + Context F1:    "
        f"{QWEN_FEW_F1:.3f}%"
    )

print(
    f"Gemma-2B LoRA + Context F1:          "
    f"{results_r5['f1']:.3f}%"
)

gap_zero = (
    results_r5["f1"]
    - QWEN_ZERO_F1
)

print(
    f"\nGap to Qwen zero-shot: "
    f"{gap_zero:+.3f} percentage points"
)

if "QWEN_FEW_F1" in globals():

    gap_few = (
        results_r5["f1"]
        - QWEN_FEW_F1
    )

    print(
        f"Gap to Qwen 2-shot:    "
        f"{gap_few:+.3f} percentage points"
    )

print("\n" + "─" * 55)

print(
    "Note: Qwen is used as a larger prompting reference, "
    "not an adaptation-matched baseline."
)

============================================================
RQ1 CHECK: GEMMA-2B LoRA VS QWEN2.5-14B
============================================================
Qwen2.5-14B Zero-Shot + Context F1: 18.488%
Qwen2.5-14B 2-Shot + Context F1:    18.934%
Gemma-2B LoRA + Context F1:          17.309%

Gap to Qwen zero-shot: -1.179 percentage points
Gap to Qwen 2-shot:    -1.624 percentage points

───────────────────────────────────────────────────────
Note: Qwen is used as a larger prompting reference, not an adaptation-matched baseline.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 22: GEMMA QUESTION-TYPE PERFORMANCE
# ═══════════════════════════════════════════════════════════

import pandas as pd

print("=" * 70)
print("GEMMA-2B LoRA — QUESTION-TYPE PERFORMANCE")
print("=" * 70)

rows = []

for q_type in sorted(
    strat_r5.keys()
):

    values = strat_r5[
        q_type
    ]

    rows.append({
        "Question_Type":
            q_type,

        "N":
            values["count"],

        "EM_percent":
            values["exact_match"],

        "F1_percent":
            values["f1"]
    })

gemma_question_type_df = (
    pd.DataFrame(rows)
)

display(
    gemma_question_type_df.round(3)
)

QUESTION_TYPE_PATH = (
    f"{RESULTS_DIR}/"
    f"Gemma2B_LoRA_CONTEXT_QuestionType_Results.csv"
)

gemma_question_type_df.to_csv(
    QUESTION_TYPE_PATH,
    index=False
)

print("\nSaved:")
print(QUESTION_TYPE_PATH)

======================================================================
GEMMA-2B LoRA — QUESTION-TYPE PERFORMANCE
======================================================================

      Question_Type    N  EM_percent  F1_percent
0     multi factual  158         0.0      27.368
1   multi reasoning  158         0.0      24.892
2         no answer  155         0.0       2.811
3    single factual  158         0.0      15.743
4  single reasoning  158         0.0      21.509
5     summarization  158         0.0      25.771
6            yes/no  158         0.0       2.796

Saved:
/content/drive/MyDrive/MR603_Thesis/results/Gemma2B_LoRA_CONTEXT_QuestionType_Results.csv

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 23: FINAL CLEAN CORRECTED GEMMA RESULTS
# ═══════════════════════════════════════════════════════════

import pandas as pd

final_row = {
    "Condition":
        "R5_Gemma2B_LoRA_CONTEXT",

    "Model":
        "Gemma-2B",

    "Method":
        "LoRA",

    "Parameters_B":
        2.0,

    "Base_Precision":
        results_r5["precision"],

    "Context_Mode":
        "BM25-retrieved syllabus context",

    "EM_percent":
        results_r5["em"],

    "F1_percent":
        results_r5["f1"],

    "Training_Time_min":
        lora_train_mins,

    "Avg_Latency_ms":
        results_r5["avg_latency_ms"],

    "Peak_Eval_VRAM_GB":
        results_r5["peak_vram_gb"],

    "Peak_Train_VRAM_GB":
        lora_peak_train_vram,

    "Trainable_Params":
        trainable_params,

    "Trainable_Pct":
        trainable_pct,

    "Gap_to_Qwen_ZeroShot_F1_pp":
        results_r5["f1"]
        - QWEN_ZERO_F1
}

if "QWEN_FEW_F1" in globals():

    final_row[
        "Gap_to_Qwen_2Shot_F1_pp"
    ] = (
        results_r5["f1"]
        - QWEN_FEW_F1
    )

gemma_final = pd.DataFrame(
    [final_row]
)

FINAL_RESULT_PATH = (
    f"{RESULTS_DIR}/"
    f"Gemma2B_LoRA_CONTEXT_Final_Results.csv"
)

gemma_final.to_csv(
    FINAL_RESULT_PATH,
    index=False
)

display(
    gemma_final.round(3)
)

print("\nSaved:")
print(FINAL_RESULT_PATH)

,Condition,Model,Method,Parameters_B,Base_Precision,Context_Mode,EM_percent,F1_percent,Training_Time_min,Avg_Latency_ms,Peak_Eval_VRAM_GB,Peak_Train_VRAM_GB,Trainable_Params,Trainable_Pct,Gap_to_Qwen_ZeroShot_F1_pp,Gap_to_Qwen_2Shot_F1_pp
0,R5_Gemma2B_LoRA_CONTEXT,Gemma-2B,LoRA,2.0,bfloat16,BM25-retrieved syllabus context,0.0,17.309,11.342,2410.089,5.121,10.737,3686400,0.147,-1.179,-1.624

Saved:
/content/drive/MyDrive/MR603_Thesis/results/Gemma2B_LoRA_CONTEXT_Final_Results.csv

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 24: FINAL FILE CHECK + GPU CLEANUP
# ═══════════════════════════════════════════════════════════

import os
import gc
import torch

required_files = [
    "REF_qwen14b_zeroshot_CONTEXT.json",
    "R5_gemma2b_lora_CONTEXT.json",
    "R5_gemma2b_lora_CONTEXT_predictions.jsonl",
    "Gemma2B_LoRA_CONTEXT_QuestionType_Results.csv",
    "Gemma2B_LoRA_CONTEXT_Final_Results.csv"
]

# Add few-shot files only if that experiment exists
if "QWEN_FEW_F1" in globals():

    required_files.extend([
        "REF_qwen14b_2shot_CONTEXT.json",
        "Qwen_Context_Prompting_Comparison.json"
    ])

print("=" * 70)
print("NOTEBOOK 1 — FINAL CORRECTED FILE CHECK")
print("=" * 70)

all_good = True

for filename in required_files:

    path = (
        f"{RESULTS_DIR}/{filename}"
    )

    if os.path.exists(path):

        size_kb = (
            os.path.getsize(path)
            / 1024
        )

        print(
            f"FOUND   "
            f"{filename} "
            f"({size_kb:.1f} KB)"
        )

    else:

        print(
            f"MISSING "
            f"{filename}"
        )

        all_good = False

if all_good:

    print(
        "\n✓ NOTEBOOK 1 CORRECTED GEMMA RUN COMPLETE."
    )

else:

    print(
        "\nSome files are missing."
    )

# ------------------------------------------------------------
# Only clear GPU after everything is safely saved
# ------------------------------------------------------------

if "model_r5" in globals():
    del model_r5

if "tok_r5" in globals():
    del tok_r5

if "trainer_r5" in globals():
    del trainer_r5

gc.collect()
torch.cuda.empty_cache()

free_vram = (
    torch.cuda.get_device_properties(0).total_memory
    - torch.cuda.memory_allocated()
) / 1e9

print(
    f"\nMemory cleared. "
    f"{free_vram:.1f} GB VRAM free."
)

print(
    "Ready for corrected Phi-3-mini QLoRA."
)

======================================================================
NOTEBOOK 1 — FINAL CORRECTED FILE CHECK
======================================================================
FOUND   REF_qwen14b_zeroshot_CONTEXT.json (1.1 KB)
FOUND   R5_gemma2b_lora_CONTEXT.json (2.0 KB)
FOUND   R5_gemma2b_lora_CONTEXT_predictions.jsonl (641.3 KB)
FOUND   Gemma2B_LoRA_CONTEXT_QuestionType_Results.csv (0.3 KB)
FOUND   Gemma2B_LoRA_CONTEXT_Final_Results.csv (0.5 KB)
FOUND   REF_qwen14b_2shot_CONTEXT.json (1.5 KB)
FOUND   Qwen_Context_Prompting_Comparison.json (0.4 KB)

✓ NOTEBOOK 1 CORRECTED GEMMA RUN COMPLETE.

Memory cleared. 37.4 GB VRAM free.
Ready for corrected Phi-3-mini QLoRA.

In [8]:
# ============================================================
# RECOVER CORRECTED DATASETS AFTER SESSION DISCONNECT
# ============================================================

from datasets import load_from_disk

RECOVERY_DIR = f"{BASE_DIR}/recovery_gemma_context"

corrected_data = load_from_disk(
    f"{RECOVERY_DIR}/corrected_data"
)

train_data = corrected_data["train"]
val_data = corrected_data["validation"]
test_data = corrected_data["test"]

dataset = load_from_disk(
    f"{RECOVERY_DIR}/raw_dataset"
)

print("Corrected datasets restored:")
print("Train:", len(train_data))
print("Validation:", len(val_data))
print("Test:", len(test_data))
print("Raw test:", len(dataset["test"]))

print("\nSample corrected test prompt:")
print(test_data[0]["prompt"][:700])

Corrected datasets restored:
Train: 3018
Validation: 957
Test: 1103
Raw test: 1103

Sample corrected test prompt:
Syllabus context:
Extra Credit: Four extra credit opportunities will be available during the semester. Three of these are exam reflections and the fourth is the end-of-course survey. Each one has a maximum value of 0.3 percentage points towards your final grade. Additional details will be provided as each assignment becomes available. Final Grading Scale: Final grades are rounded to the tenth and then assigned according to this scale. A 93.00 100.00% B-80.00 82.99% D+ 67.00 69.99% A-90.00 92.99% C+ 77.00 79.99% D 60.00 66.99% B+ 87.00 89.99% C 73.00 76.99% F <59.99
miss some assignments and classes are built into the course and should cover most circumstances, but if you have an unexpected s

In [9]:
def get_answer(example):
    answer = example.get("answer", "")
    if isinstance(answer, str):
        return answer.strip()
    return str(answer).strip()

print("get_answer() ready.")

get_answer() ready.

In [14]:
# ============================================================
# RECOVER QWEN + COMPLETED GEMMA LoRA RESULTS
# ============================================================

import json
import os

print("=" * 65)
print("RECOVERING SAVED RESULTS")
print("=" * 65)

# Qwen zero-shot
with open(
    f"{RESULTS_DIR}/REF_qwen14b_zeroshot_CONTEXT.json",
    "r"
) as f:
    results_qwen_zero = json.load(f)

QWEN_ZERO_EM = results_qwen_zero["em"]
QWEN_ZERO_F1 = results_qwen_zero["f1"]

print(
    f"Qwen zero-shot: "
    f"EM={QWEN_ZERO_EM:.3f}% | "
    f"F1={QWEN_ZERO_F1:.3f}%"
)

# Qwen 2-shot
few_path = f"{RESULTS_DIR}/REF_qwen14b_2shot_CONTEXT.json"

if os.path.exists(few_path):
    with open(few_path, "r") as f:
        results_qwen_few = json.load(f)

    QWEN_FEW_EM = results_qwen_few["em"]
    QWEN_FEW_F1 = results_qwen_few["f1"]

    print(
        f"Qwen 2-shot:   "
        f"EM={QWEN_FEW_EM:.3f}% | "
        f"F1={QWEN_FEW_F1:.3f}%"
    )

# Gemma LoRA
with open(
    f"{RESULTS_DIR}/R5_gemma2b_lora_CONTEXT.json",
    "r"
) as f:
    results_r5 = json.load(f)

print(
    f"Gemma LoRA:    "
    f"EM={results_r5['em']:.3f}% | "
    f"F1={results_r5['f1']:.3f}%"
)

print("\n✓ Previous completed results restored.")

=================================================================
RECOVERING SAVED RESULTS
=================================================================
Qwen zero-shot: EM=0.000% | F1=18.488%
Qwen 2-shot:   EM=0.091% | F1=18.934%
Gemma LoRA:    EM=0.000% | F1=17.309%

✓ Previous completed results restored.

In [16]:
# ============================================================
# DEFINE set_seed() FUNCTION
# Required by QLoRA Cell 25 and preflight
# ============================================================

import random
import numpy as np
import torch
import os

SEED = 42

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

set_seed(SEED)

print("✓ set_seed() function defined.")
print("Seed:", SEED)

✓ set_seed() function defined.
Seed: 42

In [17]:
# ═══════════════════════════════════════════════════════════
# PRE-QLORA PREFLIGHT CHECK
# Run this immediately before corrected Cell 25
# ═══════════════════════════════════════════════════════════

import os
import json
import torch
import importlib.metadata

print("=" * 70)
print("PRE-QLORA PREFLIGHT CHECK")
print("=" * 70)

# 1. GPU
assert torch.cuda.is_available(), "ERROR: GPU is not enabled."

print("GPU:", torch.cuda.get_device_name(0))

free_vram = (
    torch.cuda.get_device_properties(0).total_memory
    - torch.cuda.memory_allocated()
) / 1024**3

print(f"Free VRAM: {free_vram:.2f} GB")

# 2. Required variables/functions
required_names = [
    "BASE_DIR",
    "RESULTS_DIR",
    "ADAPTER_DIR",
    "CHECKPOINT_DIR",
    "MODEL_ID",
    "SEED",
    "LORA_R",
    "LORA_ALPHA",
    "LORA_DROPOUT",
    "LORA_TARGET_MODULES",
    "LEARNING_RATE",
    "NUM_EPOCHS",
    "BATCH_SIZE",
    "GRAD_ACCUM",
    "EFFECTIVE_BATCH",
    "MAX_SEQ_LENGTH",
    "WARMUP_RATIO",
    "MAX_NEW_TOKENS",
    "train_data",
    "val_data",
    "test_data",
    "dataset",
    "references",
    "run_evaluation",
    "stratified_analysis",
    "get_answer",
    "set_seed"
]

missing = [
    name for name in required_names
    if name not in globals()
]

assert not missing, (
    f"ERROR: Missing runtime objects: {missing}"
)

print("✓ Required runtime variables/functions exist.")

# 3. Dataset sizes
assert len(train_data) == 3018
assert len(val_data) == 957
assert len(test_data) == 1103
assert len(dataset["test"]) == 1103
assert len(references) == 1103

print(
    f"✓ Dataset sizes correct: "
    f"{len(train_data)}/{len(val_data)}/{len(test_data)}"
)

# 4. Confirm corrected context is present
assert "Syllabus context:" in train_data[0]["text"]
assert "Syllabus context:" in test_data[0]["prompt"]

assert "Syllabus context:\n\n" not in train_data[0]["text"]
assert "Syllabus context:\n\n" not in test_data[0]["prompt"]

print("✓ Corrected syllabus context confirmed.")

# 5. Restore LoRA result if Cell 24 removed model/runtime objects
r5_path = (
    f"{RESULTS_DIR}/"
    f"R5_gemma2b_lora_CONTEXT.json"
)

assert os.path.exists(r5_path), (
    "ERROR: Corrected LoRA result JSON not found."
)

with open(r5_path, "r") as f:
    results_r5 = json.load(f)

print(
    f"✓ Corrected LoRA result loaded. "
    f"F1 = {results_r5['f1']:.3f}%"
)

# 6. Restore Qwen zero-shot
zero_path = (
    f"{RESULTS_DIR}/"
    f"REF_qwen14b_zeroshot_CONTEXT.json"
)

assert os.path.exists(zero_path), (
    "ERROR: Qwen zero-shot result not found."
)

with open(zero_path, "r") as f:
    results_qwen_zero = json.load(f)

QWEN_ZERO_EM = results_qwen_zero["em"]
QWEN_ZERO_F1 = results_qwen_zero["f1"]

print(
    f"✓ Qwen zero-shot restored. "
    f"F1 = {QWEN_ZERO_F1:.3f}%"
)

# 7. Restore Qwen 2-shot
few_path = (
    f"{RESULTS_DIR}/"
    f"REF_qwen14b_2shot_CONTEXT.json"
)

if os.path.exists(few_path):

    with open(few_path, "r") as f:
        results_qwen_few = json.load(f)

    QWEN_FEW_EM = results_qwen_few["em"]
    QWEN_FEW_F1 = results_qwen_few["f1"]

    print(
        f"✓ Qwen 2-shot restored. "
        f"F1 = {QWEN_FEW_F1:.3f}%"
    )

else:
    print("WARNING: Qwen 2-shot file not found.")

# 8. Check packages required for QLoRA
import transformers
import accelerate
import peft
import bitsandbytes

print("\nPackage versions:")
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)
print("PEFT:", peft.__version__)
print("BitsAndBytes:", bitsandbytes.__version__)

# 9. Critical Accelerate detection check
from transformers.utils import is_accelerate_available

assert is_accelerate_available(), (
    "ERROR: Transformers does not detect Accelerate."
)

print("✓ Transformers detects Accelerate.")

# 10. Confirm 4-bit support class imports
from transformers import BitsAndBytesConfig, Trainer, TrainingArguments
from peft import prepare_model_for_kbit_training

print("✓ QLoRA dependencies import successfully.")

print("\n" + "=" * 70)
print("ALL PRE-QLORA CHECKS PASSED")
print("GO DIRECTLY TO CORRECTED CELL 25")
print("=" * 70)

======================================================================
PRE-QLORA PREFLIGHT CHECK
======================================================================
GPU: NVIDIA A100-SXM4-40GB
Free VRAM: 39.49 GB
✓ Required runtime variables/functions exist.
✓ Dataset sizes correct: 3018/957/1103
✓ Corrected syllabus context confirmed.
✓ Corrected LoRA result loaded. F1 = 17.309%
✓ Qwen zero-shot restored. F1 = 18.488%
✓ Qwen 2-shot restored. F1 = 18.934%

Package versions:
Transformers: 5.16.1
Accelerate: 1.15.0
PEFT: 0.12.0
BitsAndBytes: 0.50.2
✓ Transformers detects Accelerate.
✓ QLoRA dependencies import successfully.

======================================================================
ALL PRE-QLORA CHECKS PASSED
GO DIRECTLY TO CORRECTED CELL 25
======================================================================

In [18]:
# ═══════════════════════════════════════════════════════════
# CELL 25: R6 — GEMMA-2B QLoRA + CORRECTED CONTEXT
# Standard Hugging Face Trainer
# 4-bit NF4 + double quantisation
# ═══════════════════════════════════════════════════════════

import gc
import math
import time
import inspect
import torch

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
    TaskType
)

print("=" * 70)
print("CONDITION R6: GEMMA-2B QLoRA")
print("Corrected syllabus-context pipeline")
print("Base model: 4-bit NF4 + double quantisation")
print("=" * 70)

# ------------------------------------------------------------
# 1. GPU cleanup
# ------------------------------------------------------------

gc.collect()
torch.cuda.empty_cache()
set_seed(SEED)

assert torch.cuda.is_available(), "GPU is not enabled."

print("\nGPU:", torch.cuda.get_device_name(0))
print("BF16 support:", torch.cuda.is_bf16_supported())

# ------------------------------------------------------------
# 2. Tokenizer
# ------------------------------------------------------------

print("\nLoading tokenizer...")

tok_r6 = AutoTokenizer.from_pretrained(
    MODEL_ID
)

if tok_r6.pad_token is None:
    tok_r6.pad_token = tok_r6.eos_token

tok_r6.padding_side = "right"

# ------------------------------------------------------------
# 3. 4-bit NF4 configuration
# ------------------------------------------------------------

print("Configuring QLoRA 4-bit NF4...")

bnb_config_r6 = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16
)

# ------------------------------------------------------------
# 4. Load quantised Gemma
# ------------------------------------------------------------

print("Loading Gemma-2B in 4-bit...")

model_r6 = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config_r6,
    device_map={"": 0}
)

model_r6.config.pad_token_id = tok_r6.pad_token_id
model_r6.config.use_cache = False

print(
    "Model device:",
    next(model_r6.parameters()).device
)

print(
    f"Allocated VRAM after load: "
    f"{torch.cuda.memory_allocated()/1024**3:.3f} GB"
)

# ------------------------------------------------------------
# 5. Prepare for k-bit training
# ------------------------------------------------------------

print("\nPreparing quantised model for k-bit training...")

model_r6 = prepare_model_for_kbit_training(
    model_r6,
    use_gradient_checkpointing=True
)

# ------------------------------------------------------------
# 6. SAME adapter configuration as LoRA
# ------------------------------------------------------------

qlora_config_r6 = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=LORA_TARGET_MODULES,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

model_r6 = get_peft_model(
    model_r6,
    qlora_config_r6
)

model_r6.print_trainable_parameters()

trainable_q = sum(
    p.numel()
    for p in model_r6.parameters()
    if p.requires_grad
)

total_q = sum(
    p.numel()
    for p in model_r6.parameters()
)

trainable_q_pct = (
    100 * trainable_q / total_q
)

print(f"\nTrainable parameters: {trainable_q:,}")
print(f"Total parameters:     {total_q:,}")
print(f"Trainable percentage: {trainable_q_pct:.4f}%")

assert trainable_q > 0, "No QLoRA parameters are trainable."

# ------------------------------------------------------------
# 7. Tokenize SAME corrected context dataset
# ------------------------------------------------------------

def tokenize_r6(batch):
    return tok_r6(
        batch["text"],
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
        padding=False
    )

print("\nTokenizing corrected training dataset...")

train_tokenized_r6 = train_data.map(
    tokenize_r6,
    batched=True,
    remove_columns=train_data.column_names
)

print("Tokenizing corrected validation dataset...")

val_tokenized_r6 = val_data.map(
    tokenize_r6,
    batched=True,
    remove_columns=val_data.column_names
)

print("\nTokenized datasets:")
print(f"Train:      {len(train_tokenized_r6):,}")
print(f"Validation: {len(val_tokenized_r6):,}")

# ------------------------------------------------------------
# 8. Causal-LM collator
# ------------------------------------------------------------

data_collator_r6 = DataCollatorForLanguageModeling(
    tokenizer=tok_r6,
    mlm=False
)

# ------------------------------------------------------------
# 9. Same warmup design as corrected LoRA
# ------------------------------------------------------------

steps_per_epoch_r6 = math.ceil(
    len(train_tokenized_r6)
    / BATCH_SIZE
    / GRAD_ACCUM
)

total_steps_r6 = (
    steps_per_epoch_r6
    * NUM_EPOCHS
)

warmup_steps_r6 = math.ceil(
    total_steps_r6
    * WARMUP_RATIO
)

print("\nTraining schedule:")
print("Steps per epoch:       ", steps_per_epoch_r6)
print("Total optimizer steps: ", total_steps_r6)
print("Warmup steps:          ", warmup_steps_r6)

# ------------------------------------------------------------
# 10. Handle current Transformers argument naming
# ------------------------------------------------------------

ta_params = inspect.signature(
    TrainingArguments.__init__
).parameters

if "eval_strategy" in ta_params:
    eval_key = "eval_strategy"
elif "evaluation_strategy" in ta_params:
    eval_key = "evaluation_strategy"
else:
    raise RuntimeError(
        "TrainingArguments has no supported evaluation strategy argument."
    )

R6_CHECKPOINT_DIR = (
    f"{CHECKPOINT_DIR}/"
    f"R6_gemma2b_qlora_CONTEXT"
)

training_kwargs_r6 = {
    "output_dir": R6_CHECKPOINT_DIR,
    "num_train_epochs": NUM_EPOCHS,
    "per_device_train_batch_size": BATCH_SIZE,
    "per_device_eval_batch_size": 1,
    "gradient_accumulation_steps": GRAD_ACCUM,
    "learning_rate": LEARNING_RATE,
    "lr_scheduler_type": "cosine",
    "warmup_steps": warmup_steps_r6,
    "bf16": torch.cuda.is_bf16_supported(),
    "fp16": not torch.cuda.is_bf16_supported(),
    "logging_steps": 50,
    "save_strategy": "epoch",
    "save_total_limit": 2,
    "load_best_model_at_end": True,
    "metric_for_best_model": "eval_loss",
    "greater_is_better": False,
    "gradient_checkpointing": True,
    "gradient_checkpointing_kwargs": {
        "use_reentrant": False
    },
    "optim": "paged_adamw_8bit",
    "seed": SEED,
    "data_seed": SEED,
    "report_to": "none"
}

training_kwargs_r6[eval_key] = "epoch"

train_args_r6 = TrainingArguments(
    **training_kwargs_r6
)

print("\n✓ TrainingArguments created.")

# ------------------------------------------------------------
# 11. Standard Trainer
# NO SFTTrainer
# NO tokenizer argument problem
# ------------------------------------------------------------

trainer_r6 = Trainer(
    model=model_r6,
    args=train_args_r6,
    train_dataset=train_tokenized_r6,
    eval_dataset=val_tokenized_r6,
    data_collator=data_collator_r6
)

print("✓ Trainer created successfully.")

# ------------------------------------------------------------
# 12. Train and measure resources
# ------------------------------------------------------------

torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

qlora_train_start = time.perf_counter()

print("\nStarting corrected Gemma-2B QLoRA training...\n")

train_output_r6 = trainer_r6.train()

torch.cuda.synchronize()

qlora_train_seconds = (
    time.perf_counter()
    - qlora_train_start
)

qlora_train_mins = (
    qlora_train_seconds / 60
)

qlora_peak_train_vram = (
    torch.cuda.max_memory_allocated()
    / 1024**3
)

print("\n" + "=" * 60)
print("GEMMA-2B QLoRA TRAINING COMPLETE")
print("=" * 60)

print(
    f"Training time: "
    f"{qlora_train_mins:.2f} minutes"
)

print(
    f"Peak training VRAM: "
    f"{qlora_peak_train_vram:.3f} GB"
)

# ------------------------------------------------------------
# 13. Save adapter
# ------------------------------------------------------------

R6_ADAPTER_PATH = (
    f"{ADAPTER_DIR}/"
    f"R6_gemma2b_qlora_CONTEXT"
)

model_r6.save_pretrained(
    R6_ADAPTER_PATH
)

tok_r6.save_pretrained(
    R6_ADAPTER_PATH
)

print("\nQLoRA adapter saved to:")
print(R6_ADAPTER_PATH)

print("\n✓ Cell 25 complete.")
print("✓ Continue to Cell 26.")

======================================================================
CONDITION R6: GEMMA-2B QLoRA
Corrected syllabus-context pipeline
Base model: 4-bit NF4 + double quantisation
======================================================================

GPU: NVIDIA A100-SXM4-40GB
BF16 support: True

Loading tokenizer...

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/34.2k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.5MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

Configuring QLoRA 4-bit NF4...
Loading Gemma-2B in 4-bit...

model.safetensors.index.json:   0%|          | 0.00/13.5k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/164 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

Model device: cuda:0
Allocated VRAM after load: 1.929 GB

Preparing quantised model for k-bit training...
trainable params: 3,686,400 || all params: 2,509,858,816 || trainable%: 0.1469

Trainable parameters: 3,686,400
Total parameters:     1,518,954,496
Trainable percentage: 0.2427%

Tokenizing corrected training dataset...

Map:   0%|          | 0/3018 [00:00<?, ? examples/s]

Tokenizing corrected validation dataset...

Map:   0%|          | 0/957 [00:00<?, ? examples/s]

Tokenized datasets:
Train:      3,018
Validation: 957

Training schedule:
Steps per epoch:        189
Total optimizer steps:  567
Warmup steps:           18

✓ TrainingArguments created.
✓ Trainer created successfully.

Starting corrected Gemma-2B QLoRA training...

============================================================
GEMMA-2B QLoRA TRAINING COMPLETE
============================================================
Training time: 16.08 minutes
Peak training VRAM: 10.092 GB

QLoRA adapter saved to:
/content/drive/MyDrive/MR603_Thesis/adapters/R6_gemma2b_qlora_CONTEXT

✓ Cell 25 complete.
✓ Continue to Cell 26.

In [19]:
# ═══════════════════════════════════════════════════════════
# CELL 26: EVALUATE R6 — GEMMA-2B QLoRA + CONTEXT
# ═══════════════════════════════════════════════════════════

import json

print("=" * 70)
print("EVALUATING R6: GEMMA-2B QLoRA + CONTEXT")
print("=" * 70)

model_r6.config.use_cache = True
model_r6.eval()

# ------------------------------------------------------------
# Full evaluation
# ------------------------------------------------------------

results_r6 = run_evaluation(
    model=model_r6,
    tokenizer=tok_r6,
    test_data=test_data,
    references=references,
    condition_name="R6_Gemma2B_QLoRA_CONTEXT"
)

# ------------------------------------------------------------
# Metadata
# ------------------------------------------------------------

results_r6["model"] = "Gemma-2B"
results_r6["method"] = "QLoRA"
results_r6["parameters"] = "2B"

results_r6["precision"] = (
    "4-bit NF4 + double quantisation"
)

results_r6["context_mode"] = (
    "BM25-retrieved syllabus context"
)

results_r6["training_time_seconds"] = (
    qlora_train_seconds
)

results_r6["training_time_minutes"] = (
    qlora_train_mins
)

results_r6["peak_training_vram_gb"] = (
    qlora_peak_train_vram
)

results_r6["trainable_parameters"] = (
    trainable_q
)

results_r6["trainable_percentage"] = (
    trainable_q_pct
)

# Accuracy duplicates EM in your original pipeline
results_r6.pop(
    "accuracy",
    None
)

# ------------------------------------------------------------
# Stratified analysis
# ------------------------------------------------------------

print("\nRunning question-type stratified analysis...")

strat_r6 = stratified_analysis(
    predictions=results_r6["predictions"],
    test_raw=dataset["test"],
    condition_name="R6_Gemma2B_QLoRA_CONTEXT"
)

results_r6["stratified"] = strat_r6
results_r6["stratified_em"] = strat_r6

# ------------------------------------------------------------
# Save summary JSON
# ------------------------------------------------------------

save_r6 = {
    k: v
    for k, v in results_r6.items()
    if k not in [
        "predictions",
        "latencies"
    ]
}

R6_RESULT_PATH = (
    f"{RESULTS_DIR}/"
    f"R6_gemma2b_qlora_CONTEXT.json"
)

with open(
    R6_RESULT_PATH,
    "w"
) as f:
    json.dump(
        save_r6,
        f,
        indent=2
    )

# ------------------------------------------------------------
# Save individual predictions
# ------------------------------------------------------------

R6_PRED_PATH = (
    f"{RESULTS_DIR}/"
    f"R6_gemma2b_qlora_CONTEXT_predictions.jsonl"
)

with open(
    R6_PRED_PATH,
    "w",
    encoding="utf-8"
) as f:

    for i, prediction in enumerate(
        results_r6["predictions"]
    ):

        raw = dataset["test"][i]

        row = {
            "id": str(i),
            "syllabus_name": raw["syllabus_name"],
            "question_type": raw["question_type"],
            "question": raw["question"],
            "reference_answer": get_answer(raw),
            "prediction": prediction
        }

        f.write(
            json.dumps(
                row,
                ensure_ascii=False
            ) + "\n"
        )

# ------------------------------------------------------------
# Display same-style results
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("GEMMA-2B QLoRA CORRECTED RESULTS")
print("=" * 60)

print(
    f"Exact Match:        "
    f"{results_r6['em']:.3f}%"
)

print(
    f"F1 Score:           "
    f"{results_r6['f1']:.3f}%"
)

print(
    f"Avg Latency:        "
    f"{results_r6['avg_latency_ms']:.3f} ms/sample"
)

print(
    f"Peak Eval VRAM:     "
    f"{results_r6['peak_vram_gb']:.3f} GB"
)

print(
    f"Training Time:      "
    f"{qlora_train_mins:.2f} min"
)

print(
    f"Peak Training VRAM: "
    f"{qlora_peak_train_vram:.3f} GB"
)

print("\nResults saved:")
print(R6_RESULT_PATH)

print("\nPredictions saved:")
print(R6_PRED_PATH)

======================================================================
EVALUATING R6: GEMMA-2B QLoRA + CONTEXT
======================================================================

=======================================================
EVALUATING: R6_Gemma2B_QLoRA_CONTEXT
=======================================================
Test examples: 1,103
Progress logged every 100 examples
     0/1103 | 0.0 min | 0 ms/sample
   100/1103 | 6.1 min | 3653 ms/sample
   200/1103 | 12.2 min | 3652 ms/sample
   300/1103 | 18.2 min | 3647 ms/sample
   400/1103 | 24.3 min | 3647 ms/sample
   500/1103 | 30.4 min | 3648 ms/sample
   600/1103 | 36.4 min | 3638 ms/sample
   700/1103 | 42.4 min | 3634 ms/sample
   800/1103 | 48.3 min | 3620 ms/sample
   900/1103 | 54.3 min | 3620 ms/sample
  1000/1103 | 60.3 min | 3619 ms/sample
  1100/1103 | 66.4 min | 3619 ms/sample

─────────────────────────────────────────────
RESULTS: R6_Gemma2B_QLoRA_CONTEXT
─────────────────────────────────────────────
Exact Match:    0.000%
F1 Score:       17.263%
Accuracy:       0.000%
Avg Latency:    3619.289 ms/sample
Peak GPU VRAM:  3.321 GB

Running question-type stratified analysis...

Running stratified analysis: R6_Gemma2B_QLoRA_CONTEXT

Question Type             EM %     F1 %     n
──────────────────────────────────────────────────
multi factual                0.000   26.985   158
multi reasoning              0.000   24.800   158
no answer                    0.000    3.098   155
single factual               0.000   16.395   158
single reasoning             0.000   20.876   158
summarization                0.000   25.288   158
yes/no                       0.000    3.126   158

============================================================
GEMMA-2B QLoRA CORRECTED RESULTS
============================================================
Exact Match:        0.000%
F1 Score:           17.263%
Avg Latency:        3619.289 ms/sample
Peak Eval VRAM:     3.321 GB
Training Time:      16.08 min
Peak Training VRAM: 10.092 GB

Results saved:
/content/drive/MyDrive/MR603_Thesis/results/R6_gemma2b_qlora_CONTEXT.json

Predictions saved:
/content/drive/MyDrive/MR603_Thesis/results/R6_gemma2b_qlora_CONTEXT_predictions.jsonl

In [20]:
# ═══════════════════════════════════════════════════════════
# CELL 27: GEMMA-2B COMPARISON
# Corrected LoRA vs corrected QLoRA
# + corrected Qwen references
# ═══════════════════════════════════════════════════════════

print("=" * 72)
print("GEMMA-2B — CORRECTED CONTEXT COMPARISON")
print("=" * 72)

print("\nPERFORMANCE")

print(
    f"LoRA EM:                    "
    f"{results_r5['em']:.3f}%"
)

print(
    f"QLoRA EM:                   "
    f"{results_r6['em']:.3f}%"
)

print(
    f"LoRA F1:                    "
    f"{results_r5['f1']:.3f}%"
)

print(
    f"QLoRA F1:                   "
    f"{results_r6['f1']:.3f}%"
)

print(
    f"LoRA - QLoRA F1:            "
    f"{results_r5['f1'] - results_r6['f1']:+.3f} pp"
)

print(
    f"Qwen zero-shot + context:   "
    f"{QWEN_ZERO_F1:.3f}%"
)

if "QWEN_FEW_F1" in globals():
    print(
        f"Qwen 2-shot + context:      "
        f"{QWEN_FEW_F1:.3f}%"
    )

print("\nGAPS TO QWEN ZERO-SHOT")

print(
    f"LoRA:  "
    f"{results_r5['f1'] - QWEN_ZERO_F1:+.3f} pp"
)

print(
    f"QLoRA: "
    f"{results_r6['f1'] - QWEN_ZERO_F1:+.3f} pp"
)

if "QWEN_FEW_F1" in globals():

    print("\nGAPS TO QWEN 2-SHOT")

    print(
        f"LoRA:  "
        f"{results_r5['f1'] - QWEN_FEW_F1:+.3f} pp"
    )

    print(
        f"QLoRA: "
        f"{results_r6['f1'] - QWEN_FEW_F1:+.3f} pp"
    )

print("\nEFFICIENCY")

print(
    f"LoRA latency:     "
    f"{results_r5['avg_latency_ms']:.3f} ms"
)

print(
    f"QLoRA latency:    "
    f"{results_r6['avg_latency_ms']:.3f} ms"
)

print(
    f"LoRA eval VRAM:   "
    f"{results_r5['peak_vram_gb']:.3f} GB"
)

print(
    f"QLoRA eval VRAM:  "
    f"{results_r6['peak_vram_gb']:.3f} GB"
)

print(
    f"LoRA train time:  "
    f"{results_r5['training_time_minutes']:.2f} min"
)

print(
    f"QLoRA train time: "
    f"{results_r6['training_time_minutes']:.2f} min"
)

print(
    f"LoRA train VRAM:  "
    f"{results_r5['peak_training_vram_gb']:.3f} GB"
)

print(
    f"QLoRA train VRAM: "
    f"{results_r6['peak_training_vram_gb']:.3f} GB"
)

print("\nNote:")
print(
    "Qwen is a larger prompting reference, "
    "not an adaptation-matched baseline."
)

========================================================================
GEMMA-2B — CORRECTED CONTEXT COMPARISON
========================================================================

PERFORMANCE
LoRA EM:                    0.000%
QLoRA EM:                   0.000%
LoRA F1:                    17.309%
QLoRA F1:                   17.263%
LoRA - QLoRA F1:            +0.047 pp
Qwen zero-shot + context:   18.488%
Qwen 2-shot + context:      18.934%

GAPS TO QWEN ZERO-SHOT
LoRA:  -1.179 pp
QLoRA: -1.226 pp

GAPS TO QWEN 2-SHOT
LoRA:  -1.624 pp
QLoRA: -1.671 pp

EFFICIENCY
LoRA latency:     2410.089 ms
QLoRA latency:    3619.289 ms
LoRA eval VRAM:   5.121 GB
QLoRA eval VRAM:  3.321 GB
LoRA train time:  11.34 min
QLoRA train time: 16.08 min
LoRA train VRAM:  10.737 GB
QLoRA train VRAM: 10.092 GB

Note:
Qwen is a larger prompting reference, not an adaptation-matched baseline.

In [21]:
# ═══════════════════════════════════════════════════════════
# CELL 28: RQ2 — LoRA VS QLoRA BY QUESTION TYPE
# Uses both EM and F1
# ═══════════════════════════════════════════════════════════

import pandas as pd

print("=" * 76)
print("RQ2 — GEMMA-2B LoRA VS QLoRA BY QUESTION TYPE")
print("=" * 76)

strat_r5 = results_r5.get(
    "stratified",
    results_r5.get("stratified_em", {})
)

strat_r6 = results_r6.get(
    "stratified",
    results_r6.get("stratified_em", {})
)

rq2_rows = []

for q_type in sorted(strat_r5.keys()):

    if q_type not in strat_r6:
        continue

    l = strat_r5[q_type]
    q = strat_r6[q_type]

    rq2_rows.append({
        "Question_Type": q_type,
        "N": l["count"],
        "LoRA_EM_percent": l["exact_match"],
        "QLoRA_EM_percent": q["exact_match"],
        "Delta_EM_LoRA_minus_QLoRA":
            l["exact_match"] - q["exact_match"],
        "LoRA_F1_percent": l["f1"],
        "QLoRA_F1_percent": q["f1"],
        "Delta_F1_LoRA_minus_QLoRA":
            l["f1"] - q["f1"]
    })

rq2_gemma = pd.DataFrame(
    rq2_rows
)

display(
    rq2_gemma.round(3)
)

RQ2_PATH = (
    f"{RESULTS_DIR}/"
    f"Gemma2B_CONTEXT_RQ2_QuestionType_Results.csv"
)

rq2_gemma.to_csv(
    RQ2_PATH,
    index=False
)

print("\nSaved:")
print(RQ2_PATH)

============================================================================
RQ2 — GEMMA-2B LoRA VS QLoRA BY QUESTION TYPE
============================================================================

,Question_Type,N,LoRA_EM_percent,QLoRA_EM_percent,Delta_EM_LoRA_minus_QLoRA,LoRA_F1_percent,QLoRA_F1_percent,Delta_F1_LoRA_minus_QLoRA
0,multi factual,158,0.0,0.0,0.0,27.368,26.985,0.383
1,multi reasoning,158,0.0,0.0,0.0,24.892,24.800,0.091
2,no answer,155,0.0,0.0,0.0,2.811,3.098,-0.288
3,single factual,158,0.0,0.0,0.0,15.743,16.395,-0.652
4,single reasoning,158,0.0,0.0,0.0,21.509,20.876,0.632
5,summarization,158,0.0,0.0,0.0,25.771,25.288,0.483
6,yes/no,158,0.0,0.0,0.0,2.796,3.126,-0.330

Saved:
/content/drive/MyDrive/MR603_Thesis/results/Gemma2B_CONTEXT_RQ2_QuestionType_Results.csv

In [22]:
# ═══════════════════════════════════════════════════════════
# CELL 29: FINAL GEMMA-2B CORRECTED RESULTS
# LoRA + QLoRA
# ═══════════════════════════════════════════════════════════

import pandas as pd

combined_rows = []

# ------------------------------------------------------------
# LoRA
# ------------------------------------------------------------

lora_row = {
    "Condition":
        "R5_Gemma2B_LoRA_CONTEXT",

    "Model":
        "Gemma-2B",

    "Method":
        "LoRA",

    "Parameters_B":
        2.0,

    "Base_Precision":
        results_r5["precision"],

    "Context_Mode":
        "BM25-retrieved syllabus context",

    "EM_percent":
        results_r5["em"],

    "F1_percent":
        results_r5["f1"],

    "Training_Time_min":
        results_r5["training_time_minutes"],

    "Avg_Latency_ms":
        results_r5["avg_latency_ms"],

    "Peak_Eval_VRAM_GB":
        results_r5["peak_vram_gb"],

    "Peak_Train_VRAM_GB":
        results_r5["peak_training_vram_gb"],

    "Trainable_Params":
        results_r5["trainable_parameters"],

    "Trainable_Pct":
        results_r5["trainable_percentage"],

    "Gap_Qwen_ZeroShot_F1_pp":
        results_r5["f1"]
        - QWEN_ZERO_F1
}

if "QWEN_FEW_F1" in globals():
    lora_row["Gap_Qwen_2Shot_F1_pp"] = (
        results_r5["f1"]
        - QWEN_FEW_F1
    )

combined_rows.append(
    lora_row
)

# ------------------------------------------------------------
# QLoRA
# ------------------------------------------------------------

qlora_row = {
    "Condition":
        "R6_Gemma2B_QLoRA_CONTEXT",

    "Model":
        "Gemma-2B",

    "Method":
        "QLoRA",

    "Parameters_B":
        2.0,

    "Base_Precision":
        "4-bit NF4 + double quantisation",

    "Context_Mode":
        "BM25-retrieved syllabus context",

    "EM_percent":
        results_r6["em"],

    "F1_percent":
        results_r6["f1"],

    "Training_Time_min":
        results_r6["training_time_minutes"],

    "Avg_Latency_ms":
        results_r6["avg_latency_ms"],

    "Peak_Eval_VRAM_GB":
        results_r6["peak_vram_gb"],

    "Peak_Train_VRAM_GB":
        results_r6["peak_training_vram_gb"],

    "Trainable_Params":
        results_r6["trainable_parameters"],

    "Trainable_Pct":
        results_r6["trainable_percentage"],

    "Gap_Qwen_ZeroShot_F1_pp":
        results_r6["f1"]
        - QWEN_ZERO_F1
}

if "QWEN_FEW_F1" in globals():
    qlora_row["Gap_Qwen_2Shot_F1_pp"] = (
        results_r6["f1"]
        - QWEN_FEW_F1
    )

combined_rows.append(
    qlora_row
)

gemma_final = pd.DataFrame(
    combined_rows
)

FINAL_GEMMA_PATH = (
    f"{RESULTS_DIR}/"
    f"Gemma2B_CONTEXT_Final_Results.csv"
)

gemma_final.to_csv(
    FINAL_GEMMA_PATH,
    index=False
)

display(
    gemma_final.round(3)
)

print("\nFinal combined Gemma table saved:")
print(FINAL_GEMMA_PATH)

,Condition,Model,Method,Parameters_B,Base_Precision,Context_Mode,EM_percent,F1_percent,Training_Time_min,Avg_Latency_ms,Peak_Eval_VRAM_GB,Peak_Train_VRAM_GB,Trainable_Params,Trainable_Pct,Gap_Qwen_ZeroShot_F1_pp,Gap_Qwen_2Shot_F1_pp
0,R5_Gemma2B_LoRA_CONTEXT,Gemma-2B,LoRA,2.0,bfloat16,BM25-retrieved syllabus context,0.0,17.309,11.342,2410.089,5.121,10.737,3686400,0.147,-1.179,-1.624
1,R6_Gemma2B_QLoRA_CONTEXT,Gemma-2B,QLoRA,2.0,4-bit NF4 + double quantisation,BM25-retrieved syllabus context,0.0,17.263,16.083,3619.289,3.321,10.092,3686400,0.243,-1.226,-1.671

Final combined Gemma table saved:
/content/drive/MyDrive/MR603_Thesis/results/Gemma2B_CONTEXT_Final_Results.csv

In [23]:
# ═══════════════════════════════════════════════════════════
# CELL 30: FINAL GEMMA FILE CHECK + GPU CLEANUP
# ═══════════════════════════════════════════════════════════

import os
import gc
import torch

required_files = [
    "REF_qwen14b_zeroshot_CONTEXT.json",
    "REF_qwen14b_2shot_CONTEXT.json",

    "R5_gemma2b_lora_CONTEXT.json",
    "R5_gemma2b_lora_CONTEXT_predictions.jsonl",

    "R6_gemma2b_qlora_CONTEXT.json",
    "R6_gemma2b_qlora_CONTEXT_predictions.jsonl",

    "Gemma2B_LoRA_CONTEXT_QuestionType_Results.csv",
    "Gemma2B_CONTEXT_RQ2_QuestionType_Results.csv",

    "Gemma2B_LoRA_CONTEXT_Final_Results.csv",
    "Gemma2B_CONTEXT_Final_Results.csv",

    "Qwen_Context_Prompting_Comparison.json"
]

print("=" * 78)
print("FINAL GEMMA-2B CORRECTED FILE CHECK")
print("=" * 78)

all_good = True

for filename in required_files:

    path = f"{RESULTS_DIR}/{filename}"

    if os.path.exists(path):

        size_kb = (
            os.path.getsize(path)
            / 1024
        )

        print(
            f"FOUND   {filename} "
            f"({size_kb:.1f} KB)"
        )

    else:

        print(
            f"MISSING {filename}"
        )

        all_good = False

adapter_path = (
    f"{ADAPTER_DIR}/"
    f"R6_gemma2b_qlora_CONTEXT"
)

print("\nQLoRA adapter:")

if os.path.isdir(adapter_path):
    print("FOUND  ", adapter_path)
else:
    print("MISSING", adapter_path)
    all_good = False

if all_good:

    print("\n" + "=" * 70)
    print("✓ GEMMA-2B PHASE COMPLETE")
    print("✓ Qwen zero-shot + context saved")
    print("✓ Qwen 2-shot + context saved")
    print("✓ Gemma LoRA + context saved")
    print("✓ Gemma QLoRA + context saved")
    print("✓ LoRA vs QLoRA comparison saved")
    print("=" * 70)

else:

    print(
        "\nDo not move to Phi yet. "
        "Fix the missing artifact(s) first."
    )

# ------------------------------------------------------------
# GPU cleanup
# ------------------------------------------------------------

for name in [
    "trainer_r6",
    "model_r6",
    "tok_r6"
]:
    if name in globals():
        del globals()[name]

gc.collect()
torch.cuda.empty_cache()

free_vram = (
    torch.cuda.get_device_properties(0).total_memory
    - torch.cuda.memory_allocated()
) / 1024**3

print(
    f"\nGPU cleanup complete. "
    f"Free VRAM: {free_vram:.2f} GB"
)

print(
    "\nAfter this, Gemma-2B is finished "
    "and we can move to Phi-3-mini."
)

==============================================================================
FINAL GEMMA-2B CORRECTED FILE CHECK
==============================================================================
FOUND   REF_qwen14b_zeroshot_CONTEXT.json (1.1 KB)
FOUND   REF_qwen14b_2shot_CONTEXT.json (1.5 KB)
FOUND   R5_gemma2b_lora_CONTEXT.json (2.0 KB)
FOUND   R5_gemma2b_lora_CONTEXT_predictions.jsonl (641.3 KB)
FOUND   R6_gemma2b_qlora_CONTEXT.json (2.0 KB)
FOUND   R6_gemma2b_qlora_CONTEXT_predictions.jsonl (637.4 KB)
FOUND   Gemma2B_LoRA_CONTEXT_QuestionType_Results.csv (0.3 KB)
FOUND   Gemma2B_CONTEXT_RQ2_QuestionType_Results.csv (0.7 KB)
FOUND   Gemma2B_LoRA_CONTEXT_Final_Results.csv (0.5 KB)
FOUND   Gemma2B_CONTEXT_Final_Results.csv (0.7 KB)
FOUND   Qwen_Context_Prompting_Comparison.json (0.4 KB)

QLoRA adapter:
FOUND   /content/drive/MyDrive/MR603_Thesis/adapters/R6_gemma2b_qlora_CONTEXT

======================================================================
✓ GEMMA-2B PHASE COMPLETE
✓ Qwen zero-shot + context saved
✓ Qwen 2-shot + context saved
✓ Gemma LoRA + context saved
✓ Gemma QLoRA + context saved
✓ LoRA vs QLoRA comparison saved
======================================================================

GPU cleanup complete. Free VRAM: 37.52 GB

After this, Gemma-2B is finished and we can move to Phi-3-mini.