# MR604 Thesis — Notebook 3: Mistral-7B Context Implementation

Mistral-7B notebook using the same corrected research pipeline that successfully completed the new Phi-3 Mini notebook.

**Conditions**
- R3 — Mistral-7B LoRA + corrected syllabus context
- R4 — Mistral-7B QLoRA + corrected syllabus context
- Qwen2.5-14B zero-shot + context and 2-shot + context are loaded only as larger prompting references.

**Controlled settings**
- SyllabusQA: 3018 train / 957 validation / 1103 test
- BM25 context data reused from the corrected Gemma/Phi pipeline
- r=16, alpha=32, dropout=0.05
- Mistral targets: q_proj, k_proj, v_proj, o_proj
- LR=2e-4, 3 epochs, batch=4, gradient accumulation=4, max length=512
- deterministic generation, max_new_tokens=64
- local SQuAD-style EM/F1
- standard Hugging Face Trainer; no SFTTrainer
- QLoRA: 4-bit NF4 + double quantisation
- context-specific checkpoints/results so old blank-context experiments are never resumed accidentally

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 1 — INSTALL KNOWN-WORKING STACK
# Run ONCE, then restart runtime/session.
# Do NOT rerun Cell 1 after restart.
# ═══════════════════════════════════════════════════════════

!pip uninstall -y accelerate bitsandbytes >/dev/null 2>&1

!pip install -q --no-cache-dir \
    "transformers==5.16.1" \
    "peft==0.12.0" \
    "datasets" \
    "rank_bm25"

!pip install -q --no-cache-dir --no-deps \
    "accelerate==1.15.0" \
    "bitsandbytes==0.50.2"

!pip show accelerate bitsandbytes | grep -E "Name:|Version:"

print("=" * 70)
print("INSTALLATION COMPLETE")
print("Restart runtime/session ONCE.")
print("After restart begin from Cell 2.")
print("=" * 70)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.4/296.4 kB 76.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 388.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 247.1 MB/s eta 0:00:00
Name: accelerate
Version: 1.15.0
Name: bitsandbytes
Version: 0.50.2
======================================================================
INSTALLATION COMPLETE
Restart runtime/session ONCE.
After restart begin from Cell 2.
======================================================================

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 2 — IMPORTS + ENVIRONMENT CHECK
# ═══════════════════════════════════════════════════════════

import os
import gc
import json
import time
import math
import random
import string
import re
import inspect
import importlib.metadata

import numpy as np
import pandas as pd
import torch

from collections import Counter, defaultdict

import transformers
import accelerate
import peft
import bitsandbytes
import datasets

from datasets import load_from_disk

from transformers import (
    AutoTokenizer,
    MistralForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)

from transformers.utils import is_accelerate_available

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
    TaskType
)

assert torch.cuda.is_available(), "GPU is not enabled."

assert is_accelerate_available(), (
    "Transformers does not detect Accelerate. "
    "Confirm accelerate==1.15.0 and restart runtime once."
)

GPU_NAME = torch.cuda.get_device_name(0)
GPU_VRAM = torch.cuda.get_device_properties(0).total_memory / 1024**3
BF16_OK = torch.cuda.is_bf16_supported()
TRAIN_DTYPE = torch.bfloat16 if BF16_OK else torch.float16

print("=" * 70)
print("ENVIRONMENT VERIFICATION")
print("=" * 70)
print("GPU:", GPU_NAME)
print(f"GPU VRAM: {GPU_VRAM:.2f} GB")
print("BF16 supported:", BF16_OK)
print("Training dtype:", TRAIN_DTYPE)
print()
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)
print("Accelerate metadata:", importlib.metadata.version("accelerate"))
print("PEFT:", peft.__version__)
print("BitsAndBytes:", bitsandbytes.__version__)
print("Datasets:", datasets.__version__)
print("Transformers detects Accelerate:", is_accelerate_available())
print("\n✓ Environment ready.")

======================================================================
ENVIRONMENT VERIFICATION
======================================================================
GPU: NVIDIA A100-SXM4-40GB
GPU VRAM: 39.49 GB
BF16 supported: True
Training dtype: torch.bfloat16

Transformers: 5.16.1
Accelerate: 1.15.0
Accelerate metadata: 1.15.0
PEFT: 0.12.0
BitsAndBytes: 0.50.2
Datasets: 4.8.5
Transformers detects Accelerate: True

✓ Environment ready.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 3 — REPRODUCIBILITY
# ═══════════════════════════════════════════════════════════

SEED = 42

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(SEED)

print("✓ Random seed fixed at:", SEED)

✓ Random seed fixed at: 42

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 4 — GOOGLE DRIVE + PATHS
# Same project location as corrected Gemma/Phi notebooks
# ═══════════════════════════════════════════════════════════

from google.colab import drive

drive.mount("/content/drive")

BASE_DIR = "/content/drive/MyDrive/MR603_Thesis"

RESULTS_DIR = f"{BASE_DIR}/results"
ADAPTER_DIR = f"{BASE_DIR}/adapters"
CHECKPOINT_DIR = f"{BASE_DIR}/checkpoints"
RECOVERY_DIR = f"{BASE_DIR}/recovery_gemma_context"

for path in [RESULTS_DIR, ADAPTER_DIR, CHECKPOINT_DIR]:
    os.makedirs(path, exist_ok=True)

test_file = f"{RESULTS_DIR}/.mistral_write_test"

with open(test_file, "w") as f:
    f.write("ok")

os.remove(test_file)

print("=" * 70)
print("GOOGLE DRIVE READY")
print("=" * 70)
print("BASE_DIR:", BASE_DIR)
print("RESULTS_DIR:", RESULTS_DIR)
print("ADAPTER_DIR:", ADAPTER_DIR)
print("CHECKPOINT_DIR:", CHECKPOINT_DIR)
print("RECOVERY_DIR:", RECOVERY_DIR)
print("✓ Drive is writable.")

Mounted at /content/drive
======================================================================
GOOGLE DRIVE READY
======================================================================
BASE_DIR: /content/drive/MyDrive/MR603_Thesis
RESULTS_DIR: /content/drive/MyDrive/MR603_Thesis/results
ADAPTER_DIR: /content/drive/MyDrive/MR603_Thesis/adapters
CHECKPOINT_DIR: /content/drive/MyDrive/MR603_Thesis/checkpoints
RECOVERY_DIR: /content/drive/MyDrive/MR603_Thesis/recovery_gemma_context
✓ Drive is writable.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 5 — HUGGING FACE LOGIN
# ═══════════════════════════════════════════════════════════

from huggingface_hub import login
from google.colab import userdata

try:
    hf_token = userdata.get("HF_TOKEN")
    login(token=hf_token)
    print("✓ Logged in using Colab HF_TOKEN.")
except Exception as e:
    print("Could not use HF_TOKEN secret:", e)
    hf_token = input("Paste Hugging Face token: ")
    login(token=hf_token)
    print("✓ Logged in manually.")

Could not use HF_TOKEN secret: Secret HF_TOKEN does not exist.
Paste Hugging Face token: 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
✓ Logged in manually.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 6 — MISTRAL-7B EXPERIMENT CONFIGURATION
# Preserves the original Mistral research settings.
# ═══════════════════════════════════════════════════════════

MODEL_ID = "mistralai/Mistral-7B-Instruct-v0.2"
MODEL_NAME = "Mistral-7B"
QWEN_MODEL_ID = "Qwen/Qwen2.5-14B-Instruct"

LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05

LORA_TARGET_MODULES = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj"
]

LEARNING_RATE = 2e-4
NUM_EPOCHS = 3
BATCH_SIZE = 4
GRAD_ACCUM = 4
EFFECTIVE_BATCH = BATCH_SIZE * GRAD_ACCUM
MAX_SEQ_LENGTH = 512
WARMUP_RATIO = 0.03
MAX_NEW_TOKENS = 64

EXPECTED_TRAINABLE_PARAMS = 13_631_488

print("=" * 70)
print("MISTRAL-7B EXPERIMENTAL CONFIGURATION")
print("=" * 70)
print("SLM model:", MODEL_ID)
print("Reference model:", QWEN_MODEL_ID)
print()
print("LoRA / QLoRA:")
print("  Rank:", LORA_R)
print("  Alpha:", LORA_ALPHA)
print("  Scaling ratio:", LORA_ALPHA / LORA_R)
print("  Dropout:", LORA_DROPOUT)
print("  Target modules:", LORA_TARGET_MODULES)
print()
print("Training:")
print("  Learning rate:", LEARNING_RATE)
print("  Epochs:", NUM_EPOCHS)
print("  Batch size:", BATCH_SIZE)
print("  Gradient accumulation:", GRAD_ACCUM)
print("  Effective batch:", EFFECTIVE_BATCH)
print("  Max sequence length:", MAX_SEQ_LENGTH)
print("  Warmup ratio design:", WARMUP_RATIO)
print("  Max new tokens:", MAX_NEW_TOKENS)
print("  Seed:", SEED)

======================================================================
MISTRAL-7B EXPERIMENTAL CONFIGURATION
======================================================================
SLM model: mistralai/Mistral-7B-Instruct-v0.2
Reference model: Qwen/Qwen2.5-14B-Instruct

LoRA / QLoRA:
  Rank: 16
  Alpha: 32
  Scaling ratio: 2.0
  Dropout: 0.05
  Target modules: ['q_proj', 'k_proj', 'v_proj', 'o_proj']

Training:
  Learning rate: 0.0002
  Epochs: 3
  Batch size: 4
  Gradient accumulation: 4
  Effective batch: 16
  Max sequence length: 512
  Warmup ratio design: 0.03
  Max new tokens: 64
  Seed: 42

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 7 — LOAD EXACT CORRECTED CONTEXT DATASET
# Reuses the exact context-aware data already used by
# corrected Gemma and corrected Phi.
# ═══════════════════════════════════════════════════════════

corrected_path = f"{RECOVERY_DIR}/corrected_data"
raw_path = f"{RECOVERY_DIR}/raw_dataset"

assert os.path.exists(corrected_path), (
    "Corrected dataset recovery folder is missing."
)

assert os.path.exists(raw_path), (
    "Raw dataset recovery folder is missing."
)

print("Loading exact corrected context datasets...")

corrected_data = load_from_disk(corrected_path)
dataset = load_from_disk(raw_path)

train_data = corrected_data["train"]
val_data = corrected_data["validation"]
test_data = corrected_data["test"]

print("\n" + "=" * 70)
print("CORRECTED DATASET CHECK")
print("=" * 70)
print("Train:", len(train_data))
print("Validation:", len(val_data))
print("Test:", len(test_data))
print("Raw test:", len(dataset["test"]))

assert len(train_data) == 3018
assert len(val_data) == 957
assert len(test_data) == 1103
assert len(dataset["test"]) == 1103

train_blank = sum(
    1 for ex in train_data
    if "Syllabus context:\n\n" in ex["text"]
)

test_blank = sum(
    1 for ex in test_data
    if "Syllabus context:\n\n" in ex["prompt"]
)

assert train_blank == 0, f"Blank train contexts: {train_blank}"
assert test_blank == 0, f"Blank test contexts: {test_blank}"

print("✓ Dataset sizes correct.")
print("✓ Correct syllabus context present in all checked examples.")
print("\nSample corrected test prompt:\n")
print(test_data[0]["prompt"][:900])

Loading exact corrected context datasets...

======================================================================
CORRECTED DATASET CHECK
======================================================================
Train: 3018
Validation: 957
Test: 1103
Raw test: 1103
✓ Dataset sizes correct.
✓ Correct syllabus context present in all checked examples.

Sample corrected test prompt:

Syllabus context:
Extra Credit: Four extra credit opportunities will be available during the semester. Three of these are exam reflections and the fourth is the end-of-course survey. Each one has a maximum value of 0.3 percentage points towards your final grade. Additional details will be provided as each assignment becomes available. Final Grading Scale: Final grades are rounded to the tenth and then assigned according to this scale. A 93.00 100.00% B-80.00 82.99% D+ 67.00 69.99% A-90.00 92.99% C+ 77.00 79.99% D 60.00 66.99% B+ 87.00 89.99% C 73.00 76.99% F <59.99
miss some assignments and classes are built into the course and should cover most circumstances, but if you have an unexpected situation or assignment extensions are part of your accommodations, contact me as soon as possible to discuss an extension. Note: Because of the course flexibility, extension requests should be infrequ

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 8 — LOCAL SQuAD EM/F1
# Same metric implementation used in corrected Phi.
# ═══════════════════════════════════════════════════════════

def get_answer(example):
    answer = example.get("answer", "")

    if isinstance(answer, dict):
        texts = answer.get("text", [])
        return texts[0].strip() if texts else ""

    if isinstance(answer, list):
        return str(answer[0]).strip() if answer else ""

    return str(answer).strip() if answer is not None else ""


def normalize_answer(s):

    def remove_articles(text):
        return re.sub(r"\b(a|an|the)\b", " ", text)

    def white_space_fix(text):
        return " ".join(text.split())

    def remove_punc(text):
        exclude = set(string.punctuation)
        return "".join(ch for ch in text if ch not in exclude)

    return white_space_fix(
        remove_articles(
            remove_punc(str(s).lower())
        )
    )


def exact_match_score(prediction, ground_truth):
    return float(
        normalize_answer(prediction)
        ==
        normalize_answer(ground_truth)
    )


def f1_score(prediction, ground_truth):

    prediction_tokens = normalize_answer(prediction).split()
    ground_truth_tokens = normalize_answer(ground_truth).split()

    if len(prediction_tokens) == 0 or len(ground_truth_tokens) == 0:
        return float(prediction_tokens == ground_truth_tokens)

    common = Counter(prediction_tokens) & Counter(ground_truth_tokens)
    num_same = sum(common.values())

    if num_same == 0:
        return 0.0

    precision = num_same / len(prediction_tokens)
    recall = num_same / len(ground_truth_tokens)

    return 2 * precision * recall / (precision + recall)


class LocalSquadMetric:

    def compute(self, predictions, references):

        reference_dict = {
            str(ref["id"]): ref["answers"]["text"]
            for ref in references
        }

        exact_scores = []
        f1_scores = []

        for pred in predictions:

            pred_id = str(pred["id"])
            prediction_text = pred["prediction_text"]

            ground_truths = reference_dict.get(pred_id, [""])

            if not ground_truths:
                ground_truths = [""]

            exact_scores.append(
                max(
                    exact_match_score(prediction_text, gt)
                    for gt in ground_truths
                )
            )

            f1_scores.append(
                max(
                    f1_score(prediction_text, gt)
                    for gt in ground_truths
                )
            )

        return {
            "exact_match":
                100.0 * sum(exact_scores) / len(exact_scores),

            "f1":
                100.0 * sum(f1_scores) / len(f1_scores)
        }


squad_metric = LocalSquadMetric()

references = [
    {
        "id": str(i),
        "answers": {
            "text": [get_answer(example)],
            "answer_start": [0]
        }
    }
    for i, example in enumerate(dataset["test"])
]

print("✓ Local SQuAD-style metric ready.")
print("References:", len(references))

✓ Local SQuAD-style metric ready.
References: 1103

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 9 — COMMON EVALUATION + STRATIFIED ANALYSIS
# Same output style as corrected Phi.
# ═══════════════════════════════════════════════════════════

def run_evaluation(
    model,
    tokenizer,
    test_data,
    references,
    condition_name
):

    print("\n" + "=" * 55)
    print(f"EVALUATING: {condition_name}")
    print("=" * 55)

    print(f"Test examples: {len(test_data):,}")
    print("Progress logged every 100 examples")

    model.eval()

    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()

    all_predictions = []
    all_latencies = []

    for i, example in enumerate(test_data):

        if i % 100 == 0:

            elapsed_min = (
                sum(all_latencies) / 1000 / 60
                if all_latencies
                else 0
            )

            avg_lat = (
                sum(all_latencies) / len(all_latencies)
                if all_latencies
                else 0
            )

            print(
                f"{i:4d}/{len(test_data)} | "
                f"{elapsed_min:.1f} min | "
                f"{avg_lat:.0f} ms/sample"
            )

        inputs = tokenizer(
            example["prompt"],
            return_tensors="pt",
            max_length=MAX_SEQ_LENGTH,
            truncation=True,
            padding=False
        ).to(model.device)

        input_length = inputs["input_ids"].shape[1]

        torch.cuda.synchronize()
        start_time = time.perf_counter()

        with torch.no_grad():

            outputs = model.generate(
                **inputs,
                max_new_tokens=MAX_NEW_TOKENS,
                do_sample=False,
                num_beams=1,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id
            )

        torch.cuda.synchronize()

        latency_ms = (
            time.perf_counter() - start_time
        ) * 1000

        all_latencies.append(latency_ms)

        new_tokens = outputs[0][input_length:]

        prediction = tokenizer.decode(
            new_tokens,
            skip_special_tokens=True
        ).strip()

        all_predictions.append(prediction)

    predictions_fmt = [
        {
            "id": str(i),
            "prediction_text": pred
        }
        for i, pred in enumerate(all_predictions)
    ]

    metrics = squad_metric.compute(
        predictions=predictions_fmt,
        references=references
    )

    em = float(metrics["exact_match"])
    f1 = float(metrics["f1"])
    avg_latency = float(np.mean(all_latencies))
    median_latency = float(np.median(all_latencies))

    peak_vram_gb = float(
        torch.cuda.max_memory_allocated() / 1024**3
    )

    print("\n" + "─" * 45)
    print(f"RESULTS: {condition_name}")
    print("─" * 45)
    print(f"Exact Match:    {em:.3f}%")
    print(f"F1 Score:       {f1:.3f}%")
    print(f"Avg Latency:    {avg_latency:.3f} ms/sample")
    print(f"Median Latency: {median_latency:.3f} ms/sample")
    print(f"Peak GPU VRAM:  {peak_vram_gb:.3f} GB")

    return {
        "condition": condition_name,
        "em": em,
        "f1": f1,
        "avg_latency_ms": avg_latency,
        "median_latency_ms": median_latency,
        "peak_vram_gb": peak_vram_gb,
        "predictions": all_predictions,
        "latencies": all_latencies
    }


def stratified_analysis(
    predictions,
    test_raw,
    condition_name
):

    print(
        f"\nRunning stratified analysis: "
        f"{condition_name}"
    )

    type_preds = defaultdict(list)
    type_refs = defaultdict(list)
    type_counts = defaultdict(int)

    for i, example in enumerate(test_raw):

        q_type = example.get(
            "question_type",
            "unknown"
        )

        answer_text = get_answer(example)

        prediction = (
            predictions[i]
            if i < len(predictions)
            else ""
        )

        type_preds[q_type].append({
            "id": str(i),
            "prediction_text": prediction
        })

        type_refs[q_type].append({
            "id": str(i),
            "answers": {
                "text": [answer_text],
                "answer_start": [0]
            }
        })

        type_counts[q_type] += 1

    results = {}

    print(
        f"\n{'Question Type':25s} "
        f"{'EM %':8s} "
        f"{'F1 %':8s} "
        f"{'n':5s}"
    )

    print("─" * 50)

    for q_type in sorted(type_preds.keys()):

        metrics = squad_metric.compute(
            predictions=type_preds[q_type],
            references=type_refs[q_type]
        )

        results[q_type] = {
            "exact_match":
                float(metrics["exact_match"]),
            "f1":
                float(metrics["f1"]),
            "count":
                int(type_counts[q_type])
        }

        print(
            f"{q_type:25s} "
            f"{metrics['exact_match']:8.3f} "
            f"{metrics['f1']:8.3f} "
            f"{type_counts[q_type]:5d}"
        )

    return results


print("✓ run_evaluation() ready.")
print("✓ stratified_analysis() ready.")

✓ run_evaluation() ready.
✓ stratified_analysis() ready.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 10 — LOAD CORRECTED QWEN REFERENCES
# ═══════════════════════════════════════════════════════════

zero_path = f"{RESULTS_DIR}/REF_qwen14b_zeroshot_CONTEXT.json"
few_path = f"{RESULTS_DIR}/REF_qwen14b_2shot_CONTEXT.json"

assert os.path.exists(zero_path), (
    "Corrected Qwen zero-shot result not found."
)

with open(zero_path, "r") as f:
    results_qwen_zero = json.load(f)

QWEN_ZERO_EM = float(results_qwen_zero["em"])
QWEN_ZERO_F1 = float(results_qwen_zero["f1"])

print("=" * 70)
print("CORRECTED QWEN REFERENCES")
print("=" * 70)

print(
    f"Qwen zero-shot + context: "
    f"EM={QWEN_ZERO_EM:.3f}% | "
    f"F1={QWEN_ZERO_F1:.3f}%"
)

if os.path.exists(few_path):

    with open(few_path, "r") as f:
        results_qwen_few = json.load(f)

    QWEN_FEW_EM = float(results_qwen_few["em"])
    QWEN_FEW_F1 = float(results_qwen_few["f1"])

    print(
        f"Qwen 2-shot + context:    "
        f"EM={QWEN_FEW_EM:.3f}% | "
        f"F1={QWEN_FEW_F1:.3f}%"
    )

else:
    print("WARNING: corrected Qwen 2-shot result not found.")

======================================================================
CORRECTED QWEN REFERENCES
======================================================================
Qwen zero-shot + context: EM=0.000% | F1=17.792%
Qwen 2-shot + context:    EM=0.091% | F1=18.934%

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 11 — MISTRAL PRE-TRAINING PREFLIGHT
# Do not train unless every assertion passes.
# ═══════════════════════════════════════════════════════════

print("=" * 76)
print("MISTRAL-7B PRE-TRAINING PREFLIGHT")
print("=" * 76)

required_objects = [
    "set_seed",
    "train_data",
    "val_data",
    "test_data",
    "dataset",
    "references",
    "run_evaluation",
    "stratified_analysis",
    "QWEN_ZERO_F1"
]

missing = [
    name for name in required_objects
    if name not in globals()
]

assert not missing, (
    f"Missing runtime objects: {missing}"
)

assert len(train_data) == 3018
assert len(val_data) == 957
assert len(test_data) == 1103
assert len(references) == 1103

assert "Syllabus context:" in train_data[0]["text"]
assert "Syllabus context:" in test_data[0]["prompt"]

assert "Syllabus context:\n\n" not in train_data[0]["text"]
assert "Syllabus context:\n\n" not in test_data[0]["prompt"]

assert is_accelerate_available()

free_vram = (
    torch.cuda.get_device_properties(0).total_memory
    - torch.cuda.memory_allocated()
) / 1024**3

print("GPU:", GPU_NAME)
print(f"Free VRAM: {free_vram:.2f} GB")
print("✓ Required runtime objects exist.")
print("✓ Dataset sizes: 3018 / 957 / 1103.")
print("✓ Corrected syllabus context confirmed.")
print(f"✓ Qwen zero-shot F1: {QWEN_ZERO_F1:.3f}%")

if "QWEN_FEW_F1" in globals():
    print(f"✓ Qwen 2-shot F1: {QWEN_FEW_F1:.3f}%")

print("✓ Transformers detects Accelerate.")
print("✓ Mistral targets:", LORA_TARGET_MODULES)

print("\n" + "=" * 76)
print("ALL PREFLIGHT CHECKS PASSED")
print("CONTINUE TO CELL 12 — MISTRAL LoRA SETUP")
print("=" * 76)

============================================================================
MISTRAL-7B PRE-TRAINING PREFLIGHT
============================================================================
GPU: NVIDIA A100-SXM4-40GB
Free VRAM: 39.49 GB
✓ Required runtime objects exist.
✓ Dataset sizes: 3018 / 957 / 1103.
✓ Corrected syllabus context confirmed.
✓ Qwen zero-shot F1: 17.792%
✓ Qwen 2-shot F1: 18.934%
✓ Transformers detects Accelerate.
✓ Mistral targets: ['q_proj', 'k_proj', 'v_proj', 'o_proj']

============================================================================
ALL PREFLIGHT CHECKS PASSED
CONTINUE TO CELL 12 — MISTRAL LoRA SETUP
============================================================================

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 12 — R3 MISTRAL-7B LoRA SETUP
# Native MistralForCausalLM + SDPA
# ═══════════════════════════════════════════════════════════

gc.collect()
torch.cuda.empty_cache()
set_seed(SEED)

print("=" * 72)
print("R3 — MISTRAL-7B LoRA + CORRECTED CONTEXT")
print("=" * 72)

tokenizer_r3 = AutoTokenizer.from_pretrained(
    MODEL_ID
)

if tokenizer_r3.pad_token is None:
    tokenizer_r3.pad_token = tokenizer_r3.eos_token

tokenizer_r3.padding_side = "right"

print("\nLoading native MistralForCausalLM...")

model_r3 = MistralForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=TRAIN_DTYPE,
    device_map={"": 0},
    attn_implementation="sdpa"
)

model_r3.config.pad_token_id = tokenizer_r3.pad_token_id
model_r3.config.use_cache = False

available_modules = {
    name.split(".")[-1]
    for name, _ in model_r3.named_modules()
}

missing_targets = [
    module
    for module in LORA_TARGET_MODULES
    if module not in available_modules
]

assert not missing_targets, (
    f"Mistral LoRA target modules missing: {missing_targets}"
)

print("✓ Target modules confirmed:", LORA_TARGET_MODULES)

lora_config_r3 = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=LORA_TARGET_MODULES,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

model_r3 = get_peft_model(
    model_r3,
    lora_config_r3
)

model_r3.enable_input_require_grads()

model_r3.gradient_checkpointing_enable(
    gradient_checkpointing_kwargs={
        "use_reentrant": False
    }
)

model_r3.config.use_cache = False

model_r3.print_trainable_parameters()

trainable_r3 = sum(
    p.numel()
    for p in model_r3.parameters()
    if p.requires_grad
)

total_r3 = sum(
    p.numel()
    for p in model_r3.parameters()
)

trainable_pct_r3 = (
    100 * trainable_r3 / total_r3
)

print(f"\nTrainable parameters: {trainable_r3:,}")
print(f"Total parameters: {total_r3:,}")
print(f"Trainable percentage: {trainable_pct_r3:.4f}%")

if trainable_r3 != EXPECTED_TRAINABLE_PARAMS:
    print(
        "WARNING: trainable parameter count differs from "
        f"the previous Mistral run ({EXPECTED_TRAINABLE_PARAMS:,})."
    )
else:
    print("✓ Trainable parameter count matches previous Mistral run.")

def tokenize_r3(batch):
    return tokenizer_r3(
        batch["text"],
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
        padding=False
    )

print("\nTokenizing corrected training dataset...")

train_tokenized_r3 = train_data.map(
    tokenize_r3,
    batched=True,
    remove_columns=train_data.column_names
)

print("Tokenizing corrected validation dataset...")

val_tokenized_r3 = val_data.map(
    tokenize_r3,
    batched=True,
    remove_columns=val_data.column_names
)

data_collator_r3 = DataCollatorForLanguageModeling(
    tokenizer=tokenizer_r3,
    mlm=False
)

steps_per_epoch_r3 = math.ceil(
    len(train_tokenized_r3)
    / BATCH_SIZE
    / GRAD_ACCUM
)

total_steps_r3 = (
    steps_per_epoch_r3
    * NUM_EPOCHS
)

warmup_steps_r3 = math.ceil(
    total_steps_r3
    * WARMUP_RATIO
)

ta_params = inspect.signature(
    TrainingArguments.__init__
).parameters

if "eval_strategy" in ta_params:
    eval_key_r3 = "eval_strategy"
elif "evaluation_strategy" in ta_params:
    eval_key_r3 = "evaluation_strategy"
else:
    raise RuntimeError(
        "TrainingArguments has no supported evaluation strategy."
    )

R3_CHECKPOINT_DIR = (
    f"{CHECKPOINT_DIR}/"
    "R3_mistral7b_lora_CONTEXT"
)

training_kwargs_r3 = {
    "output_dir":
        R3_CHECKPOINT_DIR,
    "num_train_epochs":
        NUM_EPOCHS,
    "per_device_train_batch_size":
        BATCH_SIZE,
    "per_device_eval_batch_size":
        1,
    "gradient_accumulation_steps":
        GRAD_ACCUM,
    "learning_rate":
        LEARNING_RATE,
    "lr_scheduler_type":
        "cosine",
    "warmup_steps":
        warmup_steps_r3,
    "bf16":
        BF16_OK,
    "fp16":
        not BF16_OK,
    "logging_steps":
        50,
    "save_strategy":
        "epoch",
    "save_total_limit":
        2,
    "load_best_model_at_end":
        True,
    "metric_for_best_model":
        "eval_loss",
    "greater_is_better":
        False,
    "gradient_checkpointing":
        True,
    "gradient_checkpointing_kwargs": {
        "use_reentrant": False
    },
    "optim":
        "paged_adamw_8bit",
    "seed":
        SEED,
    "data_seed":
        SEED,
    "report_to":
        "none"
}

training_kwargs_r3[
    eval_key_r3
] = "epoch"

train_args_r3 = TrainingArguments(
    **training_kwargs_r3
)

trainer_r3 = Trainer(
    model=model_r3,
    args=train_args_r3,
    train_dataset=train_tokenized_r3,
    eval_dataset=val_tokenized_r3,
    data_collator=data_collator_r3
)

print("\nTraining schedule:")
print("Steps per epoch:", steps_per_epoch_r3)
print("Total optimizer steps:", total_steps_r3)
print("Warmup steps:", warmup_steps_r3)

print("\n✓ R3 LoRA Trainer created successfully.")
print("✓ Continue to Cell 13.")

========================================================================
R3 — MISTRAL-7B LoRA + CORRECTED CONTEXT
========================================================================

config.json:   0%|          | 0.00/596 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.10k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

tokenizer.model: reconstructing file:   0%|          |  0.00B /  493kB

tokenizer.model: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

Loading native MistralForCausalLM...

model.safetensors.index.json:   0%|          | 0.00/25.1k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

✓ Target modules confirmed: ['q_proj', 'k_proj', 'v_proj', 'o_proj']
trainable params: 13,631,488 || all params: 7,255,363,584 || trainable%: 0.1879

Trainable parameters: 13,631,488
Total parameters: 7,255,363,584
Trainable percentage: 0.1879%
✓ Trainable parameter count matches previous Mistral run.

Tokenizing corrected training dataset...

Map:   0%|          | 0/3018 [00:00<?, ? examples/s]

Tokenizing corrected validation dataset...

Map:   0%|          | 0/957 [00:00<?, ? examples/s]

Training schedule:
Steps per epoch: 189
Total optimizer steps: 567
Warmup steps: 18

✓ R3 LoRA Trainer created successfully.
✓ Continue to Cell 13.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 13 — TRAIN R3 MISTRAL LoRA + SAVE ADAPTER
# Fresh corrected-context run. No old checkpoint resume.
# ═══════════════════════════════════════════════════════════

torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

r3_train_start = time.perf_counter()

print("=" * 72)
print("STARTING MISTRAL-7B LoRA TRAINING")
print("=" * 72)
print(f"Training examples: {len(train_tokenized_r3):,}")
print(f"Epochs: {NUM_EPOCHS}")
print(f"Effective batch: {EFFECTIVE_BATCH}")
print(f"Learning rate: {LEARNING_RATE}")

train_output_r3 = trainer_r3.train()

torch.cuda.synchronize()

r3_train_seconds = (
    time.perf_counter() - r3_train_start
)

r3_train_mins = (
    r3_train_seconds / 60
)

r3_peak_train_vram = (
    torch.cuda.max_memory_allocated() / 1024**3
)

print("\n" + "=" * 62)
print("MISTRAL-7B LoRA TRAINING COMPLETE")
print("=" * 62)
print(f"Training time: {r3_train_mins:.2f} min")
print(f"Peak training VRAM: {r3_peak_train_vram:.3f} GB")

R3_ADAPTER_PATH = (
    f"{ADAPTER_DIR}/"
    "R3_mistral7b_lora_CONTEXT"
)

model_r3.save_pretrained(
    R3_ADAPTER_PATH
)

tokenizer_r3.save_pretrained(
    R3_ADAPTER_PATH
)

print("\nLoRA adapter saved:")
print(R3_ADAPTER_PATH)
print("✓ Continue to Cell 14.")

========================================================================
STARTING MISTRAL-7B LoRA TRAINING
========================================================================
Training examples: 3,018
Epochs: 3
Effective batch: 16
Learning rate: 0.0002

==============================================================
MISTRAL-7B LoRA TRAINING COMPLETE
==============================================================
Training time: 23.42 min
Peak training VRAM: 14.897 GB

LoRA adapter saved:
/content/drive/MyDrive/MR603_Thesis/adapters/R3_mistral7b_lora_CONTEXT
✓ Continue to Cell 14.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 14 — EVALUATE + SAVE R3 MISTRAL LoRA
# ═══════════════════════════════════════════════════════════

model_r3.config.use_cache = True
model_r3.eval()

results_r3 = run_evaluation(
    model=model_r3,
    tokenizer=tokenizer_r3,
    test_data=test_data,
    references=references,
    condition_name=
        "R3_Mistral7B_LoRA_CONTEXT"
)

results_r3.update({
    "model":
        "Mistral-7B",
    "method":
        "LoRA",
    "parameters":
        "7B",
    "precision":
        "bfloat16"
        if BF16_OK
        else "float16",
    "context_mode":
        "BM25-retrieved syllabus context",
    "training_time_seconds":
        float(r3_train_seconds),
    "training_time_minutes":
        float(r3_train_mins),
    "peak_training_vram_gb":
        float(r3_peak_train_vram),
    "trainable_parameters":
        int(trainable_r3),
    "trainable_percentage":
        float(trainable_pct_r3)
})

print("\nRunning native question-type analysis...")

strat_r3 = stratified_analysis(
    predictions=
        results_r3["predictions"],
    test_raw=
        dataset["test"],
    condition_name=
        "R3_Mistral7B_LoRA_CONTEXT"
)

results_r3["stratified"] = strat_r3
results_r3["stratified_em"] = strat_r3

save_r3 = {
    k: v
    for k, v in results_r3.items()
    if k not in [
        "predictions",
        "latencies"
    ]
}

R3_RESULT_PATH = (
    f"{RESULTS_DIR}/"
    "R3_mistral7b_lora_CONTEXT.json"
)

with open(
    R3_RESULT_PATH,
    "w"
) as f:
    json.dump(
        save_r3,
        f,
        indent=2
    )

R3_PRED_JSONL = (
    f"{RESULTS_DIR}/"
    "R3_mistral7b_lora_CONTEXT_predictions.jsonl"
)

with open(
    R3_PRED_JSONL,
    "w",
    encoding="utf-8"
) as f:

    for i, prediction in enumerate(
        results_r3["predictions"]
    ):

        raw = dataset["test"][i]

        row = {
            "id":
                str(i),
            "syllabus_name":
                raw["syllabus_name"],
            "question_type":
                raw["question_type"],
            "question":
                raw["question"],
            "reference_answer":
                get_answer(raw),
            "prediction":
                prediction,
            "latency_ms":
                results_r3["latencies"][i]
        }

        f.write(
            json.dumps(
                row,
                ensure_ascii=False
            ) + "\n"
        )

R3_PRED_CSV = (
    f"{RESULTS_DIR}/"
    "R3_mistral7b_lora_CONTEXT_predictions.csv"
)

pd.DataFrame({
    "Question":
        [
            ex.get("question", "")
            for ex in dataset["test"]
        ],
    "Question_Type":
        [
            ex.get("question_type", "unknown")
            for ex in dataset["test"]
        ],
    "Reference":
        [
            get_answer(ex)
            for ex in dataset["test"]
        ],
    "Prediction":
        results_r3["predictions"],
    "Latency_ms":
        results_r3["latencies"]
}).to_csv(
    R3_PRED_CSV,
    index=False
)

print("\n" + "=" * 62)
print("MISTRAL-7B LoRA CORRECTED RESULTS")
print("=" * 62)
print(f"Exact Match: {results_r3['em']:.3f}%")
print(f"F1 Score: {results_r3['f1']:.3f}%")
print(f"Avg Latency: {results_r3['avg_latency_ms']:.3f} ms/sample")
print(f"Median Latency: {results_r3['median_latency_ms']:.3f} ms/sample")
print(f"Peak Eval VRAM: {results_r3['peak_vram_gb']:.3f} GB")
print(f"Training Time: {r3_train_mins:.2f} min")
print(f"Peak Training VRAM: {r3_peak_train_vram:.3f} GB")

print("\nRQ1 CHECK — Mistral LoRA vs corrected Qwen")
print(f"Qwen zero-shot + context F1: {QWEN_ZERO_F1:.3f}%")

if "QWEN_FEW_F1" in globals():
    print(f"Qwen 2-shot + context F1: {QWEN_FEW_F1:.3f}%")

print(f"Mistral LoRA + context F1: {results_r3['f1']:.3f}%")
print(f"Gap to Qwen zero-shot: {results_r3['f1'] - QWEN_ZERO_F1:+.3f} pp")

if "QWEN_FEW_F1" in globals():
    print(f"Gap to Qwen 2-shot: {results_r3['f1'] - QWEN_FEW_F1:+.3f} pp")

print("\nResults saved:", R3_RESULT_PATH)
print("Predictions JSONL:", R3_PRED_JSONL)
print("Predictions CSV:", R3_PRED_CSV)

=======================================================
EVALUATING: R3_Mistral7B_LoRA_CONTEXT
=======================================================
Test examples: 1,103
Progress logged every 100 examples
   0/1103 | 0.0 min | 0 ms/sample
 100/1103 | 6.9 min | 4134 ms/sample
 200/1103 | 13.8 min | 4133 ms/sample
 300/1103 | 20.6 min | 4127 ms/sample
 400/1103 | 27.5 min | 4121 ms/sample
 500/1103 | 34.3 min | 4119 ms/sample
 600/1103 | 41.2 min | 4119 ms/sample
 700/1103 | 48.0 min | 4117 ms/sample
 800/1103 | 54.9 min | 4117 ms/sample
 900/1103 | 61.7 min | 4117 ms/sample
1000/1103 | 68.6 min | 4117 ms/sample
1100/1103 | 75.5 min | 4118 ms/sample

─────────────────────────────────────────────
RESULTS: R3_Mistral7B_LoRA_CONTEXT
─────────────────────────────────────────────
Exact Match:    0.000%
F1 Score:       19.483%
Avg Latency:    4117.590 ms/sample
Median Latency: 4114.102 ms/sample
Peak GPU VRAM:  13.701 GB

Running native question-type analysis...

Running stratified analysis: R3_Mistral7B_LoRA_CONTEXT

Question Type             EM %     F1 %     n
──────────────────────────────────────────────────
multi factual                0.000   30.545   158
multi reasoning              0.000   27.359   158
no answer                    0.000    5.646   155
single factual               0.000   18.188   158
single reasoning             0.000   23.734   158
summarization                0.000   27.160   158
yes/no                       0.000    3.485   158

==============================================================
MISTRAL-7B LoRA CORRECTED RESULTS
==============================================================
Exact Match: 0.000%
F1 Score: 19.483%
Avg Latency: 4117.590 ms/sample
Median Latency: 4114.102 ms/sample
Peak Eval VRAM: 13.701 GB
Training Time: 23.42 min
Peak Training VRAM: 14.897 GB

RQ1 CHECK — Mistral LoRA vs corrected Qwen
Qwen zero-shot + context F1: 17.792%
Qwen 2-shot + context F1: 18.934%
Mistral LoRA + context F1: 19.483%
Gap to Qwen zero-shot: +1.691 pp
Gap to Qwen 2-shot: +0.549 pp

Results saved: /content/drive/MyDrive/MR603_Thesis/results/R3_mistral7b_lora_CONTEXT.json
Predictions JSONL: /content/drive/MyDrive/MR603_Thesis/results/R3_mistral7b_lora_CONTEXT_predictions.jsonl
Predictions CSV: /content/drive/MyDrive/MR603_Thesis/results/R3_mistral7b_lora_CONTEXT_predictions.csv

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 15 — CLEAR R3 LoRA MODEL FROM GPU
# ═══════════════════════════════════════════════════════════

for name in [
    "trainer_r3",
    "model_r3",
    "train_tokenized_r3",
    "val_tokenized_r3"
]:
    if name in globals():
        del globals()[name]

gc.collect()
torch.cuda.empty_cache()

free_vram = (
    torch.cuda.get_device_properties(0).total_memory
    - torch.cuda.memory_allocated()
) / 1024**3

print("✓ R3 LoRA cleared from GPU.")
print(f"Free VRAM: {free_vram:.2f} GB")
print("✓ Continue to Cell 16 — QLoRA setup.")

✓ R3 LoRA cleared from GPU.
Free VRAM: 39.23 GB
✓ Continue to Cell 16 — QLoRA setup.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 16 — R4 MISTRAL-7B QLoRA SETUP
# Native MistralForCausalLM + 4-bit NF4
# Fresh corrected-context run.
# ═══════════════════════════════════════════════════════════

gc.collect()
torch.cuda.empty_cache()
set_seed(SEED)

print("=" * 72)
print("R4 — MISTRAL-7B QLoRA + CORRECTED CONTEXT")
print("=" * 72)

tokenizer_r4 = AutoTokenizer.from_pretrained(
    MODEL_ID
)

if tokenizer_r4.pad_token is None:
    tokenizer_r4.pad_token = tokenizer_r4.eos_token

tokenizer_r4.padding_side = "right"

bnb_config_r4 = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=TRAIN_DTYPE
)

print("\nLoading native MistralForCausalLM in 4-bit NF4...")

model_r4 = MistralForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config_r4,
    device_map={"": 0},
    attn_implementation="sdpa"
)

model_r4.config.pad_token_id = tokenizer_r4.pad_token_id
model_r4.config.use_cache = False

print(
    f"Allocated VRAM after model load: "
    f"{torch.cuda.memory_allocated()/1024**3:.3f} GB"
)

model_r4 = prepare_model_for_kbit_training(
    model_r4,
    use_gradient_checkpointing=True
)

model_r4.config.use_cache = False

available_modules = {
    name.split(".")[-1]
    for name, _ in model_r4.named_modules()
}

missing_targets = [
    module
    for module in LORA_TARGET_MODULES
    if module not in available_modules
]

assert not missing_targets, (
    f"Mistral QLoRA target modules missing: {missing_targets}"
)

print("✓ Target modules confirmed:", LORA_TARGET_MODULES)

lora_config_r4 = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=LORA_TARGET_MODULES,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

model_r4 = get_peft_model(
    model_r4,
    lora_config_r4
)

model_r4.print_trainable_parameters()

trainable_r4 = sum(
    p.numel()
    for p in model_r4.parameters()
    if p.requires_grad
)

total_r4 = sum(
    p.numel()
    for p in model_r4.parameters()
)

trainable_pct_r4 = (
    100 * trainable_r4 / total_r4
)

print(f"\nTrainable parameters: {trainable_r4:,}")
print(f"Total parameters: {total_r4:,}")
print(f"Trainable percentage: {trainable_pct_r4:.4f}%")

if trainable_r4 != EXPECTED_TRAINABLE_PARAMS:
    print(
        "WARNING: trainable parameter count differs from "
        f"the previous Mistral run ({EXPECTED_TRAINABLE_PARAMS:,})."
    )
else:
    print("✓ Trainable parameter count matches previous Mistral run.")

def tokenize_r4(batch):
    return tokenizer_r4(
        batch["text"],
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
        padding=False
    )

print("\nTokenizing corrected training dataset...")

train_tokenized_r4 = train_data.map(
    tokenize_r4,
    batched=True,
    remove_columns=train_data.column_names
)

print("Tokenizing corrected validation dataset...")

val_tokenized_r4 = val_data.map(
    tokenize_r4,
    batched=True,
    remove_columns=val_data.column_names
)

data_collator_r4 = DataCollatorForLanguageModeling(
    tokenizer=tokenizer_r4,
    mlm=False
)

steps_per_epoch_r4 = math.ceil(
    len(train_tokenized_r4)
    / BATCH_SIZE
    / GRAD_ACCUM
)

total_steps_r4 = (
    steps_per_epoch_r4
    * NUM_EPOCHS
)

warmup_steps_r4 = math.ceil(
    total_steps_r4
    * WARMUP_RATIO
)

ta_params = inspect.signature(
    TrainingArguments.__init__
).parameters

if "eval_strategy" in ta_params:
    eval_key_r4 = "eval_strategy"
elif "evaluation_strategy" in ta_params:
    eval_key_r4 = "evaluation_strategy"
else:
    raise RuntimeError(
        "TrainingArguments has no supported evaluation strategy."
    )

R4_CHECKPOINT_DIR = (
    f"{CHECKPOINT_DIR}/"
    "R4_mistral7b_qlora_CONTEXT"
)

training_kwargs_r4 = {
    "output_dir":
        R4_CHECKPOINT_DIR,
    "num_train_epochs":
        NUM_EPOCHS,
    "per_device_train_batch_size":
        BATCH_SIZE,
    "per_device_eval_batch_size":
        1,
    "gradient_accumulation_steps":
        GRAD_ACCUM,
    "learning_rate":
        LEARNING_RATE,
    "lr_scheduler_type":
        "cosine",
    "warmup_steps":
        warmup_steps_r4,
    "bf16":
        BF16_OK,
    "fp16":
        not BF16_OK,
    "logging_steps":
        50,
    "save_strategy":
        "epoch",
    "save_total_limit":
        2,
    "load_best_model_at_end":
        True,
    "metric_for_best_model":
        "eval_loss",
    "greater_is_better":
        False,
    "gradient_checkpointing":
        True,
    "gradient_checkpointing_kwargs": {
        "use_reentrant": False
    },
    "optim":
        "paged_adamw_8bit",
    "seed":
        SEED,
    "data_seed":
        SEED,
    "report_to":
        "none"
}

training_kwargs_r4[
    eval_key_r4
] = "epoch"

train_args_r4 = TrainingArguments(
    **training_kwargs_r4
)

trainer_r4 = Trainer(
    model=model_r4,
    args=train_args_r4,
    train_dataset=train_tokenized_r4,
    eval_dataset=val_tokenized_r4,
    data_collator=data_collator_r4
)

print("\nTraining schedule:")
print("Steps per epoch:", steps_per_epoch_r4)
print("Total optimizer steps:", total_steps_r4)
print("Warmup steps:", warmup_steps_r4)

print("\n✓ R4 QLoRA Trainer created successfully.")
print("✓ Fresh run — no old checkpoint resume.")
print("✓ Continue to Cell 17.")

========================================================================
R4 — MISTRAL-7B QLoRA + CORRECTED CONTEXT
========================================================================

Loading native MistralForCausalLM in 4-bit NF4...

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Allocated VRAM after model load: 4.107 GB
✓ Target modules confirmed: ['q_proj', 'k_proj', 'v_proj', 'o_proj']
trainable params: 13,631,488 || all params: 7,255,363,584 || trainable%: 0.1879

Trainable parameters: 13,631,488
Total parameters: 3,765,702,656
Trainable percentage: 0.3620%
✓ Trainable parameter count matches previous Mistral run.

Tokenizing corrected training dataset...

Map:   0%|          | 0/3018 [00:00<?, ? examples/s]

Tokenizing corrected validation dataset...

Map:   0%|          | 0/957 [00:00<?, ? examples/s]

Training schedule:
Steps per epoch: 189
Total optimizer steps: 567
Warmup steps: 18

✓ R4 QLoRA Trainer created successfully.
✓ Fresh run — no old checkpoint resume.
✓ Continue to Cell 17.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 17 — TRAIN R4 MISTRAL QLoRA + SAVE ADAPTER
# ═══════════════════════════════════════════════════════════

torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

r4_train_start = time.perf_counter()

print("=" * 72)
print("STARTING MISTRAL-7B QLoRA TRAINING")
print("=" * 72)
print(f"Training examples: {len(train_tokenized_r4):,}")
print(f"Epochs: {NUM_EPOCHS}")
print(f"Effective batch: {EFFECTIVE_BATCH}")
print(f"Learning rate: {LEARNING_RATE}")

train_output_r4 = trainer_r4.train()

torch.cuda.synchronize()

r4_train_seconds = (
    time.perf_counter() - r4_train_start
)

r4_train_mins = (
    r4_train_seconds / 60
)

r4_peak_train_vram = (
    torch.cuda.max_memory_allocated() / 1024**3
)

print("\n" + "=" * 62)
print("MISTRAL-7B QLoRA TRAINING COMPLETE")
print("=" * 62)
print(f"Training time: {r4_train_mins:.2f} min")
print(f"Peak training VRAM: {r4_peak_train_vram:.3f} GB")

R4_ADAPTER_PATH = (
    f"{ADAPTER_DIR}/"
    "R4_mistral7b_qlora_CONTEXT"
)

model_r4.save_pretrained(
    R4_ADAPTER_PATH
)

tokenizer_r4.save_pretrained(
    R4_ADAPTER_PATH
)

print("\nQLoRA adapter saved:")
print(R4_ADAPTER_PATH)
print("✓ Continue to Cell 18.")

========================================================================
STARTING MISTRAL-7B QLoRA TRAINING
========================================================================
Training examples: 3,018
Epochs: 3
Effective batch: 16
Learning rate: 0.0002

==============================================================
MISTRAL-7B QLoRA TRAINING COMPLETE
==============================================================
Training time: 31.41 min
Peak training VRAM: 6.733 GB

QLoRA adapter saved:
/content/drive/MyDrive/MR603_Thesis/adapters/R4_mistral7b_qlora_CONTEXT
✓ Continue to Cell 18.

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 18 — EVALUATE + SAVE R4 MISTRAL QLoRA
# ═══════════════════════════════════════════════════════════

model_r4.config.use_cache = True
model_r4.eval()

results_r4 = run_evaluation(
    model=model_r4,
    tokenizer=tokenizer_r4,
    test_data=test_data,
    references=references,
    condition_name=
        "R4_Mistral7B_QLoRA_CONTEXT"
)

results_r4.update({
    "model":
        "Mistral-7B",
    "method":
        "QLoRA",
    "parameters":
        "7B",
    "precision":
        "4-bit NF4 + double quantisation",
    "context_mode":
        "BM25-retrieved syllabus context",
    "training_time_seconds":
        float(r4_train_seconds),
    "training_time_minutes":
        float(r4_train_mins),
    "peak_training_vram_gb":
        float(r4_peak_train_vram),
    "trainable_parameters":
        int(trainable_r4),
    "trainable_percentage":
        float(trainable_pct_r4)
})

print("\nRunning native question-type analysis...")

strat_r4 = stratified_analysis(
    predictions=
        results_r4["predictions"],
    test_raw=
        dataset["test"],
    condition_name=
        "R4_Mistral7B_QLoRA_CONTEXT"
)

results_r4["stratified"] = strat_r4
results_r4["stratified_em"] = strat_r4

save_r4 = {
    k: v
    for k, v in results_r4.items()
    if k not in [
        "predictions",
        "latencies"
    ]
}

R4_RESULT_PATH = (
    f"{RESULTS_DIR}/"
    "R4_mistral7b_qlora_CONTEXT.json"
)

with open(
    R4_RESULT_PATH,
    "w"
) as f:
    json.dump(
        save_r4,
        f,
        indent=2
    )

R4_PRED_JSONL = (
    f"{RESULTS_DIR}/"
    "R4_mistral7b_qlora_CONTEXT_predictions.jsonl"
)

with open(
    R4_PRED_JSONL,
    "w",
    encoding="utf-8"
) as f:

    for i, prediction in enumerate(
        results_r4["predictions"]
    ):

        raw = dataset["test"][i]

        row = {
            "id":
                str(i),
            "syllabus_name":
                raw["syllabus_name"],
            "question_type":
                raw["question_type"],
            "question":
                raw["question"],
            "reference_answer":
                get_answer(raw),
            "prediction":
                prediction,
            "latency_ms":
                results_r4["latencies"][i]
        }

        f.write(
            json.dumps(
                row,
                ensure_ascii=False
            ) + "\n"
        )

R4_PRED_CSV = (
    f"{RESULTS_DIR}/"
    "R4_mistral7b_qlora_CONTEXT_predictions.csv"
)

pd.DataFrame({
    "Question":
        [
            ex.get("question", "")
            for ex in dataset["test"]
        ],
    "Question_Type":
        [
            ex.get("question_type", "unknown")
            for ex in dataset["test"]
        ],
    "Reference":
        [
            get_answer(ex)
            for ex in dataset["test"]
        ],
    "Prediction":
        results_r4["predictions"],
    "Latency_ms":
        results_r4["latencies"]
}).to_csv(
    R4_PRED_CSV,
    index=False
)

print("\n" + "=" * 62)
print("MISTRAL-7B QLoRA CORRECTED RESULTS")
print("=" * 62)
print(f"Exact Match: {results_r4['em']:.3f}%")
print(f"F1 Score: {results_r4['f1']:.3f}%")
print(f"Avg Latency: {results_r4['avg_latency_ms']:.3f} ms/sample")
print(f"Median Latency: {results_r4['median_latency_ms']:.3f} ms/sample")
print(f"Peak Eval VRAM: {results_r4['peak_vram_gb']:.3f} GB")
print(f"Training Time: {r4_train_mins:.2f} min")
print(f"Peak Training VRAM: {r4_peak_train_vram:.3f} GB")

print("\nRQ1 CHECK — Mistral QLoRA vs corrected Qwen")
print(f"Qwen zero-shot + context F1: {QWEN_ZERO_F1:.3f}%")

if "QWEN_FEW_F1" in globals():
    print(f"Qwen 2-shot + context F1: {QWEN_FEW_F1:.3f}%")

print(f"Mistral QLoRA + context F1: {results_r4['f1']:.3f}%")
print(f"Gap to Qwen zero-shot: {results_r4['f1'] - QWEN_ZERO_F1:+.3f} pp")

if "QWEN_FEW_F1" in globals():
    print(f"Gap to Qwen 2-shot: {results_r4['f1'] - QWEN_FEW_F1:+.3f} pp")

print("\nResults saved:", R4_RESULT_PATH)
print("Predictions JSONL:", R4_PRED_JSONL)
print("Predictions CSV:", R4_PRED_CSV)

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 19 — CLEAR R4 + RELOAD SAVED R3/R4 FROM DISK
# Disk reload makes final analysis independent of runtime state.
# ═══════════════════════════════════════════════════════════

for name in [
    "trainer_r4",
    "model_r4",
    "train_tokenized_r4",
    "val_tokenized_r4"
]:
    if name in globals():
        del globals()[name]

gc.collect()
torch.cuda.empty_cache()

with open(
    f"{RESULTS_DIR}/"
    "R3_mistral7b_lora_CONTEXT.json",
    "r"
) as f:
    r3_saved = json.load(f)

with open(
    f"{RESULTS_DIR}/"
    "R4_mistral7b_qlora_CONTEXT.json",
    "r"
) as f:
    r4_saved = json.load(f)

print("=" * 72)
print("SAVED MISTRAL RESULTS RELOADED")
print("=" * 72)
print(f"R3 LoRA F1:  {r3_saved['f1']:.3f}%")
print(f"R4 QLoRA F1: {r4_saved['f1']:.3f}%")
print(f"Qwen zero-shot + context F1: {QWEN_ZERO_F1:.3f}%")

if "QWEN_FEW_F1" in globals():
    print(f"Qwen 2-shot + context F1: {QWEN_FEW_F1:.3f}%")

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 20 — MISTRAL LoRA VS QLoRA + QWEN COMPARISON
# Uses SAVED disk results, not transient runtime objects.
# ═══════════════════════════════════════════════════════════

print("=" * 76)
print("MISTRAL-7B — CORRECTED CONTEXT COMPARISON")
print("=" * 76)

print("\nPERFORMANCE")
print(f"LoRA EM: {r3_saved['em']:.3f}%")
print(f"QLoRA EM: {r4_saved['em']:.3f}%")
print(f"LoRA F1: {r3_saved['f1']:.3f}%")
print(f"QLoRA F1: {r4_saved['f1']:.3f}%")
print(
    f"LoRA - QLoRA F1: "
    f"{r3_saved['f1'] - r4_saved['f1']:+.3f} pp"
)

print(f"Qwen zero-shot + context: {QWEN_ZERO_F1:.3f}%")

if "QWEN_FEW_F1" in globals():
    print(f"Qwen 2-shot + context: {QWEN_FEW_F1:.3f}%")

print("\nGAPS TO QWEN ZERO-SHOT")
print(f"LoRA: {r3_saved['f1'] - QWEN_ZERO_F1:+.3f} pp")
print(f"QLoRA: {r4_saved['f1'] - QWEN_ZERO_F1:+.3f} pp")

if "QWEN_FEW_F1" in globals():
    print("\nGAPS TO QWEN 2-SHOT")
    print(f"LoRA: {r3_saved['f1'] - QWEN_FEW_F1:+.3f} pp")
    print(f"QLoRA: {r4_saved['f1'] - QWEN_FEW_F1:+.3f} pp")

print("\nEFFICIENCY")
print(f"LoRA latency: {r3_saved['avg_latency_ms']:.3f} ms")
print(f"QLoRA latency: {r4_saved['avg_latency_ms']:.3f} ms")
print(f"LoRA eval VRAM: {r3_saved['peak_vram_gb']:.3f} GB")
print(f"QLoRA eval VRAM: {r4_saved['peak_vram_gb']:.3f} GB")
print(f"LoRA train time: {r3_saved['training_time_minutes']:.2f} min")
print(f"QLoRA train time: {r4_saved['training_time_minutes']:.2f} min")
print(f"LoRA train VRAM: {r3_saved['peak_training_vram_gb']:.3f} GB")
print(f"QLoRA train VRAM: {r4_saved['peak_training_vram_gb']:.3f} GB")

print("\nNote:")
print(
    "Qwen2.5-14B is a larger prompting reference, "
    "not an adaptation-matched baseline."
)

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 21 — RQ2 QUESTION-TYPE COMPARISON
# Strong validation prevents a silent empty table.
# ═══════════════════════════════════════════════════════════

expected_types = {
    "multi factual",
    "multi reasoning",
    "no answer",
    "single factual",
    "single reasoning",
    "summarization",
    "yes/no"
}

strat_l = r3_saved.get(
    "stratified",
    r3_saved.get(
        "stratified_em",
        {}
    )
)

strat_q = r4_saved.get(
    "stratified",
    r4_saved.get(
        "stratified_em",
        {}
    )
)

assert strat_l, "R3 stratified results are empty."
assert strat_q, "R4 stratified results are empty."

assert expected_types.issubset(
    set(strat_l.keys())
), (
    "R3 is missing one or more native SyllabusQA question types."
)

assert expected_types.issubset(
    set(strat_q.keys())
), (
    "R4 is missing one or more native SyllabusQA question types."
)

rq2_rows = []

for q_type in sorted(expected_types):

    lora_values = strat_l[q_type]
    qlora_values = strat_q[q_type]

    rq2_rows.append({
        "Question_Type":
            q_type,
        "N":
            lora_values["count"],
        "LoRA_EM_percent":
            lora_values["exact_match"],
        "QLoRA_EM_percent":
            qlora_values["exact_match"],
        "Delta_EM_LoRA_minus_QLoRA":
            (
                lora_values["exact_match"]
                -
                qlora_values["exact_match"]
            ),
        "LoRA_F1_percent":
            lora_values["f1"],
        "QLoRA_F1_percent":
            qlora_values["f1"],
        "Delta_F1_LoRA_minus_QLoRA":
            (
                lora_values["f1"]
                -
                qlora_values["f1"]
            )
    })

mistral_rq2 = pd.DataFrame(rq2_rows)

assert len(mistral_rq2) == 7, (
    "RQ2 table should contain exactly 7 question types."
)

print("=" * 78)
print("RQ2 — MISTRAL-7B LoRA VS QLoRA BY QUESTION TYPE")
print("=" * 78)

display(
    mistral_rq2.round(3)
)

MISTRAL_RQ2_PATH = (
    f"{RESULTS_DIR}/"
    "Mistral7B_CONTEXT_RQ2_QuestionType_Results.csv"
)

mistral_rq2.to_csv(
    MISTRAL_RQ2_PATH,
    index=False
)

print("\nSaved:")
print(MISTRAL_RQ2_PATH)

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 22 — FINAL CORRECTED MISTRAL RESULTS
# ═══════════════════════════════════════════════════════════

mistral_rows = []

r3_row = {
    "Notebook":
        3,
    "Condition":
        "R3_Mistral7B_LoRA_CONTEXT",
    "Model":
        "Mistral-7B",
    "Method":
        "LoRA",
    "Parameters_B":
        7.0,
    "Base_Precision":
        r3_saved["precision"],
    "Context_Mode":
        "BM25-retrieved syllabus context",
    "EM_percent":
        r3_saved["em"],
    "F1_percent":
        r3_saved["f1"],
    "Training_Time_min":
        r3_saved["training_time_minutes"],
    "Avg_Latency_ms":
        r3_saved["avg_latency_ms"],
    "Median_Latency_ms":
        r3_saved["median_latency_ms"],
    "Peak_Train_VRAM_GB":
        r3_saved["peak_training_vram_gb"],
    "Peak_Eval_VRAM_GB":
        r3_saved["peak_vram_gb"],
    "Trainable_Params":
        r3_saved["trainable_parameters"],
    "Trainable_Pct":
        r3_saved["trainable_percentage"],
    "Gap_Qwen_ZeroShot_F1_pp":
        r3_saved["f1"] - QWEN_ZERO_F1
}

if "QWEN_FEW_F1" in globals():
    r3_row["Gap_Qwen_2Shot_F1_pp"] = (
        r3_saved["f1"] - QWEN_FEW_F1
    )

mistral_rows.append(r3_row)

r4_row = {
    "Notebook":
        3,
    "Condition":
        "R4_Mistral7B_QLoRA_CONTEXT",
    "Model":
        "Mistral-7B",
    "Method":
        "QLoRA",
    "Parameters_B":
        7.0,
    "Base_Precision":
        "4-bit NF4 + double quantisation",
    "Context_Mode":
        "BM25-retrieved syllabus context",
    "EM_percent":
        r4_saved["em"],
    "F1_percent":
        r4_saved["f1"],
    "Training_Time_min":
        r4_saved["training_time_minutes"],
    "Avg_Latency_ms":
        r4_saved["avg_latency_ms"],
    "Median_Latency_ms":
        r4_saved["median_latency_ms"],
    "Peak_Train_VRAM_GB":
        r4_saved["peak_training_vram_gb"],
    "Peak_Eval_VRAM_GB":
        r4_saved["peak_vram_gb"],
    "Trainable_Params":
        r4_saved["trainable_parameters"],
    "Trainable_Pct":
        r4_saved["trainable_percentage"],
    "Gap_Qwen_ZeroShot_F1_pp":
        r4_saved["f1"] - QWEN_ZERO_F1
}

if "QWEN_FEW_F1" in globals():
    r4_row["Gap_Qwen_2Shot_F1_pp"] = (
        r4_saved["f1"] - QWEN_FEW_F1
    )

mistral_rows.append(r4_row)

mistral_final = pd.DataFrame(
    mistral_rows
)

MISTRAL_FINAL_PATH = (
    f"{RESULTS_DIR}/"
    "Mistral7B_CONTEXT_Final_Results.csv"
)

mistral_final.to_csv(
    MISTRAL_FINAL_PATH,
    index=False
)

display(
    mistral_final.round(3)
)

print("\nSaved final Mistral results:")
print(MISTRAL_FINAL_PATH)

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 23 — SAVE MISTRAL EXPERIMENT CONFIGURATION
# ═══════════════════════════════════════════════════════════

mistral_config = {
    "notebook":
        "3_Mistral7B_CONTEXT",
    "model":
        MODEL_ID,
    "dataset":
        "SyllabusQA",
    "dataset_split": {
        "train":
            3018,
        "validation":
            957,
        "test":
            1103
    },
    "context_pipeline": {
        "method":
            "BM25 syllabus-context retrieval",
        "chunk_words":
            90,
        "chunk_overlap":
            30,
        "top_k":
            2,
        "max_sequence_length":
            MAX_SEQ_LENGTH
    },
    "seed":
        SEED,
    "gpu":
        GPU_NAME,
    "gpu_vram_gb":
        GPU_VRAM,
    "lora_rank":
        LORA_R,
    "lora_alpha":
        LORA_ALPHA,
    "lora_dropout":
        LORA_DROPOUT,
    "target_modules":
        LORA_TARGET_MODULES,
    "learning_rate":
        LEARNING_RATE,
    "epochs":
        NUM_EPOCHS,
    "batch_size":
        BATCH_SIZE,
    "gradient_accumulation":
        GRAD_ACCUM,
    "effective_batch":
        EFFECTIVE_BATCH,
    "warmup_ratio_design":
        WARMUP_RATIO,
    "optimizer":
        "paged_adamw_8bit",
    "qlora_quantization":
        "4-bit NF4 + double quantisation",
    "metrics": [
        "Exact Match",
        "token-level F1",
        "average inference latency",
        "median inference latency",
        "peak evaluation VRAM",
        "training time",
        "peak training VRAM"
    ],
    "qwen_reference": {
        "zero_shot_context_file":
            "REF_qwen14b_zeroshot_CONTEXT.json",
        "two_shot_context_file":
            "REF_qwen14b_2shot_CONTEXT.json"
    }
}

MISTRAL_CONFIG_PATH = (
    f"{RESULTS_DIR}/"
    "Mistral7B_CONTEXT_Experiment_Config.json"
)

with open(
    MISTRAL_CONFIG_PATH,
    "w"
) as f:
    json.dump(
        mistral_config,
        f,
        indent=2
    )

print("Saved experiment configuration:")
print(MISTRAL_CONFIG_PATH)

In [ ]:
# ═══════════════════════════════════════════════════════════
# CELL 24 — FINAL MISTRAL FILE CHECK + CLEANUP
# ═══════════════════════════════════════════════════════════

required_files = [
    "REF_qwen14b_zeroshot_CONTEXT.json",

    "R3_mistral7b_lora_CONTEXT.json",
    "R3_mistral7b_lora_CONTEXT_predictions.jsonl",
    "R3_mistral7b_lora_CONTEXT_predictions.csv",

    "R4_mistral7b_qlora_CONTEXT.json",
    "R4_mistral7b_qlora_CONTEXT_predictions.jsonl",
    "R4_mistral7b_qlora_CONTEXT_predictions.csv",

    "Mistral7B_CONTEXT_RQ2_QuestionType_Results.csv",
    "Mistral7B_CONTEXT_Final_Results.csv",
    "Mistral7B_CONTEXT_Experiment_Config.json"
]

if "QWEN_FEW_F1" in globals():
    required_files.append(
        "REF_qwen14b_2shot_CONTEXT.json"
    )

print("=" * 80)
print("FINAL MISTRAL-7B CORRECTED FILE CHECK")
print("=" * 80)

all_good = True

for filename in required_files:

    path = f"{RESULTS_DIR}/{filename}"

    if os.path.exists(path):

        size_kb = (
            os.path.getsize(path) / 1024
        )

        print(
            f"FOUND   {filename} "
            f"({size_kb:.1f} KB)"
        )

    else:

        print(
            f"MISSING {filename}"
        )

        all_good = False

print("\nAdapters:")

for adapter_name in [
    "R3_mistral7b_lora_CONTEXT",
    "R4_mistral7b_qlora_CONTEXT"
]:

    adapter_path = (
        f"{ADAPTER_DIR}/"
        f"{adapter_name}"
    )

    if os.path.isdir(adapter_path):

        print(
            "FOUND:",
            adapter_name
        )

    else:

        print(
            "MISSING:",
            adapter_name
        )

        all_good = False

if all_good:

    print("\n" + "=" * 72)
    print("✓ MISTRAL-7B PHASE COMPLETE")
    print("✓ Corrected LoRA + context saved")
    print("✓ Corrected QLoRA + context saved")
    print("✓ Corrected Qwen references linked")
    print("✓ Seven-type RQ2 table validated and saved")
    print("✓ Final Mistral results saved")
    print("=" * 72)

else:

    print(
        "\nSome required outputs are missing. "
        "Do not move to the final cross-model notebook yet."
    )

gc.collect()
torch.cuda.empty_cache()

free_vram = (
    torch.cuda.get_device_properties(0).total_memory
    - torch.cuda.memory_allocated()
) / 1024**3

print(
    f"\nGPU cleanup complete. "
    f"Free VRAM: {free_vram:.2f} GB"
)

print(
    "\nAfter this, the corrected Gemma, Phi and Mistral "
    "model phases are ready for the final cross-model analysis."
)

## Recovery after a Colab disconnect

The notebook uses new `_CONTEXT` checkpoint and result names, so old blank-context runs are never mixed with the corrected experiment.

If the runtime disconnects **after R3 LoRA evaluation is fully saved**, rerun Cells 2–11 to restore environment/data/helpers/Qwen, load:

```python
with open(f"{RESULTS_DIR}/R3_mistral7b_lora_CONTEXT.json") as f:
    r3_saved = json.load(f)
```

and continue from Cell 16 (R4 QLoRA setup).

If the runtime disconnects **after R4 QLoRA evaluation is saved**, rerun Cells 2–11, then run Cells 19–24 only.

For final comparisons, use only `_CONTEXT` result files.