In [1]:
# ═══════════════════════════════════════════════════════════
# CELL 1 — INSTALL KNOWN-WORKING STACK
# Run ONCE, then restart runtime/session.
# ═══════════════════════════════════════════════════════════

!pip uninstall -y accelerate >/dev/null 2>&1

!pip install -q --no-cache-dir \
    "transformers==5.16.1" \
    "accelerate==1.15.0" \
    "peft==0.12.0" \
    "bitsandbytes==0.50.2" \
    "datasets" \
    "rank_bm25"

print("=" * 70)
print("INSTALLATION COMPLETE")
print("Restart runtime/session ONCE.")
print("After restart begin from Cell 2.")
print("=" * 70)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 221.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 343.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.4/296.4 kB 328.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 209.4 MB/s eta 0:00:00
======================================================================
INSTALLATION COMPLETE
Restart runtime/session ONCE.
After restart begin from Cell 2.
======================================================================

In [2]:
# ============================================================
# FIX bitsandbytes INSTALLATION
# ============================================================

!pip install -q --upgrade --no-cache-dir bitsandbytes

print("bitsandbytes install attempted.")

bitsandbytes install attempted.

In [3]:
import bitsandbytes

print("bitsandbytes version:", bitsandbytes.__version__)
print("✓ bitsandbytes import works.")

bitsandbytes version: 0.50.2
✓ bitsandbytes import works.

In [4]:
# ═══════════════════════════════════════════════════════════
# CELL 2 — IMPORTS + ENVIRONMENT CHECK
# ═══════════════════════════════════════════════════════════

import os
import gc
import json
import time
import math
import random
import string
import re
import inspect
import importlib.metadata

import numpy as np
import pandas as pd
import torch

from pathlib import Path
from collections import Counter, defaultdict

import transformers
import accelerate
import peft
import bitsandbytes
import datasets

from datasets import Dataset, DatasetDict, load_from_disk

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)

from transformers.utils import is_accelerate_available

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
    TaskType
)

assert torch.cuda.is_available(), "GPU is not enabled."

assert is_accelerate_available(), (
    "Transformers does not detect Accelerate. "
    "Confirm accelerate==1.15.0 and restart runtime."
)

GPU_NAME = torch.cuda.get_device_name(0)
GPU_VRAM = torch.cuda.get_device_properties(0).total_memory / 1024**3
BF16_OK = torch.cuda.is_bf16_supported()
TRAIN_DTYPE = torch.bfloat16 if BF16_OK else torch.float16

print("=" * 70)
print("ENVIRONMENT VERIFICATION")
print("=" * 70)

print("GPU:", GPU_NAME)
print(f"GPU VRAM: {GPU_VRAM:.2f} GB")
print("BF16 supported:", BF16_OK)
print("Training dtype:", TRAIN_DTYPE)

print("\nPackage versions:")
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)
print("PEFT:", peft.__version__)
print("BitsAndBytes:", bitsandbytes.__version__)
print("Datasets:", datasets.__version__)

print("\nAccelerate metadata:",
      importlib.metadata.version("accelerate"))

print("Transformers detects Accelerate:",
      is_accelerate_available())

print("\n✓ Environment ready.")

======================================================================
ENVIRONMENT VERIFICATION
======================================================================
GPU: NVIDIA A100-SXM4-40GB
GPU VRAM: 39.49 GB
BF16 supported: True
Training dtype: torch.bfloat16

Package versions:
Transformers: 5.16.1
Accelerate: 1.15.0
PEFT: 0.12.0
BitsAndBytes: 0.50.2
Datasets: 4.8.5

Accelerate metadata: 1.15.0
Transformers detects Accelerate: True

✓ Environment ready.

In [5]:
# ═══════════════════════════════════════════════════════════
# CELL 3 — REPRODUCIBILITY
# ═══════════════════════════════════════════════════════════

SEED = 42

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(SEED)

print("✓ Random seed fixed at:", SEED)

✓ Random seed fixed at: 42

In [6]:
# ═══════════════════════════════════════════════════════════
# CELL 4 — GOOGLE DRIVE + PATHS
# ═══════════════════════════════════════════════════════════

from google.colab import drive

drive.mount("/content/drive")

BASE_DIR = "/content/drive/MyDrive/MR603_Thesis"

RESULTS_DIR = f"{BASE_DIR}/results"
ADAPTER_DIR = f"{BASE_DIR}/adapters"
CHECKPOINT_DIR = f"{BASE_DIR}/checkpoints"

RECOVERY_DIR = f"{BASE_DIR}/recovery_gemma_context"

for path in [
    RESULTS_DIR,
    ADAPTER_DIR,
    CHECKPOINT_DIR
]:
    os.makedirs(path, exist_ok=True)

test_file = f"{RESULTS_DIR}/.phi_write_test"

with open(test_file, "w") as f:
    f.write("ok")

os.remove(test_file)

print("=" * 70)
print("GOOGLE DRIVE READY")
print("=" * 70)

print("BASE_DIR:", BASE_DIR)
print("RESULTS_DIR:", RESULTS_DIR)
print("ADAPTER_DIR:", ADAPTER_DIR)
print("CHECKPOINT_DIR:", CHECKPOINT_DIR)
print("RECOVERY_DIR:", RECOVERY_DIR)

print("\n✓ Drive is writable.")

Mounted at /content/drive
======================================================================
GOOGLE DRIVE READY
======================================================================
BASE_DIR: /content/drive/MyDrive/MR603_Thesis
RESULTS_DIR: /content/drive/MyDrive/MR603_Thesis/results
ADAPTER_DIR: /content/drive/MyDrive/MR603_Thesis/adapters
CHECKPOINT_DIR: /content/drive/MyDrive/MR603_Thesis/checkpoints
RECOVERY_DIR: /content/drive/MyDrive/MR603_Thesis/recovery_gemma_context

✓ Drive is writable.

In [7]:
# ═══════════════════════════════════════════════════════════
# CELL 5 — HUGGING FACE LOGIN
# ═══════════════════════════════════════════════════════════

from huggingface_hub import login
from google.colab import userdata

try:
    hf_token = userdata.get("HF_TOKEN")
    login(token=hf_token)
    print("✓ Logged in using Colab HF_TOKEN.")
except Exception as e:
    print("Could not use HF_TOKEN secret:", e)

    hf_token = input("Paste Hugging Face token: ")

    login(token=hf_token)

    print("✓ Logged in manually.")

Could not use HF_TOKEN secret: Secret HF_TOKEN does not exist.
Paste Hugging Face token: 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
✓ Logged in manually.

In [8]:
# ═══════════════════════════════════════════════════════════
# CELL 6 — PHI-3 MINI EXPERIMENT CONFIGURATION
# ═══════════════════════════════════════════════════════════

MODEL_ID = "microsoft/Phi-3-mini-4k-instruct"

MODEL_NAME = "Phi-3 Mini"

QWEN_MODEL_ID = "Qwen/Qwen2.5-14B-Instruct"

LORA_R = 16

LORA_ALPHA = 32

LORA_DROPOUT = 0.05

# Phi-3 uses combined Q/K/V projection
LORA_TARGET_MODULES = [
    "qkv_proj",
    "o_proj"
]

LEARNING_RATE = 2e-4

NUM_EPOCHS = 3

BATCH_SIZE = 4

GRAD_ACCUM = 4

EFFECTIVE_BATCH = (
    BATCH_SIZE * GRAD_ACCUM
)

MAX_SEQ_LENGTH = 512

WARMUP_RATIO = 0.03

MAX_NEW_TOKENS = 64

print("=" * 70)
print("PHI-3 MINI EXPERIMENTAL CONFIGURATION")
print("=" * 70)

print("SLM model:", MODEL_ID)
print("Reference model:", QWEN_MODEL_ID)

print("\nLoRA / QLoRA configuration:")
print("Rank:", LORA_R)
print("Alpha:", LORA_ALPHA)
print("Scaling ratio:", LORA_ALPHA / LORA_R)
print("Dropout:", LORA_DROPOUT)
print("Target modules:", LORA_TARGET_MODULES)

print("\nTraining:")
print("Learning rate:", LEARNING_RATE)
print("Epochs:", NUM_EPOCHS)
print("Per-device batch:", BATCH_SIZE)
print("Gradient accumulation:", GRAD_ACCUM)
print("Effective batch:", EFFECTIVE_BATCH)
print("Max seq length:", MAX_SEQ_LENGTH)
print("Warmup ratio:", WARMUP_RATIO)
print("Max new tokens:", MAX_NEW_TOKENS)
print("Seed:", SEED)

======================================================================
PHI-3 MINI EXPERIMENTAL CONFIGURATION
======================================================================
SLM model: microsoft/Phi-3-mini-4k-instruct
Reference model: Qwen/Qwen2.5-14B-Instruct

LoRA / QLoRA configuration:
Rank: 16
Alpha: 32
Scaling ratio: 2.0
Dropout: 0.05
Target modules: ['qkv_proj', 'o_proj']

Training:
Learning rate: 0.0002
Epochs: 3
Per-device batch: 4
Gradient accumulation: 4
Effective batch: 16
Max seq length: 512
Warmup ratio: 0.03
Max new tokens: 64
Seed: 42

In [9]:
# ═══════════════════════════════════════════════════════════
# CELL 7 — LOAD EXACT CORRECTED CONTEXT DATASET
# ═══════════════════════════════════════════════════════════

corrected_path = (
    f"{RECOVERY_DIR}/corrected_data"
)

raw_path = (
    f"{RECOVERY_DIR}/raw_dataset"
)

assert os.path.exists(
    corrected_path
), (
    "Corrected dataset recovery folder not found. "
    "Complete/save the updated Gemma corrected dataset first."
)

assert os.path.exists(
    raw_path
), (
    "Raw dataset recovery folder not found."
)

print(
    "Loading exact corrected datasets "
    "saved during Gemma implementation..."
)

corrected_data = load_from_disk(
    corrected_path
)

dataset = load_from_disk(
    raw_path
)

train_data = (
    corrected_data["train"]
)

val_data = (
    corrected_data["validation"]
)

test_data = (
    corrected_data["test"]
)

print("\n" + "=" * 70)
print("CORRECTED DATASET CHECK")
print("=" * 70)

print(
    "Train:",
    len(train_data)
)

print(
    "Validation:",
    len(val_data)
)

print(
    "Test:",
    len(test_data)
)

print(
    "Raw test:",
    len(dataset["test"])
)

assert len(train_data) == 3018
assert len(val_data) == 957
assert len(test_data) == 1103
assert len(dataset["test"]) == 1103

train_empty = sum(
    1
    for ex in train_data
    if "Syllabus context:\n\n"
    in ex["text"]
)

test_empty = sum(
    1
    for ex in test_data
    if "Syllabus context:\n\n"
    in ex["prompt"]
)

assert train_empty == 0, (
    f"Blank training contexts: {train_empty}"
)

assert test_empty == 0, (
    f"Blank test contexts: {test_empty}"
)

print(
    "\n✓ Dataset sizes correct."
)

print(
    "✓ All train/test examples contain syllabus context."
)

print(
    "\nSample corrected test prompt:\n"
)

print(
    test_data[0]["prompt"][:900]
)

Loading exact corrected datasets saved during Gemma implementation...

======================================================================
CORRECTED DATASET CHECK
======================================================================
Train: 3018
Validation: 957
Test: 1103
Raw test: 1103

✓ Dataset sizes correct.
✓ All train/test examples contain syllabus context.

Sample corrected test prompt:

Syllabus context:
Extra Credit: Four extra credit opportunities will be available during the semester. Three of these are exam reflections and the fourth is the end-of-course survey. Each one has a maximum value of 0.3 percentage points towards your final grade. Additional details will be provided as each assignment becomes available. Final Grading Scale: Final grades are rounded to the tenth and then assigned according to this scale. A 93.00 100.00% B-80.00 82.99% D+ 67.00 69.99% A-90.00 92.99% C+ 77.00 79.99% D 60.00 66.99% B+ 87.00 89.99% C 73.00 76.99% F <59.99
miss some assignments and classes are built into the course and should cover most circumstances, but if you have an unexpected situation or assignment extensions are part of your accommodations, contact me as soon as possible to discuss an extension. Note: Because of the course flexibility, extension requests should be infrequ

In [10]:
# ═══════════════════════════════════════════════════════════
# CELL 8 — LOCAL SQuAD EM + TOKEN-LEVEL F1
# ═══════════════════════════════════════════════════════════

def get_answer(example):

    answer = example.get(
        "answer",
        ""
    )

    if isinstance(
        answer,
        dict
    ):

        texts = answer.get(
            "text",
            []
        )

        return (
            texts[0].strip()
            if texts
            else ""
        )

    if isinstance(
        answer,
        list
    ):

        return (
            str(answer[0]).strip()
            if answer
            else ""
        )

    return (
        str(answer).strip()
        if answer is not None
        else ""
    )


def normalize_answer(s):

    def remove_articles(text):

        return re.sub(
            r"\b(a|an|the)\b",
            " ",
            text
        )

    def white_space_fix(text):

        return " ".join(
            text.split()
        )

    def remove_punc(text):

        exclude = set(
            string.punctuation
        )

        return "".join(
            ch
            for ch in text
            if ch not in exclude
        )

    return white_space_fix(
        remove_articles(
            remove_punc(
                str(s).lower()
            )
        )
    )


def exact_match_score(
    prediction,
    ground_truth
):

    return float(
        normalize_answer(
            prediction
        )
        ==
        normalize_answer(
            ground_truth
        )
    )


def f1_score(
    prediction,
    ground_truth
):

    prediction_tokens = (
        normalize_answer(
            prediction
        ).split()
    )

    ground_truth_tokens = (
        normalize_answer(
            ground_truth
        ).split()
    )

    if (
        len(prediction_tokens) == 0
        or
        len(ground_truth_tokens) == 0
    ):

        return float(
            prediction_tokens
            ==
            ground_truth_tokens
        )

    common = (
        Counter(
            prediction_tokens
        )
        &
        Counter(
            ground_truth_tokens
        )
    )

    num_same = sum(
        common.values()
    )

    if num_same == 0:
        return 0.0

    precision = (
        num_same
        /
        len(prediction_tokens)
    )

    recall = (
        num_same
        /
        len(ground_truth_tokens)
    )

    return (
        2
        * precision
        * recall
        /
        (
            precision
            +
            recall
        )
    )


class LocalSquadMetric:

    def compute(
        self,
        predictions,
        references
    ):

        reference_dict = {
            str(ref["id"]):
                ref["answers"]["text"]
            for ref in references
        }

        exact_scores = []

        f1_scores = []

        for pred in predictions:

            pred_id = str(
                pred["id"]
            )

            prediction_text = (
                pred[
                    "prediction_text"
                ]
            )

            ground_truths = (
                reference_dict.get(
                    pred_id,
                    [""]
                )
            )

            if not ground_truths:
                ground_truths = [""]

            exact_scores.append(
                max(
                    exact_match_score(
                        prediction_text,
                        gt
                    )
                    for gt
                    in ground_truths
                )
            )

            f1_scores.append(
                max(
                    f1_score(
                        prediction_text,
                        gt
                    )
                    for gt
                    in ground_truths
                )
            )

        return {
            "exact_match":
                100.0
                * sum(
                    exact_scores
                )
                /
                len(
                    exact_scores
                ),

            "f1":
                100.0
                * sum(
                    f1_scores
                )
                /
                len(
                    f1_scores
                )
        }


squad_metric = (
    LocalSquadMetric()
)


references = [

    {
        "id":
            str(i),

        "answers": {

            "text":
                [
                    get_answer(
                        example
                    )
                ],

            "answer_start":
                [0]
        }
    }

    for i, example
    in enumerate(
        dataset["test"]
    )
]


print(
    "✓ Local SQuAD-style metric ready."
)

print(
    "References:",
    len(references)
)

✓ Local SQuAD-style metric ready.
References: 1103

In [11]:
# ═══════════════════════════════════════════════════════════
# CELL 9 — COMMON EVALUATION FUNCTION
# ═══════════════════════════════════════════════════════════

def run_evaluation(
    model,
    tokenizer,
    test_data,
    references,
    condition_name
):

    print(
        "\n" + "=" * 55
    )

    print(
        f"EVALUATING: "
        f"{condition_name}"
    )

    print(
        "=" * 55
    )

    print(
        f"Test examples: "
        f"{len(test_data):,}"
    )

    print(
        "Progress logged every 100 examples"
    )

    model.eval()

    torch.cuda.empty_cache()

    torch.cuda.reset_peak_memory_stats()

    all_predictions = []

    all_latencies = []

    for i, example in enumerate(
        test_data
    ):

        if i % 100 == 0:

            elapsed_min = (
                sum(all_latencies)
                / 1000
                / 60
                if all_latencies
                else 0
            )

            avg_lat = (
                sum(all_latencies)
                /
                len(all_latencies)
                if all_latencies
                else 0
            )

            print(
                f"{i:4d}/"
                f"{len(test_data)} "
                f"| {elapsed_min:.1f} min "
                f"| {avg_lat:.0f} ms/sample"
            )

        inputs = tokenizer(
            example["prompt"],
            return_tensors="pt",
            max_length=MAX_SEQ_LENGTH,
            truncation=True,
            padding=False
        ).to(
            model.device
        )

        input_length = (
            inputs["input_ids"]
            .shape[1]
        )

        torch.cuda.synchronize()

        start_time = (
            time.perf_counter()
        )

        with torch.no_grad():

            outputs = (
                model.generate(
                    **inputs,
                    max_new_tokens=
                        MAX_NEW_TOKENS,
                    do_sample=False,
                    num_beams=1,
                    pad_token_id=
                        tokenizer.pad_token_id,
                    eos_token_id=
                        tokenizer.eos_token_id
                )
            )

        torch.cuda.synchronize()

        latency_ms = (
            time.perf_counter()
            -
            start_time
        ) * 1000

        all_latencies.append(
            latency_ms
        )

        new_tokens = (
            outputs[0][
                input_length:
            ]
        )

        prediction = (
            tokenizer.decode(
                new_tokens,
                skip_special_tokens=True
            ).strip()
        )

        all_predictions.append(
            prediction
        )

    predictions_fmt = [

        {
            "id":
                str(i),

            "prediction_text":
                pred
        }

        for i, pred
        in enumerate(
            all_predictions
        )
    ]

    metrics = (
        squad_metric.compute(
            predictions=
                predictions_fmt,

            references=
                references
        )
    )

    em = float(
        metrics[
            "exact_match"
        ]
    )

    f1 = float(
        metrics[
            "f1"
        ]
    )

    avg_latency = float(
        np.mean(
            all_latencies
        )
    )

    median_latency = float(
        np.median(
            all_latencies
        )
    )

    peak_vram_gb = float(
        torch.cuda.max_memory_allocated()
        /
        1024**3
    )

    print(
        "\n" + "─" * 45
    )

    print(
        f"RESULTS: "
        f"{condition_name}"
    )

    print(
        "─" * 45
    )

    print(
        f"Exact Match:    "
        f"{em:.3f}%"
    )

    print(
        f"F1 Score:       "
        f"{f1:.3f}%"
    )

    print(
        f"Avg Latency:    "
        f"{avg_latency:.3f} ms/sample"
    )

    print(
        f"Median Latency: "
        f"{median_latency:.3f} ms/sample"
    )

    print(
        f"Peak GPU VRAM:  "
        f"{peak_vram_gb:.3f} GB"
    )

    return {

        "condition":
            condition_name,

        "em":
            em,

        "f1":
            f1,

        "avg_latency_ms":
            avg_latency,

        "median_latency_ms":
            median_latency,

        "peak_vram_gb":
            peak_vram_gb,

        "predictions":
            all_predictions,

        "latencies":
            all_latencies
    }


print(
    "✓ run_evaluation() ready."
)

✓ run_evaluation() ready.

In [12]:
# ═══════════════════════════════════════════════════════════
# CELL 10 — STRATIFIED QUESTION-TYPE ANALYSIS
# ═══════════════════════════════════════════════════════════

def stratified_analysis(
    predictions,
    test_raw,
    condition_name
):

    print(
        f"\nRunning stratified analysis: "
        f"{condition_name}"
    )

    type_preds = defaultdict(
        list
    )

    type_refs = defaultdict(
        list
    )

    type_counts = defaultdict(
        int
    )

    for i, example in enumerate(
        test_raw
    ):

        q_type = (
            example.get(
                "question_type",
                "unknown"
            )
        )

        answer_text = (
            get_answer(
                example
            )
        )

        prediction = (
            predictions[i]
            if i < len(predictions)
            else ""
        )

        type_preds[
            q_type
        ].append({

            "id":
                str(i),

            "prediction_text":
                prediction
        })

        type_refs[
            q_type
        ].append({

            "id":
                str(i),

            "answers": {

                "text":
                    [
                        answer_text
                    ],

                "answer_start":
                    [0]
            }
        })

        type_counts[
            q_type
        ] += 1

    results = {}

    print(
        f"\n{'Question Type':25s} "
        f"{'EM %':8s} "
        f"{'F1 %':8s} "
        f"{'n':5s}"
    )

    print(
        "─" * 50
    )

    for q_type in sorted(
        type_preds.keys()
    ):

        metrics = (
            squad_metric.compute(
                predictions=
                    type_preds[
                        q_type
                    ],

                references=
                    type_refs[
                        q_type
                    ]
            )
        )

        results[
            q_type
        ] = {

            "exact_match":
                float(
                    metrics[
                        "exact_match"
                    ]
                ),

            "f1":
                float(
                    metrics[
                        "f1"
                    ]
                ),

            "count":
                int(
                    type_counts[
                        q_type
                    ]
                )
        }

        print(
            f"{q_type:25s} "
            f"{metrics['exact_match']:8.3f} "
            f"{metrics['f1']:8.3f} "
            f"{type_counts[q_type]:5d}"
        )

    return results


print(
    "✓ stratified_analysis() ready."
)

✓ stratified_analysis() ready.

In [13]:
# ═══════════════════════════════════════════════════════════
# CELL 11 — LOAD CORRECTED QWEN REFERENCES
# ═══════════════════════════════════════════════════════════

zero_path = (
    f"{RESULTS_DIR}/"
    "REF_qwen14b_zeroshot_CONTEXT.json"
)

few_path = (
    f"{RESULTS_DIR}/"
    "REF_qwen14b_2shot_CONTEXT.json"
)

assert os.path.exists(
    zero_path
), (
    "Corrected Qwen zero-shot result "
    "not found."
)

with open(
    zero_path,
    "r"
) as f:

    results_qwen_zero = (
        json.load(f)
    )

QWEN_ZERO_EM = float(
    results_qwen_zero[
        "em"
    ]
)

QWEN_ZERO_F1 = float(
    results_qwen_zero[
        "f1"
    ]
)

print(
    "=" * 70
)

print(
    "CORRECTED QWEN REFERENCES"
)

print(
    "=" * 70
)

print(
    f"Qwen zero-shot + context: "
    f"EM={QWEN_ZERO_EM:.3f}% | "
    f"F1={QWEN_ZERO_F1:.3f}%"
)

if os.path.exists(
    few_path
):

    with open(
        few_path,
        "r"
    ) as f:

        results_qwen_few = (
            json.load(f)
        )

    QWEN_FEW_EM = float(
        results_qwen_few[
            "em"
        ]
    )

    QWEN_FEW_F1 = float(
        results_qwen_few[
            "f1"
        ]
    )

    print(
        f"Qwen 2-shot + context:    "
        f"EM={QWEN_FEW_EM:.3f}% | "
        f"F1={QWEN_FEW_F1:.3f}%"
    )

else:

    print(
        "WARNING: Qwen 2-shot "
        "result not found."
    )

======================================================================
CORRECTED QWEN REFERENCES
======================================================================
Qwen zero-shot + context: EM=0.000% | F1=18.488%
Qwen 2-shot + context:    EM=0.091% | F1=18.934%

In [14]:
# ═══════════════════════════════════════════════════════════
# CELL 12 — PHI PRE-TRAINING PREFLIGHT
# ═══════════════════════════════════════════════════════════

print(
    "=" * 74
)

print(
    "PHI-3 MINI PRE-TRAINING PREFLIGHT"
)

print(
    "=" * 74
)

required_objects = [

    "set_seed",

    "train_data",

    "val_data",

    "test_data",

    "dataset",

    "references",

    "run_evaluation",

    "stratified_analysis",

    "QWEN_ZERO_F1"
]

missing = [

    name

    for name
    in required_objects

    if name
    not in globals()
]

assert not missing, (
    f"Missing runtime objects: "
    f"{missing}"
)

assert len(
    train_data
) == 3018

assert len(
    val_data
) == 957

assert len(
    test_data
) == 1103

assert len(
    references
) == 1103

assert (
    "Syllabus context:"
    in train_data[0]["text"]
)

assert (
    "Syllabus context:"
    in test_data[0]["prompt"]
)

assert (
    "Syllabus context:\n\n"
    not in train_data[0]["text"]
)

assert (
    "Syllabus context:\n\n"
    not in test_data[0]["prompt"]
)

assert (
    is_accelerate_available()
)

free_vram = (
    torch.cuda.get_device_properties(0)
    .total_memory
    -
    torch.cuda.memory_allocated()
) / 1024**3

print(
    "GPU:",
    GPU_NAME
)

print(
    f"Free VRAM: "
    f"{free_vram:.2f} GB"
)

print(
    "✓ Required runtime objects exist."
)

print(
    "✓ Dataset sizes: "
    "3018 / 957 / 1103."
)

print(
    "✓ Corrected syllabus context confirmed."
)

print(
    f"✓ Qwen zero-shot F1: "
    f"{QWEN_ZERO_F1:.3f}%"
)

if (
    "QWEN_FEW_F1"
    in globals()
):

    print(
        f"✓ Qwen 2-shot F1: "
        f"{QWEN_FEW_F1:.3f}%"
    )

print(
    "✓ Transformers detects Accelerate."
)

print(
    "✓ Phi target modules:",
    LORA_TARGET_MODULES
)

print(
    "\n" + "=" * 74
)

print(
    "ALL PREFLIGHT CHECKS PASSED"
)

print(
    "CONTINUE TO CELL 13 — PHI LoRA"
)

print(
    "=" * 74
)

==========================================================================
PHI-3 MINI PRE-TRAINING PREFLIGHT
==========================================================================
GPU: NVIDIA A100-SXM4-40GB
Free VRAM: 39.49 GB
✓ Required runtime objects exist.
✓ Dataset sizes: 3018 / 957 / 1103.
✓ Corrected syllabus context confirmed.
✓ Qwen zero-shot F1: 18.488%
✓ Qwen 2-shot F1: 18.934%
✓ Transformers detects Accelerate.
✓ Phi target modules: ['qkv_proj', 'o_proj']

==========================================================================
ALL PREFLIGHT CHECKS PASSED
CONTINUE TO CELL 13 — PHI LoRA
==========================================================================

In [15]:
# ═══════════════════════════════════════════════════════════
# CELL 13 — R1 PHI-3 MINI LoRA SETUP
# FIXED: use native Transformers Phi-3 implementation
# Do NOT use trust_remote_code=True
# ═══════════════════════════════════════════════════════════

gc.collect()
torch.cuda.empty_cache()
set_seed(SEED)

print("=" * 70)
print("R1 — PHI-3 MINI LoRA + CORRECTED CONTEXT")
print("=" * 70)

# ------------------------------------------------------------
# 1. Tokenizer
# ------------------------------------------------------------

print("\nLoading Phi-3 tokenizer...")

tokenizer_r1 = AutoTokenizer.from_pretrained(
    MODEL_ID
)

if tokenizer_r1.pad_token is None:
    tokenizer_r1.pad_token = tokenizer_r1.eos_token

tokenizer_r1.padding_side = "right"

print("✓ Tokenizer loaded.")

# ------------------------------------------------------------
# 2. Load Phi-3 Mini using NATIVE Transformers implementation
# ------------------------------------------------------------

print("\nLoading Phi-3 Mini using native Transformers...")

model_r1 = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=TRAIN_DTYPE,
    device_map={"": 0}
)

model_r1.config.pad_token_id = tokenizer_r1.pad_token_id
model_r1.config.use_cache = False

print("✓ Phi-3 Mini loaded successfully.")
print("Model class:", type(model_r1).__name__)

# ------------------------------------------------------------
# 3. Verify expected Phi architecture modules
# ------------------------------------------------------------

available_modules = {
    name.split(".")[-1]
    for name, _ in model_r1.named_modules()
}

missing_targets = [
    module
    for module in LORA_TARGET_MODULES
    if module not in available_modules
]

assert not missing_targets, (
    f"LoRA target modules not found: {missing_targets}"
)

print(
    "✓ Phi LoRA target modules confirmed:",
    LORA_TARGET_MODULES
)

# ------------------------------------------------------------
# 4. LoRA configuration
# ------------------------------------------------------------

lora_config_r1 = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=LORA_TARGET_MODULES,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

model_r1 = get_peft_model(
    model_r1,
    lora_config_r1
)

# Same stability settings used in your working PEFT pipeline
model_r1.enable_input_require_grads()

model_r1.gradient_checkpointing_enable(
    gradient_checkpointing_kwargs={
        "use_reentrant": False
    }
)

model_r1.config.use_cache = False

model_r1.print_trainable_parameters()

trainable_r1 = sum(
    p.numel()
    for p in model_r1.parameters()
    if p.requires_grad
)

total_r1 = sum(
    p.numel()
    for p in model_r1.parameters()
)

trainable_pct_r1 = (
    100
    * trainable_r1
    / total_r1
)

print(
    f"\nTrainable parameters: "
    f"{trainable_r1:,}"
)

print(
    f"Total parameters: "
    f"{total_r1:,}"
)

print(
    f"Trainable percentage: "
    f"{trainable_pct_r1:.4f}%"
)

assert trainable_r1 > 0

# ------------------------------------------------------------
# 5. Tokenize corrected context-aware training data
# ------------------------------------------------------------

def tokenize_r1(batch):

    return tokenizer_r1(
        batch["text"],
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
        padding=False
    )

print(
    "\nTokenizing corrected training dataset..."
)

train_tokenized_r1 = train_data.map(
    tokenize_r1,
    batched=True,
    remove_columns=train_data.column_names
)

print(
    "Tokenizing corrected validation dataset..."
)

val_tokenized_r1 = val_data.map(
    tokenize_r1,
    batched=True,
    remove_columns=val_data.column_names
)

print(
    f"\nTrain tokenized: "
    f"{len(train_tokenized_r1):,}"
)

print(
    f"Validation tokenized: "
    f"{len(val_tokenized_r1):,}"
)

# ------------------------------------------------------------
# 6. Data collator
# ------------------------------------------------------------

data_collator_r1 = DataCollatorForLanguageModeling(
    tokenizer=tokenizer_r1,
    mlm=False
)

# ------------------------------------------------------------
# 7. Training schedule
# ------------------------------------------------------------

steps_per_epoch_r1 = math.ceil(
    len(train_tokenized_r1)
    / BATCH_SIZE
    / GRAD_ACCUM
)

total_steps_r1 = (
    steps_per_epoch_r1
    * NUM_EPOCHS
)

warmup_steps_r1 = math.ceil(
    total_steps_r1
    * WARMUP_RATIO
)

print("\nTraining schedule:")

print(
    "Steps per epoch:",
    steps_per_epoch_r1
)

print(
    "Total optimizer steps:",
    total_steps_r1
)

print(
    "Warmup steps:",
    warmup_steps_r1
)

# ------------------------------------------------------------
# 8. Current Transformers argument compatibility
# ------------------------------------------------------------

ta_params = inspect.signature(
    TrainingArguments.__init__
).parameters

if "eval_strategy" in ta_params:
    eval_key_r1 = "eval_strategy"

elif "evaluation_strategy" in ta_params:
    eval_key_r1 = "evaluation_strategy"

else:
    raise RuntimeError(
        "No supported evaluation strategy argument found."
    )

R1_CHECKPOINT_DIR = (
    f"{CHECKPOINT_DIR}/"
    "R1_phi3mini_lora_CONTEXT"
)

training_kwargs_r1 = {
    "output_dir":
        R1_CHECKPOINT_DIR,

    "num_train_epochs":
        NUM_EPOCHS,

    "per_device_train_batch_size":
        BATCH_SIZE,

    "per_device_eval_batch_size":
        1,

    "gradient_accumulation_steps":
        GRAD_ACCUM,

    "learning_rate":
        LEARNING_RATE,

    "lr_scheduler_type":
        "cosine",

    "warmup_steps":
        warmup_steps_r1,

    "bf16":
        BF16_OK,

    "fp16":
        not BF16_OK,

    "logging_steps":
        50,

    "save_strategy":
        "epoch",

    "save_total_limit":
        2,

    "load_best_model_at_end":
        True,

    "metric_for_best_model":
        "eval_loss",

    "greater_is_better":
        False,

    "gradient_checkpointing":
        True,

    "gradient_checkpointing_kwargs": {
        "use_reentrant": False
    },

    "optim":
        "paged_adamw_8bit",

    "seed":
        SEED,

    "data_seed":
        SEED,

    "report_to":
        "none"
}

training_kwargs_r1[
    eval_key_r1
] = "epoch"

train_args_r1 = TrainingArguments(
    **training_kwargs_r1
)

trainer_r1 = Trainer(
    model=model_r1,
    args=train_args_r1,
    train_dataset=train_tokenized_r1,
    eval_dataset=val_tokenized_r1,
    data_collator=data_collator_r1
)

print("\n✓ R1 Trainer created successfully.")
print("✓ Continue to Cell 14 only if no error appears.")

======================================================================
R1 — PHI-3 MINI LoRA + CORRECTED CONTEXT
======================================================================

Loading Phi-3 tokenizer...

config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.44k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

tokenizer.model: reconstructing file:   0%|          |  0.00B /  500kB

tokenizer.model: downloading bytes:           |  0.00B

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

✓ Tokenizer loaded.

Loading Phi-3 Mini using native Transformers...

model.safetensors.index.json:   0%|          | 0.00/16.5k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

✓ Phi-3 Mini loaded successfully.
Model class: Phi3ForCausalLM
✓ Phi LoRA target modules confirmed: ['qkv_proj', 'o_proj']
trainable params: 9,437,184 || all params: 3,830,516,736 || trainable%: 0.2464

Trainable parameters: 9,437,184
Total parameters: 3,830,516,736
Trainable percentage: 0.2464%

Tokenizing corrected training dataset...

Map:   0%|          | 0/3018 [00:00<?, ? examples/s]

Tokenizing corrected validation dataset...

Map:   0%|          | 0/957 [00:00<?, ? examples/s]

Train tokenized: 3,018
Validation tokenized: 957

Training schedule:
Steps per epoch: 189
Total optimizer steps: 567
Warmup steps: 18

✓ R1 Trainer created successfully.
✓ Continue to Cell 14 only if no error appears.

In [16]:
# ═══════════════════════════════════════════════════════════
# CELL 14 — TRAIN R1 PHI LoRA
# ═══════════════════════════════════════════════════════════

torch.cuda.empty_cache()

torch.cuda.reset_peak_memory_stats()

r1_train_start = (
    time.perf_counter()
)

print(
    "=" * 70
)

print(
    "STARTING PHI-3 MINI LoRA TRAINING"
)

print(
    "=" * 70
)

print(
    f"Training examples: "
    f"{len(train_tokenized_r1):,}"
)

print(
    f"Epochs: "
    f"{NUM_EPOCHS}"
)

print(
    f"Effective batch: "
    f"{EFFECTIVE_BATCH}"
)

print(
    f"Learning rate: "
    f"{LEARNING_RATE}"
)

train_output_r1 = (
    trainer_r1.train()
)

torch.cuda.synchronize()

r1_train_seconds = (
    time.perf_counter()
    -
    r1_train_start
)

r1_train_mins = (
    r1_train_seconds
    /
    60
)

r1_peak_train_vram = (
    torch.cuda.max_memory_allocated()
    /
    1024**3
)

print(
    "\n" + "=" * 60
)

print(
    "PHI-3 MINI LoRA TRAINING COMPLETE"
)

print(
    "=" * 60
)

print(
    f"Training time: "
    f"{r1_train_mins:.2f} min"
)

print(
    f"Peak training VRAM: "
    f"{r1_peak_train_vram:.3f} GB"
)

R1_ADAPTER_PATH = (
    f"{ADAPTER_DIR}/"
    "R1_phi3mini_lora_CONTEXT"
)

model_r1.save_pretrained(
    R1_ADAPTER_PATH
)

tokenizer_r1.save_pretrained(
    R1_ADAPTER_PATH
)

print(
    "\nLoRA adapter saved:"
)

print(
    R1_ADAPTER_PATH
)

print(
    "✓ Continue to Cell 15."
)

======================================================================
STARTING PHI-3 MINI LoRA TRAINING
======================================================================
Training examples: 3,018
Epochs: 3
Effective batch: 16
Learning rate: 0.0002

============================================================
PHI-3 MINI LoRA TRAINING COMPLETE
============================================================
Training time: 17.01 min
Peak training VRAM: 8.346 GB

LoRA adapter saved:
/content/drive/MyDrive/MR603_Thesis/adapters/R1_phi3mini_lora_CONTEXT
✓ Continue to Cell 15.

In [17]:
# ═══════════════════════════════════════════════════════════
# CELL 15 — EVALUATE R1 PHI LoRA
# ═══════════════════════════════════════════════════════════

model_r1.config.use_cache = True

model_r1.eval()

results_r1 = (
    run_evaluation(

        model=
            model_r1,

        tokenizer=
            tokenizer_r1,

        test_data=
            test_data,

        references=
            references,

        condition_name=
            "R1_Phi3Mini_LoRA_CONTEXT"
    )
)

results_r1.update({

    "model":
        "Phi-3 Mini",

    "method":
        "LoRA",

    "parameters":
        "3.8B",

    "precision":
        (
            "bfloat16"
            if BF16_OK
            else "float16"
        ),

    "context_mode":
        "BM25-retrieved syllabus context",

    "training_time_seconds":
        float(
            r1_train_seconds
        ),

    "training_time_minutes":
        float(
            r1_train_mins
        ),

    "peak_training_vram_gb":
        float(
            r1_peak_train_vram
        ),

    "trainable_parameters":
        int(
            trainable_r1
        ),

    "trainable_percentage":
        float(
            trainable_pct_r1
        )
})

print(
    "\nRunning native question-type analysis..."
)

strat_r1 = (
    stratified_analysis(

        predictions=
            results_r1[
                "predictions"
            ],

        test_raw=
            dataset[
                "test"
            ],

        condition_name=
            "R1_Phi3Mini_LoRA_CONTEXT"
    )
)

results_r1[
    "stratified"
] = strat_r1

results_r1[
    "stratified_em"
] = strat_r1

save_r1 = {

    k: v

    for k, v
    in results_r1.items()

    if k not in [
        "predictions",
        "latencies"
    ]
}

R1_RESULT_PATH = (
    f"{RESULTS_DIR}/"
    "R1_phi3mini_lora_CONTEXT.json"
)

with open(
    R1_RESULT_PATH,
    "w"
) as f:

    json.dump(
        save_r1,
        f,
        indent=2
    )

R1_PRED_JSONL = (
    f"{RESULTS_DIR}/"
    "R1_phi3mini_lora_CONTEXT_predictions.jsonl"
)

with open(
    R1_PRED_JSONL,
    "w",
    encoding="utf-8"
) as f:

    for i, prediction in enumerate(
        results_r1[
            "predictions"
        ]
    ):

        raw = (
            dataset[
                "test"
            ][i]
        )

        row = {

            "id":
                str(i),

            "syllabus_name":
                raw[
                    "syllabus_name"
                ],

            "question_type":
                raw[
                    "question_type"
                ],

            "question":
                raw[
                    "question"
                ],

            "reference_answer":
                get_answer(
                    raw
                ),

            "prediction":
                prediction,

            "latency_ms":
                results_r1[
                    "latencies"
                ][i]
        }

        f.write(
            json.dumps(
                row,
                ensure_ascii=False
            )
            +
            "\n"
        )

R1_PRED_CSV = (
    f"{RESULTS_DIR}/"
    "R1_phi3mini_lora_CONTEXT_predictions.csv"
)

pd.DataFrame({

    "Question":
        [
            ex.get(
                "question",
                ""
            )
            for ex
            in dataset[
                "test"
            ]
        ],

    "Question_Type":
        [
            ex.get(
                "question_type",
                "unknown"
            )
            for ex
            in dataset[
                "test"
            ]
        ],

    "Reference":
        [
            get_answer(
                ex
            )
            for ex
            in dataset[
                "test"
            ]
        ],

    "Prediction":
        results_r1[
            "predictions"
        ],

    "Latency_ms":
        results_r1[
            "latencies"
        ]

}).to_csv(
    R1_PRED_CSV,
    index=False
)

print(
    "\n" + "=" * 60
)

print(
    "PHI-3 MINI LoRA CORRECTED RESULTS"
)

print(
    "=" * 60
)

print(
    f"Exact Match: "
    f"{results_r1['em']:.3f}%"
)

print(
    f"F1 Score: "
    f"{results_r1['f1']:.3f}%"
)

print(
    f"Avg Latency: "
    f"{results_r1['avg_latency_ms']:.3f} ms/sample"
)

print(
    f"Median Latency: "
    f"{results_r1['median_latency_ms']:.3f} ms/sample"
)

print(
    f"Peak Eval VRAM: "
    f"{results_r1['peak_vram_gb']:.3f} GB"
)

print(
    f"Training Time: "
    f"{r1_train_mins:.2f} min"
)

print(
    f"Peak Training VRAM: "
    f"{r1_peak_train_vram:.3f} GB"
)

print(
    "\nRQ1 CHECK — Phi LoRA vs corrected Qwen"
)

print(
    f"Qwen zero-shot + context F1: "
    f"{QWEN_ZERO_F1:.3f}%"
)

if (
    "QWEN_FEW_F1"
    in globals()
):

    print(
        f"Qwen 2-shot + context F1: "
        f"{QWEN_FEW_F1:.3f}%"
    )

print(
    f"Phi LoRA + context F1: "
    f"{results_r1['f1']:.3f}%"
)

print(
    f"Gap to Qwen zero-shot: "
    f"{results_r1['f1'] - QWEN_ZERO_F1:+.3f} pp"
)

if (
    "QWEN_FEW_F1"
    in globals()
):

    print(
        f"Gap to Qwen 2-shot: "
        f"{results_r1['f1'] - QWEN_FEW_F1:+.3f} pp"
    )

print(
    "\nResults saved:",
    R1_RESULT_PATH
)

print(
    "Predictions JSONL:",
    R1_PRED_JSONL
)

print(
    "Predictions CSV:",
    R1_PRED_CSV
)

=======================================================
EVALUATING: R1_Phi3Mini_LoRA_CONTEXT
=======================================================
Test examples: 1,103
Progress logged every 100 examples
   0/1103 | 0.0 min | 0 ms/sample
 100/1103 | 5.9 min | 3523 ms/sample
 200/1103 | 11.8 min | 3534 ms/sample
 300/1103 | 17.6 min | 3527 ms/sample
 400/1103 | 23.6 min | 3533 ms/sample
 500/1103 | 29.5 min | 3540 ms/sample
 600/1103 | 35.5 min | 3546 ms/sample
 700/1103 | 41.4 min | 3549 ms/sample
 800/1103 | 47.4 min | 3552 ms/sample
 900/1103 | 53.3 min | 3553 ms/sample
1000/1103 | 59.2 min | 3555 ms/sample
1100/1103 | 65.2 min | 3556 ms/sample

─────────────────────────────────────────────
RESULTS: R1_Phi3Mini_LoRA_CONTEXT
─────────────────────────────────────────────
Exact Match:    0.091%
F1 Score:       20.030%
Avg Latency:    3555.800 ms/sample
Median Latency: 3553.205 ms/sample
Peak GPU VRAM:  7.421 GB

Running native question-type analysis...

Running stratified analysis: R1_Phi3Mini_LoRA_CONTEXT

Question Type             EM %     F1 %     n
──────────────────────────────────────────────────
multi factual                0.000   32.365   158
multi reasoning              0.000   27.673   158
no answer                    0.645    4.881   155
single factual               0.000   19.170   158
single reasoning             0.000   24.631   158
summarization                0.000   28.530   158
yes/no                       0.000    2.676   158

============================================================
PHI-3 MINI LoRA CORRECTED RESULTS
============================================================
Exact Match: 0.091%
F1 Score: 20.030%
Avg Latency: 3555.800 ms/sample
Median Latency: 3553.205 ms/sample
Peak Eval VRAM: 7.421 GB
Training Time: 17.01 min
Peak Training VRAM: 8.346 GB

RQ1 CHECK — Phi LoRA vs corrected Qwen
Qwen zero-shot + context F1: 18.488%
Qwen 2-shot + context F1: 18.934%
Phi LoRA + context F1: 20.030%
Gap to Qwen zero-shot: +1.542 pp
Gap to Qwen 2-shot: +1.097 pp

Results saved: /content/drive/MyDrive/MR603_Thesis/results/R1_phi3mini_lora_CONTEXT.json
Predictions JSONL: /content/drive/MyDrive/MR603_Thesis/results/R1_phi3mini_lora_CONTEXT_predictions.jsonl
Predictions CSV: /content/drive/MyDrive/MR603_Thesis/results/R1_phi3mini_lora_CONTEXT_predictions.csv

In [18]:
# ═══════════════════════════════════════════════════════════
# CELL 16 — CLEAR LoRA MODEL FROM GPU
# ═══════════════════════════════════════════════════════════

for name in [

    "trainer_r1",

    "model_r1",

    "train_tokenized_r1",

    "val_tokenized_r1"

]:

    if name in globals():

        del globals()[
            name
        ]

gc.collect()

torch.cuda.empty_cache()

free_vram = (
    torch.cuda
    .get_device_properties(0)
    .total_memory
    -
    torch.cuda
    .memory_allocated()
) / 1024**3

print(
    "✓ R1 LoRA cleared from GPU."
)

print(
    f"Free VRAM: "
    f"{free_vram:.2f} GB"
)

print(
    "✓ Continue to Cell 17."
)

✓ R1 LoRA cleared from GPU.
Free VRAM: 39.29 GB
✓ Continue to Cell 17.

In [20]:
# ═══════════════════════════════════════════════════════════
# CELL 17 — R2 PHI-3 MINI QLoRA SETUP
# FIXED: force native Phi3ForCausalLM
# NO remote modeling_phi3.py
# Fresh clean 4-bit NF4 QLoRA run
# ═══════════════════════════════════════════════════════════

import gc
import math
import inspect
import torch

from transformers import (
    AutoTokenizer,
    Phi3ForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
    TaskType
)

gc.collect()
torch.cuda.empty_cache()
set_seed(SEED)

print("=" * 70)
print("R2 — PHI-3 MINI QLoRA + CORRECTED CONTEXT")
print("Native Transformers Phi3ForCausalLM")
print("=" * 70)

# ------------------------------------------------------------
# 1. Tokenizer
# ------------------------------------------------------------

print("\nLoading Phi-3 tokenizer...")

tokenizer_r2 = AutoTokenizer.from_pretrained(
    MODEL_ID
)

if tokenizer_r2.pad_token is None:
    tokenizer_r2.pad_token = tokenizer_r2.eos_token

tokenizer_r2.padding_side = "right"

print("✓ Tokenizer loaded.")

# ------------------------------------------------------------
# 2. 4-bit QLoRA configuration
# ------------------------------------------------------------

print("\nConfiguring 4-bit NF4 quantisation...")

bnb_config_r2 = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16
)

# ------------------------------------------------------------
# 3. IMPORTANT FIX:
# Force native Phi3ForCausalLM instead of AutoModel remote code
# ------------------------------------------------------------

print(
    "Loading Phi-3 Mini using native "
    "Phi3ForCausalLM in 4-bit..."
)

model_r2 = Phi3ForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config_r2,
    device_map={"": 0},
    attn_implementation="sdpa"
)

model_r2.config.pad_token_id = (
    tokenizer_r2.pad_token_id
)

model_r2.config.use_cache = False

print("✓ Phi-3 Mini QLoRA base model loaded.")
print("Model class:", type(model_r2).__name__)

print(
    f"GPU memory after model load: "
    f"{torch.cuda.memory_allocated()/1024**3:.3f} GB"
)

# ------------------------------------------------------------
# 4. Prepare for k-bit training
# ------------------------------------------------------------

print("\nPreparing model for k-bit training...")

model_r2 = prepare_model_for_kbit_training(
    model_r2,
    use_gradient_checkpointing=True
)

model_r2.config.use_cache = False

# ------------------------------------------------------------
# 5. Verify Phi target modules
# ------------------------------------------------------------

available_modules = {
    name.split(".")[-1]
    for name, _ in model_r2.named_modules()
}

missing_targets = [
    module
    for module in LORA_TARGET_MODULES
    if module not in available_modules
]

assert not missing_targets, (
    f"Missing Phi LoRA targets: {missing_targets}"
)

print(
    "✓ Phi target modules found:",
    LORA_TARGET_MODULES
)

# ------------------------------------------------------------
# 6. LoRA adapters on quantised base
# ------------------------------------------------------------

lora_config_r2 = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=LORA_TARGET_MODULES,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

model_r2 = get_peft_model(
    model_r2,
    lora_config_r2
)

model_r2.print_trainable_parameters()

trainable_r2 = sum(
    p.numel()
    for p in model_r2.parameters()
    if p.requires_grad
)

total_r2 = sum(
    p.numel()
    for p in model_r2.parameters()
)

trainable_pct_r2 = (
    100
    * trainable_r2
    / total_r2
)

print(
    f"\nTrainable parameters: "
    f"{trainable_r2:,}"
)

print(
    f"Total parameters: "
    f"{total_r2:,}"
)

print(
    f"Trainable percentage: "
    f"{trainable_pct_r2:.4f}%"
)

assert trainable_r2 > 0

# ------------------------------------------------------------
# 7. Tokenize corrected context-aware data
# ------------------------------------------------------------

def tokenize_r2(batch):
    return tokenizer_r2(
        batch["text"],
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
        padding=False
    )

print("\nTokenizing corrected training dataset...")

train_tokenized_r2 = train_data.map(
    tokenize_r2,
    batched=True,
    remove_columns=train_data.column_names
)

print("Tokenizing corrected validation dataset...")

val_tokenized_r2 = val_data.map(
    tokenize_r2,
    batched=True,
    remove_columns=val_data.column_names
)

print(
    f"\nTrain tokenized: "
    f"{len(train_tokenized_r2):,}"
)

print(
    f"Validation tokenized: "
    f"{len(val_tokenized_r2):,}"
)

# ------------------------------------------------------------
# 8. Data collator
# ------------------------------------------------------------

data_collator_r2 = DataCollatorForLanguageModeling(
    tokenizer=tokenizer_r2,
    mlm=False
)

# ------------------------------------------------------------
# 9. Training schedule
# ------------------------------------------------------------

steps_per_epoch_r2 = math.ceil(
    len(train_tokenized_r2)
    / BATCH_SIZE
    / GRAD_ACCUM
)

total_steps_r2 = (
    steps_per_epoch_r2
    * NUM_EPOCHS
)

warmup_steps_r2 = math.ceil(
    total_steps_r2
    * WARMUP_RATIO
)

print("\nTraining schedule:")
print("Steps per epoch:", steps_per_epoch_r2)
print("Total optimizer steps:", total_steps_r2)
print("Warmup steps:", warmup_steps_r2)

# ------------------------------------------------------------
# 10. TrainingArguments compatibility
# ------------------------------------------------------------

ta_params = inspect.signature(
    TrainingArguments.__init__
).parameters

if "eval_strategy" in ta_params:
    eval_key_r2 = "eval_strategy"

elif "evaluation_strategy" in ta_params:
    eval_key_r2 = "evaluation_strategy"

else:
    raise RuntimeError(
        "No supported evaluation strategy argument found."
    )

R2_CHECKPOINT_DIR = (
    f"{CHECKPOINT_DIR}/"
    "R2_phi3mini_qlora_CONTEXT"
)

training_kwargs_r2 = {
    "output_dir":
        R2_CHECKPOINT_DIR,

    "num_train_epochs":
        NUM_EPOCHS,

    "per_device_train_batch_size":
        BATCH_SIZE,

    "per_device_eval_batch_size":
        1,

    "gradient_accumulation_steps":
        GRAD_ACCUM,

    "learning_rate":
        LEARNING_RATE,

    "lr_scheduler_type":
        "cosine",

    "warmup_steps":
        warmup_steps_r2,

    "bf16":
        BF16_OK,

    "fp16":
        not BF16_OK,

    "logging_steps":
        50,

    "save_strategy":
        "epoch",

    "save_total_limit":
        2,

    "load_best_model_at_end":
        True,

    "metric_for_best_model":
        "eval_loss",

    "greater_is_better":
        False,

    "gradient_checkpointing":
        True,

    "gradient_checkpointing_kwargs": {
        "use_reentrant": False
    },

    "optim":
        "paged_adamw_8bit",

    "seed":
        SEED,

    "data_seed":
        SEED,

    "report_to":
        "none"
}

training_kwargs_r2[
    eval_key_r2
] = "epoch"

train_args_r2 = TrainingArguments(
    **training_kwargs_r2
)

trainer_r2 = Trainer(
    model=model_r2,
    args=train_args_r2,
    train_dataset=train_tokenized_r2,
    eval_dataset=val_tokenized_r2,
    data_collator=data_collator_r2
)

print("\n✓ R2 QLoRA Trainer created successfully.")
print("✓ Native Phi implementation confirmed.")
print("✓ Fresh run — no checkpoint resume.")
print("✓ Continue to Cell 18.")

======================================================================
R2 — PHI-3 MINI QLoRA + CORRECTED CONTEXT
Native Transformers Phi3ForCausalLM
======================================================================

Loading Phi-3 tokenizer...
✓ Tokenizer loaded.

Configuring 4-bit NF4 quantisation...
Loading Phi-3 Mini using native Phi3ForCausalLM in 4-bit...

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

✓ Phi-3 Mini QLoRA base model loaded.
Model class: Phi3ForCausalLM
GPU memory after model load: 2.309 GB

Preparing model for k-bit training...
✓ Phi target modules found: ['qkv_proj', 'o_proj']
trainable params: 9,437,184 || all params: 3,830,516,736 || trainable%: 0.2464

Trainable parameters: 9,437,184
Total parameters: 2,018,577,408
Trainable percentage: 0.4675%

Tokenizing corrected training dataset...

Map:   0%|          | 0/3018 [00:00<?, ? examples/s]

Tokenizing corrected validation dataset...

Map:   0%|          | 0/957 [00:00<?, ? examples/s]

Train tokenized: 3,018
Validation tokenized: 957

Training schedule:
Steps per epoch: 189
Total optimizer steps: 567
Warmup steps: 18

✓ R2 QLoRA Trainer created successfully.
✓ Native Phi implementation confirmed.
✓ Fresh run — no checkpoint resume.
✓ Continue to Cell 18.

In [21]:
# ═══════════════════════════════════════════════════════════
# CELL 18 — TRAIN R2 PHI QLoRA
# ═══════════════════════════════════════════════════════════

torch.cuda.empty_cache()

torch.cuda.reset_peak_memory_stats()

r2_train_start = (
    time.perf_counter()
)

print(
    "=" * 70
)

print(
    "STARTING PHI-3 MINI QLoRA TRAINING"
)

print(
    "=" * 70
)

print(
    f"Training examples: "
    f"{len(train_tokenized_r2):,}"
)

print(
    f"Epochs: "
    f"{NUM_EPOCHS}"
)

print(
    f"Effective batch: "
    f"{EFFECTIVE_BATCH}"
)

print(
    f"Learning rate: "
    f"{LEARNING_RATE}"
)

train_output_r2 = (
    trainer_r2.train()
)

torch.cuda.synchronize()

r2_train_seconds = (
    time.perf_counter()
    -
    r2_train_start
)

r2_train_mins = (
    r2_train_seconds
    /
    60
)

r2_peak_train_vram = (
    torch.cuda.max_memory_allocated()
    /
    1024**3
)

print(
    "\n" + "=" * 60
)

print(
    "PHI-3 MINI QLoRA TRAINING COMPLETE"
)

print(
    "=" * 60
)

print(
    f"Training time: "
    f"{r2_train_mins:.2f} min"
)

print(
    f"Peak training VRAM: "
    f"{r2_peak_train_vram:.3f} GB"
)

R2_ADAPTER_PATH = (
    f"{ADAPTER_DIR}/"
    "R2_phi3mini_qlora_CONTEXT"
)

model_r2.save_pretrained(
    R2_ADAPTER_PATH
)

tokenizer_r2.save_pretrained(
    R2_ADAPTER_PATH
)

print(
    "\nQLoRA adapter saved:"
)

print(
    R2_ADAPTER_PATH
)

print(
    "✓ Continue to Cell 19."
)

======================================================================
STARTING PHI-3 MINI QLoRA TRAINING
======================================================================
Training examples: 3,018
Epochs: 3
Effective batch: 16
Learning rate: 0.0002

============================================================
PHI-3 MINI QLoRA TRAINING COMPLETE
============================================================
Training time: 21.85 min
Peak training VRAM: 4.448 GB

QLoRA adapter saved:
/content/drive/MyDrive/MR603_Thesis/adapters/R2_phi3mini_qlora_CONTEXT
✓ Continue to Cell 19.

In [22]:
# ═══════════════════════════════════════════════════════════
# CELL 19 — EVALUATE R2 PHI QLoRA
# ═══════════════════════════════════════════════════════════

model_r2.config.use_cache = True

model_r2.eval()

results_r2 = (
    run_evaluation(

        model=
            model_r2,

        tokenizer=
            tokenizer_r2,

        test_data=
            test_data,

        references=
            references,

        condition_name=
            "R2_Phi3Mini_QLoRA_CONTEXT"
    )
)

results_r2.update({

    "model":
        "Phi-3 Mini",

    "method":
        "QLoRA",

    "parameters":
        "3.8B",

    "precision":
        "4-bit NF4 + double quantisation",

    "context_mode":
        "BM25-retrieved syllabus context",

    "training_time_seconds":
        float(
            r2_train_seconds
        ),

    "training_time_minutes":
        float(
            r2_train_mins
        ),

    "peak_training_vram_gb":
        float(
            r2_peak_train_vram
        ),

    "trainable_parameters":
        int(
            trainable_r2
        ),

    "trainable_percentage":
        float(
            trainable_pct_r2
        )
})

print(
    "\nRunning native question-type analysis..."
)

strat_r2 = (
    stratified_analysis(

        predictions=
            results_r2[
                "predictions"
            ],

        test_raw=
            dataset[
                "test"
            ],

        condition_name=
            "R2_Phi3Mini_QLoRA_CONTEXT"
    )
)

results_r2[
    "stratified"
] = strat_r2

results_r2[
    "stratified_em"
] = strat_r2

save_r2 = {

    k: v

    for k, v
    in results_r2.items()

    if k not in [
        "predictions",
        "latencies"
    ]
}

R2_RESULT_PATH = (
    f"{RESULTS_DIR}/"
    "R2_phi3mini_qlora_CONTEXT.json"
)

with open(
    R2_RESULT_PATH,
    "w"
) as f:

    json.dump(
        save_r2,
        f,
        indent=2
    )

R2_PRED_JSONL = (
    f"{RESULTS_DIR}/"
    "R2_phi3mini_qlora_CONTEXT_predictions.jsonl"
)

with open(
    R2_PRED_JSONL,
    "w",
    encoding="utf-8"
) as f:

    for i, prediction in enumerate(
        results_r2[
            "predictions"
        ]
    ):

        raw = (
            dataset[
                "test"
            ][i]
        )

        row = {

            "id":
                str(i),

            "syllabus_name":
                raw[
                    "syllabus_name"
                ],

            "question_type":
                raw[
                    "question_type"
                ],

            "question":
                raw[
                    "question"
                ],

            "reference_answer":
                get_answer(
                    raw
                ),

            "prediction":
                prediction,

            "latency_ms":
                results_r2[
                    "latencies"
                ][i]
        }

        f.write(
            json.dumps(
                row,
                ensure_ascii=False
            )
            +
            "\n"
        )

R2_PRED_CSV = (
    f"{RESULTS_DIR}/"
    "R2_phi3mini_qlora_CONTEXT_predictions.csv"
)

pd.DataFrame({

    "Question":
        [
            ex.get(
                "question",
                ""
            )
            for ex
            in dataset[
                "test"
            ]
        ],

    "Question_Type":
        [
            ex.get(
                "question_type",
                "unknown"
            )
            for ex
            in dataset[
                "test"
            ]
        ],

    "Reference":
        [
            get_answer(
                ex
            )
            for ex
            in dataset[
                "test"
            ]
        ],

    "Prediction":
        results_r2[
            "predictions"
        ],

    "Latency_ms":
        results_r2[
            "latencies"
        ]

}).to_csv(
    R2_PRED_CSV,
    index=False
)

print(
    "\n" + "=" * 60
)

print(
    "PHI-3 MINI QLoRA CORRECTED RESULTS"
)

print(
    "=" * 60
)

print(
    f"Exact Match: "
    f"{results_r2['em']:.3f}%"
)

print(
    f"F1 Score: "
    f"{results_r2['f1']:.3f}%"
)

print(
    f"Avg Latency: "
    f"{results_r2['avg_latency_ms']:.3f} ms/sample"
)

print(
    f"Median Latency: "
    f"{results_r2['median_latency_ms']:.3f} ms/sample"
)

print(
    f"Peak Eval VRAM: "
    f"{results_r2['peak_vram_gb']:.3f} GB"
)

print(
    f"Training Time: "
    f"{r2_train_mins:.2f} min"
)

print(
    f"Peak Training VRAM: "
    f"{r2_peak_train_vram:.3f} GB"
)

print(
    "\nRQ1 CHECK — Phi QLoRA vs corrected Qwen"
)

print(
    f"Qwen zero-shot + context F1: "
    f"{QWEN_ZERO_F1:.3f}%"
)

if (
    "QWEN_FEW_F1"
    in globals()
):

    print(
        f"Qwen 2-shot + context F1: "
        f"{QWEN_FEW_F1:.3f}%"
    )

print(
    f"Phi QLoRA + context F1: "
    f"{results_r2['f1']:.3f}%"
)

print(
    f"Gap to Qwen zero-shot: "
    f"{results_r2['f1'] - QWEN_ZERO_F1:+.3f} pp"
)

if (
    "QWEN_FEW_F1"
    in globals()
):

    print(
        f"Gap to Qwen 2-shot: "
        f"{results_r2['f1'] - QWEN_FEW_F1:+.3f} pp"
    )

print(
    "\nResults saved:",
    R2_RESULT_PATH
)

print(
    "Predictions JSONL:",
    R2_PRED_JSONL
)

print(
    "Predictions CSV:",
    R2_PRED_CSV
)

=======================================================
EVALUATING: R2_Phi3Mini_QLoRA_CONTEXT
=======================================================
Test examples: 1,103
Progress logged every 100 examples
   0/1103 | 0.0 min | 0 ms/sample
 100/1103 | 7.3 min | 4370 ms/sample
 200/1103 | 14.5 min | 4350 ms/sample
 300/1103 | 21.7 min | 4346 ms/sample
 400/1103 | 29.0 min | 4345 ms/sample
 500/1103 | 36.1 min | 4335 ms/sample
 600/1103 | 43.3 min | 4333 ms/sample
 700/1103 | 50.6 min | 4335 ms/sample
 800/1103 | 57.8 min | 4338 ms/sample
 900/1103 | 65.1 min | 4340 ms/sample
1000/1103 | 72.4 min | 4343 ms/sample
1100/1103 | 79.6 min | 4344 ms/sample

─────────────────────────────────────────────
RESULTS: R2_Phi3Mini_QLoRA_CONTEXT
─────────────────────────────────────────────
Exact Match:    0.000%
F1 Score:       20.084%
Avg Latency:    4344.341 ms/sample
Median Latency: 4343.310 ms/sample
Peak GPU VRAM:  3.237 GB

Running native question-type analysis...

Running stratified analysis: R2_Phi3Mini_QLoRA_CONTEXT

Question Type             EM %     F1 %     n
──────────────────────────────────────────────────
multi factual                0.000   31.142   158
multi reasoning              0.000   29.035   158
no answer                    0.000    3.292   155
single factual               0.000   18.752   158
single reasoning             0.000   26.249   158
summarization                0.000   28.425   158
yes/no                       0.000    3.374   158

============================================================
PHI-3 MINI QLoRA CORRECTED RESULTS
============================================================
Exact Match: 0.000%
F1 Score: 20.084%
Avg Latency: 4344.341 ms/sample
Median Latency: 4343.310 ms/sample
Peak Eval VRAM: 3.237 GB
Training Time: 21.85 min
Peak Training VRAM: 4.448 GB

RQ1 CHECK — Phi QLoRA vs corrected Qwen
Qwen zero-shot + context F1: 18.488%
Qwen 2-shot + context F1: 18.934%
Phi QLoRA + context F1: 20.084%
Gap to Qwen zero-shot: +1.596 pp
Gap to Qwen 2-shot: +1.150 pp

Results saved: /content/drive/MyDrive/MR603_Thesis/results/R2_phi3mini_qlora_CONTEXT.json
Predictions JSONL: /content/drive/MyDrive/MR603_Thesis/results/R2_phi3mini_qlora_CONTEXT_predictions.jsonl
Predictions CSV: /content/drive/MyDrive/MR603_Thesis/results/R2_phi3mini_qlora_CONTEXT_predictions.csv

In [23]:
# ═══════════════════════════════════════════════════════════
# CELL 20 — PHI LoRA VS QLoRA + QWEN COMPARISON
# ═══════════════════════════════════════════════════════════

print(
    "=" * 74
)

print(
    "PHI-3 MINI — CORRECTED CONTEXT COMPARISON"
)

print(
    "=" * 74
)

print(
    "\nPERFORMANCE"
)

print(
    f"LoRA EM: "
    f"{results_r1['em']:.3f}%"
)

print(
    f"QLoRA EM: "
    f"{results_r2['em']:.3f}%"
)

print(
    f"LoRA F1: "
    f"{results_r1['f1']:.3f}%"
)

print(
    f"QLoRA F1: "
    f"{results_r2['f1']:.3f}%"
)

print(
    f"LoRA - QLoRA F1: "
    f"{results_r1['f1'] - results_r2['f1']:+.3f} pp"
)

print(
    f"Qwen zero-shot + context: "
    f"{QWEN_ZERO_F1:.3f}%"
)

if (
    "QWEN_FEW_F1"
    in globals()
):

    print(
        f"Qwen 2-shot + context: "
        f"{QWEN_FEW_F1:.3f}%"
    )


print(
    "\nGAPS TO QWEN ZERO-SHOT"
)

print(
    f"LoRA: "
    f"{results_r1['f1'] - QWEN_ZERO_F1:+.3f} pp"
)

print(
    f"QLoRA: "
    f"{results_r2['f1'] - QWEN_ZERO_F1:+.3f} pp"
)


if (
    "QWEN_FEW_F1"
    in globals()
):

    print(
        "\nGAPS TO QWEN 2-SHOT"
    )

    print(
        f"LoRA: "
        f"{results_r1['f1'] - QWEN_FEW_F1:+.3f} pp"
    )

    print(
        f"QLoRA: "
        f"{results_r2['f1'] - QWEN_FEW_F1:+.3f} pp"
    )


print(
    "\nEFFICIENCY"
)

print(
    f"LoRA latency: "
    f"{results_r1['avg_latency_ms']:.3f} ms"
)

print(
    f"QLoRA latency: "
    f"{results_r2['avg_latency_ms']:.3f} ms"
)

print(
    f"LoRA eval VRAM: "
    f"{results_r1['peak_vram_gb']:.3f} GB"
)

print(
    f"QLoRA eval VRAM: "
    f"{results_r2['peak_vram_gb']:.3f} GB"
)

print(
    f"LoRA train time: "
    f"{results_r1['training_time_minutes']:.2f} min"
)

print(
    f"QLoRA train time: "
    f"{results_r2['training_time_minutes']:.2f} min"
)

print(
    f"LoRA train VRAM: "
    f"{results_r1['peak_training_vram_gb']:.3f} GB"
)

print(
    f"QLoRA train VRAM: "
    f"{results_r2['peak_training_vram_gb']:.3f} GB"
)

print(
    "\nNote:"
)

print(
    "Qwen2.5-14B is a larger prompting reference, "
    "not an adaptation-matched baseline."
)

==========================================================================
PHI-3 MINI — CORRECTED CONTEXT COMPARISON
==========================================================================

PERFORMANCE
LoRA EM: 0.091%
QLoRA EM: 0.000%
LoRA F1: 20.030%
QLoRA F1: 20.084%
LoRA - QLoRA F1: -0.053 pp
Qwen zero-shot + context: 18.488%
Qwen 2-shot + context: 18.934%

GAPS TO QWEN ZERO-SHOT
LoRA: +1.542 pp
QLoRA: +1.596 pp

GAPS TO QWEN 2-SHOT
LoRA: +1.097 pp
QLoRA: +1.150 pp

EFFICIENCY
LoRA latency: 3555.800 ms
QLoRA latency: 4344.341 ms
LoRA eval VRAM: 7.421 GB
QLoRA eval VRAM: 3.237 GB
LoRA train time: 17.01 min
QLoRA train time: 21.85 min
LoRA train VRAM: 8.346 GB
QLoRA train VRAM: 4.448 GB

Note:
Qwen2.5-14B is a larger prompting reference, not an adaptation-matched baseline.

In [24]:
# ═══════════════════════════════════════════════════════════
# CELL 21 — RQ2 QUESTION-TYPE COMPARISON
# ═══════════════════════════════════════════════════════════

print(
    "=" * 76
)

print(
    "RQ2 — PHI-3 MINI LoRA VS QLoRA BY QUESTION TYPE"
)

print(
    "=" * 76
)

strat_l = (
    results_r1.get(
        "stratified",
        results_r1.get(
            "stratified_em",
            {}
        )
    )
)

strat_q = (
    results_r2.get(
        "stratified",
        results_r2.get(
            "stratified_em",
            {}
        )
    )
)

rq2_rows = []

for q_type in sorted(
    strat_l.keys()
):

    if (
        q_type
        not in strat_q
    ):

        continue

    lora_values = (
        strat_l[
            q_type
        ]
    )

    qlora_values = (
        strat_q[
            q_type
        ]
    )

    rq2_rows.append({

        "Question_Type":
            q_type,

        "N":
            lora_values[
                "count"
            ],

        "LoRA_EM_percent":
            lora_values[
                "exact_match"
            ],

        "QLoRA_EM_percent":
            qlora_values[
                "exact_match"
            ],

        "Delta_EM_LoRA_minus_QLoRA":
            (
                lora_values[
                    "exact_match"
                ]
                -
                qlora_values[
                    "exact_match"
                ]
            ),

        "LoRA_F1_percent":
            lora_values[
                "f1"
            ],

        "QLoRA_F1_percent":
            qlora_values[
                "f1"
            ],

        "Delta_F1_LoRA_minus_QLoRA":
            (
                lora_values[
                    "f1"
                ]
                -
                qlora_values[
                    "f1"
                ]
            )
    })


phi_rq2 = (
    pd.DataFrame(
        rq2_rows
    )
)

display(
    phi_rq2.round(
        3
    )
)

PHI_RQ2_PATH = (
    f"{RESULTS_DIR}/"
    "Phi3Mini_CONTEXT_RQ2_QuestionType_Results.csv"
)

phi_rq2.to_csv(
    PHI_RQ2_PATH,
    index=False
)

print(
    "\nSaved:"
)

print(
    PHI_RQ2_PATH
)

============================================================================
RQ2 — PHI-3 MINI LoRA VS QLoRA BY QUESTION TYPE
============================================================================

,Question_Type,N,LoRA_EM_percent,QLoRA_EM_percent,Delta_EM_LoRA_minus_QLoRA,LoRA_F1_percent,QLoRA_F1_percent,Delta_F1_LoRA_minus_QLoRA
0,multi factual,158,0.000,0.0,0.000,32.365,31.142,1.222
1,multi reasoning,158,0.000,0.0,0.000,27.673,29.035,-1.362
2,no answer,155,0.645,0.0,0.645,4.881,3.292,1.589
3,single factual,158,0.000,0.0,0.000,19.170,18.752,0.418
4,single reasoning,158,0.000,0.0,0.000,24.631,26.249,-1.617
5,summarization,158,0.000,0.0,0.000,28.530,28.425,0.105
6,yes/no,158,0.000,0.0,0.000,2.676,3.374,-0.699

Saved:
/content/drive/MyDrive/MR603_Thesis/results/Phi3Mini_CONTEXT_RQ2_QuestionType_Results.csv

In [25]:
# ═══════════════════════════════════════════════════════════
# CELL 22 — FINAL CORRECTED PHI RESULTS
# ═══════════════════════════════════════════════════════════

phi_rows = []


r1_row = {

    "Notebook":
        2,

    "Condition":
        "R1_Phi3Mini_LoRA_CONTEXT",

    "Model":
        "Phi-3 Mini",

    "Method":
        "LoRA",

    "Parameters_B":
        3.8,

    "Base_Precision":
        results_r1[
            "precision"
        ],

    "Context_Mode":
        "BM25-retrieved syllabus context",

    "EM_percent":
        results_r1[
            "em"
        ],

    "F1_percent":
        results_r1[
            "f1"
        ],

    "Training_Time_min":
        results_r1[
            "training_time_minutes"
        ],

    "Avg_Latency_ms":
        results_r1[
            "avg_latency_ms"
        ],

    "Median_Latency_ms":
        results_r1[
            "median_latency_ms"
        ],

    "Peak_Train_VRAM_GB":
        results_r1[
            "peak_training_vram_gb"
        ],

    "Peak_Eval_VRAM_GB":
        results_r1[
            "peak_vram_gb"
        ],

    "Trainable_Params":
        results_r1[
            "trainable_parameters"
        ],

    "Trainable_Pct":
        results_r1[
            "trainable_percentage"
        ],

    "Gap_Qwen_ZeroShot_F1_pp":
        (
            results_r1[
                "f1"
            ]
            -
            QWEN_ZERO_F1
        )
}


if (
    "QWEN_FEW_F1"
    in globals()
):

    r1_row[
        "Gap_Qwen_2Shot_F1_pp"
    ] = (
        results_r1[
            "f1"
        ]
        -
        QWEN_FEW_F1
    )


phi_rows.append(
    r1_row
)


r2_row = {

    "Notebook":
        2,

    "Condition":
        "R2_Phi3Mini_QLoRA_CONTEXT",

    "Model":
        "Phi-3 Mini",

    "Method":
        "QLoRA",

    "Parameters_B":
        3.8,

    "Base_Precision":
        "4-bit NF4 + double quantisation",

    "Context_Mode":
        "BM25-retrieved syllabus context",

    "EM_percent":
        results_r2[
            "em"
        ],

    "F1_percent":
        results_r2[
            "f1"
        ],

    "Training_Time_min":
        results_r2[
            "training_time_minutes"
        ],

    "Avg_Latency_ms":
        results_r2[
            "avg_latency_ms"
        ],

    "Median_Latency_ms":
        results_r2[
            "median_latency_ms"
        ],

    "Peak_Train_VRAM_GB":
        results_r2[
            "peak_training_vram_gb"
        ],

    "Peak_Eval_VRAM_GB":
        results_r2[
            "peak_vram_gb"
        ],

    "Trainable_Params":
        results_r2[
            "trainable_parameters"
        ],

    "Trainable_Pct":
        results_r2[
            "trainable_percentage"
        ],

    "Gap_Qwen_ZeroShot_F1_pp":
        (
            results_r2[
                "f1"
            ]
            -
            QWEN_ZERO_F1
        )
}


if (
    "QWEN_FEW_F1"
    in globals()
):

    r2_row[
        "Gap_Qwen_2Shot_F1_pp"
    ] = (
        results_r2[
            "f1"
        ]
        -
        QWEN_FEW_F1
    )


phi_rows.append(
    r2_row
)


phi_final = (
    pd.DataFrame(
        phi_rows
    )
)


PHI_FINAL_PATH = (
    f"{RESULTS_DIR}/"
    "Phi3Mini_CONTEXT_Final_Results.csv"
)


phi_final.to_csv(
    PHI_FINAL_PATH,
    index=False
)


display(
    phi_final.round(
        3
    )
)


print(
    "\nSaved final Phi results:"
)

print(
    PHI_FINAL_PATH
)

,Notebook,Condition,Model,Method,Parameters_B,Base_Precision,Context_Mode,EM_percent,F1_percent,Training_Time_min,Avg_Latency_ms,Median_Latency_ms,Peak_Train_VRAM_GB,Peak_Eval_VRAM_GB,Trainable_Params,Trainable_Pct,Gap_Qwen_ZeroShot_F1_pp,Gap_Qwen_2Shot_F1_pp
0,2,R1_Phi3Mini_LoRA_CONTEXT,Phi-3 Mini,LoRA,3.8,bfloat16,BM25-retrieved syllabus context,0.091,20.030,17.008,3555.800,3553.205,8.346,7.421,9437184,0.246,1.542,1.097
1,2,R2_Phi3Mini_QLoRA_CONTEXT,Phi-3 Mini,QLoRA,3.8,4-bit NF4 + double quantisation,BM25-retrieved syllabus context,0.000,20.084,21.845,4344.341,4343.310,4.448,3.237,9437184,0.468,1.596,1.150

Saved final Phi results:
/content/drive/MyDrive/MR603_Thesis/results/Phi3Mini_CONTEXT_Final_Results.csv

In [26]:
# ═══════════════════════════════════════════════════════════
# CELL 23 — SAVE PHI EXPERIMENT CONFIGURATION
# ═══════════════════════════════════════════════════════════

phi_config = {

    "notebook":
        "2_Phi3Mini_CONTEXT",

    "model":
        MODEL_ID,

    "dataset":
        "SyllabusQA",

    "dataset_split": {

        "train":
            3018,

        "validation":
            957,

        "test":
            1103
    },

    "context_pipeline": {

        "method":
            "BM25 syllabus-context retrieval",

        "chunk_words":
            90,

        "chunk_overlap":
            30,

        "top_k":
            2,

        "max_sequence_length":
            MAX_SEQ_LENGTH
    },

    "seed":
        SEED,

    "gpu":
        GPU_NAME,

    "gpu_vram_gb":
        GPU_VRAM,

    "lora_rank":
        LORA_R,

    "lora_alpha":
        LORA_ALPHA,

    "lora_dropout":
        LORA_DROPOUT,

    "target_modules":
        LORA_TARGET_MODULES,

    "learning_rate":
        LEARNING_RATE,

    "epochs":
        NUM_EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "gradient_accumulation":
        GRAD_ACCUM,

    "effective_batch":
        EFFECTIVE_BATCH,

    "warmup_ratio_design":
        WARMUP_RATIO,

    "optimizer":
        "paged_adamw_8bit",

    "qlora_quantization":
        "4-bit NF4 + double quantisation",

    "metrics": [

        "Exact Match",

        "token-level F1",

        "average inference latency",

        "median inference latency",

        "peak evaluation VRAM",

        "training time",

        "peak training VRAM"
    ],

    "qwen_reference": {

        "zero_shot_context_file":
            "REF_qwen14b_zeroshot_CONTEXT.json",

        "two_shot_context_file":
            "REF_qwen14b_2shot_CONTEXT.json"
    }
}


PHI_CONFIG_PATH = (
    f"{RESULTS_DIR}/"
    "Phi3Mini_CONTEXT_Experiment_Config.json"
)


with open(
    PHI_CONFIG_PATH,
    "w"
) as f:

    json.dump(
        phi_config,
        f,
        indent=2
    )


print(
    "Saved experiment configuration:"
)

print(
    PHI_CONFIG_PATH
)

Saved experiment configuration:
/content/drive/MyDrive/MR603_Thesis/results/Phi3Mini_CONTEXT_Experiment_Config.json

In [27]:
# ═══════════════════════════════════════════════════════════
# CELL 24 — FINAL PHI FILE CHECK + GPU CLEANUP
# ═══════════════════════════════════════════════════════════

required_files = [

    "REF_qwen14b_zeroshot_CONTEXT.json",

    "R1_phi3mini_lora_CONTEXT.json",

    "R1_phi3mini_lora_CONTEXT_predictions.jsonl",

    "R1_phi3mini_lora_CONTEXT_predictions.csv",

    "R2_phi3mini_qlora_CONTEXT.json",

    "R2_phi3mini_qlora_CONTEXT_predictions.jsonl",

    "R2_phi3mini_qlora_CONTEXT_predictions.csv",

    "Phi3Mini_CONTEXT_RQ2_QuestionType_Results.csv",

    "Phi3Mini_CONTEXT_Final_Results.csv",

    "Phi3Mini_CONTEXT_Experiment_Config.json"
]


if (
    "QWEN_FEW_F1"
    in globals()
):

    required_files.append(
        "REF_qwen14b_2shot_CONTEXT.json"
    )


print(
    "=" * 78
)

print(
    "FINAL PHI-3 MINI CORRECTED FILE CHECK"
)

print(
    "=" * 78
)


all_good = True


for filename in required_files:

    path = (
        f"{RESULTS_DIR}/"
        f"{filename}"
    )

    if os.path.exists(
        path
    ):

        size_kb = (
            os.path.getsize(
                path
            )
            /
            1024
        )

        print(
            f"FOUND   "
            f"{filename} "
            f"({size_kb:.1f} KB)"
        )

    else:

        print(
            f"MISSING "
            f"{filename}"
        )

        all_good = False


print(
    "\nAdapters:"
)


for adapter_name in [

    "R1_phi3mini_lora_CONTEXT",

    "R2_phi3mini_qlora_CONTEXT"

]:

    adapter_path = (
        f"{ADAPTER_DIR}/"
        f"{adapter_name}"
    )

    if os.path.isdir(
        adapter_path
    ):

        print(
            "FOUND:",
            adapter_name
        )

    else:

        print(
            "MISSING:",
            adapter_name
        )

        all_good = False


if all_good:

    print(
        "\n" + "=" * 70
    )

    print(
        "✓ PHI-3 MINI PHASE COMPLETE"
    )

    print(
        "✓ Corrected LoRA + context saved"
    )

    print(
        "✓ Corrected QLoRA + context saved"
    )

    print(
        "✓ Corrected Qwen references linked"
    )

    print(
        "✓ Question-type comparison saved"
    )

    print(
        "✓ Final Phi results saved"
    )

    print(
        "=" * 70
    )

else:

    print(
        "\nSome required files are missing."
    )

    print(
        "Fix missing outputs before moving to Mistral."
    )


for name in [

    "trainer_r2",

    "model_r2",

    "tokenizer_r2",

    "train_tokenized_r2",

    "val_tokenized_r2"

]:

    if name in globals():

        del globals()[
            name
        ]


gc.collect()

torch.cuda.empty_cache()


free_vram = (
    torch.cuda
    .get_device_properties(0)
    .total_memory
    -
    torch.cuda
    .memory_allocated()
) / 1024**3


print(
    f"\nGPU cleanup complete. "
    f"Free VRAM: "
    f"{free_vram:.2f} GB"
)

print(
    "\nPhi-3 Mini complete."
)

print(
    "Next model: Mistral-7B."
)

==============================================================================
FINAL PHI-3 MINI CORRECTED FILE CHECK
==============================================================================
FOUND   REF_qwen14b_zeroshot_CONTEXT.json (1.1 KB)
FOUND   R1_phi3mini_lora_CONTEXT.json (2.1 KB)
FOUND   R1_phi3mini_lora_CONTEXT_predictions.jsonl (652.6 KB)
FOUND   R1_phi3mini_lora_CONTEXT_predictions.csv (489.6 KB)
FOUND   R2_phi3mini_qlora_CONTEXT.json (2.1 KB)
FOUND   R2_phi3mini_qlora_CONTEXT_predictions.jsonl (655.6 KB)
FOUND   R2_phi3mini_qlora_CONTEXT_predictions.csv (493.5 KB)
FOUND   Phi3Mini_CONTEXT_RQ2_QuestionType_Results.csv (0.7 KB)
FOUND   Phi3Mini_CONTEXT_Final_Results.csv (0.8 KB)
FOUND   Phi3Mini_CONTEXT_Experiment_Config.json (1.1 KB)
FOUND   REF_qwen14b_2shot_CONTEXT.json (1.5 KB)

Adapters:
FOUND: R1_phi3mini_lora_CONTEXT
FOUND: R2_phi3mini_qlora_CONTEXT

======================================================================
✓ PHI-3 MINI PHASE COMPLETE
✓ Corrected LoRA + context saved
✓ Corrected QLoRA + context saved
✓ Corrected Qwen references linked
✓ Question-type comparison saved
✓ Final Phi results saved
======================================================================

GPU cleanup complete. Free VRAM: 38.93 GB

Phi-3 Mini complete.
Next model: Mistral-7B.